### ISSUE TITLE
Make markdown editor shortcodes work inline too

### ISSUE THREAD

**Issue by ebernard** [decaporg/decap-cms#1001]
I'd like to integrate mathematical expressions in the markdown component using KaTeX expressions.

I know that I can use a shortcode for that, in my case it would be something like "$$ a^2 - b^2 = (a + b)(a - b)$$" (double $ syntax).

The problem is that I'd also like to be able to have inline mathematical expressions (using single $ expressions, like "to resolve this equation, we compute $\Delta = b^2 - 4ac$ and then..."), and currently shortcodes have limitations:

> Shortcodes are plain text, and must be the lone content of a paragraph. The
> paragraph must also be a direct child of the root node. When a shortcode is
> found, we just need to add data to the node so the shortcode can be
> identified and processed when serializing to a new format. The paragraph
> containing the node is also recreated to ensure normalization.

Why is there this kind of limitation ? Would it be possible to have some kind of inline shortcodes, that would appear inside text contents ? If I prepared a PR would it be accepted ? I guess that for compatibility reasons with existing shortcode patterns we would need to have another kind of shortcodes, right ?

**Comment by ebernard** [comment]
Shortcodes are evaluated after markdown inline codes and that means that something like $a_k + b_k$ would not work as expected. I'll need to figure out another solution, so I'm closing this issue.

**Comment by erquhart** [comment]
Inline shortcodes would be awesome, it just isn't a simple thing to support, and could be costly for rendering performance. Our current regex checking for shortcodes can take advantage of the fact that they occupy an entire line - if we have to check throughout every line, we need to make sure it doesn't bog down the editor for large, complex documents.

**Comment by tech4him1** [comment]
Do we want this re-opened @erquhart?

**Comment by erquhart** [comment]
Yeah, makes sense. @ebernard can you explain a bit more about the issue you ran into with this concept?

**Comment by ebernard** [comment]
As I quickly said, in my example ("$a_k + b_k$"), shortcodes are evaluated after standard markdown, which means that in this case "k + b" would be italic text and "_" would need escaping. That means that shortcodes should be evaluated first.

Another potential problem is that as of now the pattern is supposed to match an entire paragraph. To have the change be backward compatible would mean either change all existing patterns to explicitely match an entire paragraph (by prepending "^" and appending "$" for example) or have another syntax for inline shortcodes (something like CMS.register**Inline**EditorComponent ?).

**Comment by erquhart** [comment]
Gotcha - you're right on all counts, we'd ideally parse shortcodes before anything else and not require that they be block level, but again, this was the initial approach for performance reasons. I believe there were other gotchas as well, but I'm open to efforts toward inline shortcodes.

If a working implementation does happen, we could introduce it behind a [feature flag](https://github.com/netlify/netlify-cms/pull/1003) until 2.0, or perhaps we could accept an object definition for "pattern" that can include `options.inline` as a boolean flag. That'd probably be even better, as it lets those that don't need full text checking for inline shortcodes remain opted out.

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
