### ISSUE TITLE
editor: bare markdown links do not render as one might expect in the preview panel

### ISSUE THREAD

**Issue by fool** [decaporg/decap-cms#1004]
**- Do you want to request a *feature* or report a *bug*?**

*feature* - but some might think it a bug.

**- What is the current behavior?**

*currently, when you use a bare link like https://a.b in markdown, it renders as an unclickable https//a.b in the preview pane of the editor*.  However, most markdown viewers (github, as well as hugo and other SSG's) will render that as a clickable link.  The editor does not and this is not a huge inconvenience or arguably even a misbehavior - but it does diminish the "WYSIWYG" experience vs what I believe might be the common real-world behavior.

**- What is the expected behavior?**

It'd be great if bare links (`https://a.b` NOT `[document](https://a.b)`) were clickable and styled as such in the preview pane.

**- Please mention your CMS, node.js, and operating system version.**

1.0.3/v6.12.3/Ubuntu 14.04 (netlify defaults)

**- Please link or paste your `config.yml` below if applicable.**

No type or widget customization in our yml.

**Comment by erquhart** [comment]
Yeah that was disabled here: https://github.com/netlify/netlify-cms/commit/fddbf8f7f02c96fa4818cc5d2638e32531cc2491

Good point, SSG's are going to generally convert, so we should too.

**Comment by verythorough** [comment]
I think you'd want to be sure that the preview could be configured _not_ to convert, though, too.

**Comment by tech4him1** [comment]
> Good point, SSG's are going to generally convert, so we should too.

@erquhart Do you have any specific examples? I'd expect my MD to come out without extra formatting :).

**Comment by erquhart** [comment]
Hugo is one, and I've seen others (which I'm assuming is why Remark does this automatically). GitHub does it automatically too: https://www.olddvdscreensaver.com

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
