### ISSUE TITLE
Notify users on CMS updates.

### ISSUE THREAD

**Issue by tech4him1** [decaporg/decap-cms#1045]
Currently, if a CMS update is released, there is no way that users/devs are notified. We should probably have some sort of email/notification subscription, or even directly in the CMS. Discussion?

**Comment by tech4him1** [comment]
One way might just be to check the GH releases list, and see if it's on the latest version. If not, popup a notice mentioning the update in the CMS. Developers could turn it off by a config setting (`update_notice: false`). This isn't necessarily fail-proof (e.g. What if we change the repo URL?), so it would take some consideration.

**Comment by ragasirtahk** [comment]
The fastest solution in my opinion would be having an email newsletter to announce new releases and important bug fixes to users.

**Comment by erquhart** [comment]
That's a great solution for keeping folks up to date, totally agree. That said, every CMS I'm aware of either updates itself because it's SAAS, or has in-app notifications when they're available. Especially for security fixes (which could perceivably happen in the future), we want to get max visibility when an upgrade is required.

**Comment by ragasirtahk** [comment]
I would suggest that the notifications be displayed on the /admin page of netlify CMS users.

**Comment by erquhart** [comment]
For sure - at some point Netlify CMS needs as dashboard page.

**Comment by mittalyashu** [comment]
> For sure - at some point Netlify CMS needs as dashboard page.

@erquhart Can you create a separate issue for this?

> That's a great solution for keeping folks up to date, totally agree. That said, every CMS I'm aware of either updates itself because it's SAAS, or has in-app notifications when they're available. Especially for security fixes (which could perceivably happen in the future), we want to get max visibility when an upgrade is required.

How about this?

![figma_2018-09-03_15-59-49](https://user-images.githubusercontent.com/29014463/44982133-705c8e00-af92-11e8-8787-162379c7aed4.png)

**Comment by mittalyashu** [comment]
> Haven't opened a dashboard issue because we haven't yet spent time thinking about the problems it would solve.

Noted, will discuss it in the community.

> Your design looks cool! 

Thanks 😁

> Tt's in establishing a non-intrusive update broadcasting mechanism. Typically open source projects don't include this kind of functionality.

You create a mailing list and send updates to the subscribed people and in that, you can create a heading along with small description which links to the changelog.

OR

You can tell people to subscribe to the [changelog RSS feed](https://logchimp.now.sh/features/#features).

**Comment by inwardmovement** [comment]
Could you at least simply detail update infos in the GitHub releases (which can be subscribed to), or add an rss feed to the blog?

**Comment by erquhart** [comment]
Yep, we need to better at this, 100% agreed.

**Comment by martinjagodic** [comment]
@demshy found a way to generate release notes on GitHub based on changelogs in all packages. If you wish to follow updates, subscribe to the repository on GitHub. You can limit notifications only to releases. See all releases here: https://github.com/decaporg/decap-cms/releases
