### ISSUE TITLE
Using libs for our primary backend API's?

### ISSUE THREAD

**Issue by erquhart** [decaporg/decap-cms#1104]
I'd like us to consider using external libraries for our primary backend interfaces rather than writing low level API functions in first class extensions that have to be documented, maintained, kept up to date, and tested. Originally there was no complete solution for GitHub's API, but there is now. Here's what I've found:

GitHub: [@octokit/rest](https://www.npmjs.com/package/@octokit/rest) ([docs](https://octokit.github.io/rest.js/))
GitLab: [node-gitlab-api](https://github.com/jdalrymple/node-gitlab-api)
Bitbucket: [bitbucket-api-v2](https://www.npmjs.com/package/bitbucket-api-v2)

These are all well-maintained libraries that should cover our needs. GitLab would need a bit of help to get some of the write methods in place, but the framework is in place so that doing so should be straightforward.

Again, the point is to keep our codebase, and thereby our maintenance overhead, as low as possible. Doing this should enable slimmer backend integrations where we're only creating high level methods for Netlify CMS specific actions.

Thoughts?

**Comment by tech4him1** [comment]
We'd want a library that is well-maintained, but didn't have to be updated too often. Of course, that's mostly dependent on the actual API itself, not the client.

(NOTE: The "official" (documented) GitLab client is [node-gitlab](https://github.com/node-gitlab/node-gitlab), but `node-gitlab-api` may be just fine.)

**Comment by tech4him1** [comment]
A library may also be helpful for more complicated, implementation-specific things, like GL pagination.
