### ISSUE TITLE
Support for Gitea

### ISSUE THREAD

**Issue by a-akimov** [decaporg/decap-cms#1109]
Currently, Netlify CMS works only with GitHub, while for many companies this might be not the best option. It would be great if Netlify CMS can also support Gitea (https://github.com/go-gitea/gitea)

**Comment by talves** [comment]
@a-akimov Netlify CMS currently has an option to register your own backend and be able to add your own backend project.

I created a shell example of the backend for `file-system` in [this repository][1].

Anyone can make a backend the same way as GitHub by using the code in the [GitHub backend as an example][2] and replacing the `src` in [my backend example].

[1]: https://github.com/talves/netlify-cms-backend-fs
[2]: https://github.com/netlify/netlify-cms/tree/master/src/backends/github

**Comment by talves** [comment]
@erquhart do you think this issue should be a NetlifyCMS maintained feature (mono-repo) or would this be something we leave open for someone to take on outside the project as I suggested?

**Comment by erquhart** [comment]
Community, but we can leave this open for visibility.

**Comment by techknowlogick** [comment]
Gitea now supports OAuth (will be officially released soon, but for those running nightlies you can use it already): https://github.com/go-gitea/gitea/pull/5378 so this may be easier to implement.

**Comment by gsantner** [comment]
Is there any news on this? Did some subscriber of this issue maybe already work out something for his Gitea installation?

**Comment by lunny** [comment]
This is a good reason why gitea does not have pages like gitlab or github has.

**Comment by gsantner** [comment]
@lunny this is not about gitea pages, I think you missunderstood.

**Comment by lunny** [comment]
I sent a PR https://github.com/igk1972/netlify-cms-oauth-provider-go/pull/9 but don't know that's the right place.

**Comment by erquhart** [comment]
Nice! If that works, it will allow that library to handle authentication for Gitea, but you would still need a Gitea backend - check out the gitlab backend to see what that looks like:

https://github.com/netlify/netlify-cms/tree/master/packages/netlify-cms-backend-gitlab

**Comment by crone11** [comment]
Any update on this?

**Comment by erezrokah** [comment]
Hi @crone11, best way to get this prioritized is up vote the issue as we try to do the most up voted ones first.
Another option is to submit it as a PR (you can use https://github.com/netlify/netlify-cms/pull/3318) as a reference.

**Comment by ShalokShalom** [comment]
At the current time is Gitlab the only open source solution and that one is slow and I personally dislike it. 

The goal of this project is to open source the "CMS for static page" idea and so I think it is important to add choice to the backend. 

Really hope this becomes realized.

**Comment by erezrokah** [comment]
Hi @ShalokShalom we would gladly accept a contribution for this. We have one ongoing for Azure:

**Comment by DevAhmedRagab** [comment]
Any update ?!

**Comment by erezrokah** [comment]
Hi @DevAhmedRagab, see my comment [here](https://github.com/netlify/netlify-cms/issues/1109#issuecomment-698243592). It would be great if someone can continue the work done in https://github.com/netlify/netlify-cms/pull/4384

**Comment by Aeradon** [comment]
Bump! I just found myself in the exact position OP described. We are thinking on using staticCMS as they have a beta support for Gitea right now. Maybe it would be possible to port that functionality from staticCMS to netlify cms, as one is a fork of the other?

**Comment by denyskon** [comment]
@Aeradon 

I authored the Gitea backend for Static CMS 🙃
I can definitely say it would be possible to port it over, but it seems like development of Netlify CMS has stopped and I wonder if a PR would ever be accepted.

**Comment by denyskon** [comment]
> @denyskon Just noticed that they rebranded to "Decap CMS" within the last 2 weeks. Now may be the time to strike?

Yeah, I'm densely following what's happening. The Decap team has announced that they want to resolve dependency issues as their first step, so I would like to wait till that is done. At least for me, Netlify CMS didn't build the last time I tried.

When the problems will be resolved, I could easily port over the backend.

But in any case, because of https://github.com/go-gitea/gitea/issues/14619 I wouldn't consider the backend production-ready.....

**Comment by gfauredev** [comment]
I’m not sure to have the knowledge to port Gitea support by myself, but I’m interested to help if needed.

**Comment by denyskon** [comment]
> I’m not sure to have the knowledge to port Gitea support by myself, but I’m interested to help if needed.

Oh it isn't much, I'd manage it on my own. Just want to wait for the updated codebase :)

**Comment by gfauredev** [comment]
> Gitea now supports OAuth (will be officially released soon, but for those running nightlies you can use it already): [go-gitea/gitea#5378](https://github.com/go-gitea/gitea/pull/5378) so this may be easier to implement.

Ok, and do you think this could prevent the use of an additional server ?

**Comment by gfauredev** [comment]
If I understand well, the auth process as described [here](https://decapcms.org/docs/gitlab-backend/#client-side-pkce-authorization) is not feasible with [Gitea OAuth](https://docs.gitea.io/en-us/oauth2-provider/#client-types) ?

**Comment by jimafisk** [comment]
In that same Gitea doc at the top under [Supported OAuth2 Grants](https://docs.gitea.io/en-us/oauth2-provider/#supported-oauth2-grants) it lists PKCE. Getting it to work however...

> it should be possible to authenticate without a separate server but it’s not an easy task.

This was relatively straightforward to implement with GitLab. I'm just not sure if the PKCE grant is actually working in Gitea. I can't find any working examples or support, but more voices asking for the same couldn't hurt!

**Comment by denyskon** [comment]
> Gitea OAuth supposedly [supports PKCE](https://gitea.com/lunny/gitea/pulls/5378) so you shouldn't need a secret and would be able to authenticate without a separate server (like you can do with GitLab).
> 
> However, I'm trying to do this for a similar project ([Plenti](https://plenti.co/)) and not having much luck: https://discourse.gitea.io/t/oauth-pkce-example/6573

I tried to implement it, but unfortunately Gitea still requires a client secret if doing PKCE. There also is an issue open for that (https://github.com/go-gitea/gitea/issues/17107) but it seems to have stayed unnoticed till now.

**Comment by denyskon** [comment]
I ended up opening a PR for Gitea to create an API endpoint allowing to modify multiple files (https://github.com/go-gitea/gitea/pull/24887). This will make implementing the backend a lot easier and allow for it to work in a more elegant way. When I know in which state it will be merged, I will hopefully soon be able to finally create a PR for Decap.

(cc @jimafisk)

**Comment by denyskon** [comment]
If https://github.com/go-gitea/gitea/pull/25033 gets merged we can also have GitLab-like PKCE 🙂

**Comment by jimafisk** [comment]
@denyskon just want to express huge appreciation to you for picking up and running with both these critical features. Thank you!

**Comment by denyskon** [comment]
Both PRs are merged now for Gitea 1.20 which will be released near the end of June/start of July. I'll try to finish the backend until then so if Decap decides to publish a release shortly after, it'll be ready.
Basically both features merged means that we don't need an additional oauth provider anymore and also that the way we would edit files over API is more production-ready. l
Let's see what happens :)

**Comment by denyskon** [comment]
@martinjagodic How should the package be named? `netlify-cms-backend-gitea` or `decap-cms-backend-gitea` ?

**Comment by denyskon** [comment]
A problem currently is that Gitea doesn't support all the features need for the editorial workflow, but it seems to be required to provide the functions in the backend implementation.
If I don't overlook something, there is no way to define a workflow as not supporting editorial workflow? If so, would you be open to implementing such an option?
Otherwise we would need at least one other new API endpoint on the Gitea side (branch comparison)

**Comment by denyskon** [comment]
I think the PR is ready. It would be nice if somebody would test it before it can be merged. There is a prepared config for https://try.gitea.io in dev-test, you'd just need to create a repo and adjust the config accordingly.
