### ISSUE TITLE
NetlifyCMS handling Staticman comment moderation

### ISSUE THREAD

**Issue by aleksandarbasara** [decaporg/decap-cms#1193]
**- Do you want to request a *feature* or report a *bug*?**

Feature

**- What is the expected behaviour?**

NetlifyCMS handling [Staticman](https://staticman.net) comment moderation.

**Staticman brings user-generated content to static sites like reviews, comments and ratings**

[Staticman Rating Demo](http://popcorn.staticman.net/)

**Comment by erquhart** [comment]
This request seems small, but it has major implications that I'm pretty excited about. Here's why.

Staticman comment moderation happens via pull requests, the same method we're currently using for the editorial workflow. This is going to become a common pattern as git based projects embrace the JAMstack moving forward. That said, the editorial workflow interface isn't ideal for comments for a few reasons:

* Ideally, you'd burn through a bunch of comment approvals and then merge them all at once, in a single build. The editorial workflow produces a commit per item, which would result in a crazy number of superfluous build requests for sites with any volume.
* There should be a way to separate comments from different parts of a site, whereas the editorial workflow combines everything into one view.
* The editorial workflow is a kanban board, and would likely prove cumbersome for comment moderation.

The point is, it should be possible to create entire new views within Netlify CMS, and to have full access to all available data from within those views. This would enable a Staticman plugin to be created with an ideal comment moderation interface and the ability to interact with pull requests as it sees fit.

### Netlify CMS as a platform
This is a precursor to a more detailed writeup that I'll get together at some point, but I thought I'd drop a preview here:

**Every view within Netlify CMS, including the collections view and the editor, should be built as an extension.**

We're just scratching the surface of what can be done on the JAMstack, and Netlify CMS is in position to make all of it user editable, so long as we give the community something to build on. If everything is an extension, and a shared library of UI components is available for continuity, we could make it straightforward to create a dedicated comment moderation view.

So sort of a good news/bad news thing. Good news is, we should definitely support staticman and tools like it, and I believe we're going to. Not as good news is that it's going to take some time. I'll link back to this ticket when a real write up is in place for tracking.

**Comment by robsonsobral** [comment]
I guess this topic could benefit from @eduardoboucas 's opnion.

**Comment by eduardoboucas** [comment]
> I guess this topic could benefit from @eduardoboucas 's opnion.

👋 

Sounds exciting! If there's anything I can do from my end to make Staticman compatible with what you're trying to achieve, I'll be happy to make it happen.

**Comment by michaelkornblum** [comment]
Please forgive my ignorance, as I am really new to all of this, but would it be possible to use Staticman in tandem with NetlifyCMS?

**Comment by erquhart** [comment]
@michaelkornblum yep, they coexist just fine. This issue is just about integrating Staticman moderation into the Netlify CMS UI.

**Comment by mittalyashu** [comment]
> allow extensions to create entire interfaces within Netlify CMS, in which case you could build a file tree manager if you wanted that functionality

@erquhart, as you have mentioned about extension in the issue https://github.com/netlify/netlify-cms/issues/1575#issuecomment-416655560, why don't you add label to this issue like `area: extension`

**Comment by erquhart** [comment]
Because the API's don't exist for this to be an extension yet, that's all.

**Comment by inwardmovement** [comment]
This post from @eduardoboucas may help
https://eduardoboucas.com/posts/2020-12-23-staticman-netlify-functions/

**Comment by martinjagodic** [comment]
Closing as stale
