### ISSUE TITLE
Current user value on config.yaml

### ISSUE THREAD

**Issue by ekoeryanto** [decaporg/decap-cms#1235]
**- Do you want to request a *feature* or report a *bug*?**
*feature*
**- What is the current behavior?**
- imposible to put current user on config.yaml

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**
- current user value can be included in config.yaml 
- example:  `- {label: "Author", name: "author", widget: "hidden", default: "{{userEmail}}"}`

**- Please mention your CMS, node.js, and operating system version.**

**- Please link or paste your `config.yml` below if applicable.**

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
