### ISSUE TITLE
Feat: Add ability to filter folder collection by filename.

### ISSUE THREAD

**Issue by tech4him1** [decaporg/decap-cms#1245]
**- Do you want to request a *feature* or report a *bug*?**
feature

**- What is the current behavior?**
Currently, it is possible to filter a folder collection by a frontmatter value in the entries, but not by the actual filename itself. This would be really nice in cases where, for example, files with underscores in the name need to be filtered out.

**- What is the expected behavior?**
Provide ability to filter folder collections by filename (slug).

This could be really nice along with https://github.com/netlify/netlify-cms/issues/513#issuecomment-378677720, so that "index" pages can be edited separately. For example, `{{slug}}/_index.md` for one collection, and `filter: name: /^[^_]/` for the entries.

**Comment by erquhart** [comment]
I don't think filter allows regexes currently does it?

**Comment by tech4him1** [comment]
@erquhart Well, currently, `filter` only works on frontmatter values.

**Comment by erquhart** [comment]
Right, just clarifying the additional change here.

**Comment by tech4him1** [comment]
Related to #1000.

**Comment by martinjagodic** [comment]
Closing as stale
