### ISSUE TITLE
Having "visitors' post" function.

### ISSUE THREAD

**Issue by ccsource** [decaporg/decap-cms#1268]
Hi guys,
I was thinking is there any way to build a service that let the visitor submit a post and automatically put it in `in review` status and belong to a specified user (let's call `visitor` in this case)?

So we'll have a form with exact fields in our editor, and after visitor submit the form, it'll create a post with user `visitor` and assign it as `in review` status.

Is it possible? Since I can't find any documentation for APIs like this, actually I can only find [API document](https://www.netlify.com/docs/api/) for creating a site, not for creating/updating/deleting posts for the site.

**Comment by siliconchild** [comment]
Something like this would be super awesome!! This will move static much closer to dynamic websites in terms of functionality.  Is there a way to implement a form page that submits pull requests to GitHub.

**Comment by mittalyashu** [comment]
Theoretically I can explain, the process it simple:

Create a form where visitors can submit the blog post, when the users will click the submit button, a pull requests should be created with the post adding the repo.

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
