### ISSUE TITLE
Add hidden date widget that returns the current date

### ISSUE THREAD

**Issue by ghost** [decaporg/decap-cms#1270]
**- Do you want to request a *feature* or report a *bug*?**
Feature

**- What is the expected behavior?**

Please add hidden functionality to the date widget so that the date of creating the post can be returned without bothering the user.

**Comment by erquhart** [comment]
This centers around something that sort of happened by mistake imo - the date widget provides a default value that can only be generated by the widget control component while rendered in the editor - we need some way for this to work when hidden.

**Comment by johnpuddephatt** [comment]
I have the same need – to store the post creation date on the post. Working locally with eleventy I was relying on file creation dates which it will work with but I came across problems [they highlight as a common pitfall](https://www.11ty.dev/docs/dates/#collections-out-of-order-when-you-run-eleventy-on-your-server) when working with Netlify – post creation dates end up out of order.

I did think I could just add a datetime widget that defaults to the current time and assume this won't be altered by the author.

However I need the time to be quite accurate (time not just date) and using a datetime widget the time is when the create new post page is opened, not when the post is created.

**Comment by henval2020** [comment]
any update on this feature/request? I'm having the same need as this one.

**Comment by erezrokah** [comment]
Hi @henval2020, the best way to move this forward is a contribution.

As a workaround I think one could use the [`preSave` event](https://www.netlifycms.org/docs/beta-features/#registering-to-cms-events) to manage dates (add an additional key value to the entry with the creation date if doesn't exist, or assume it's an existing entry if it does exist).

**Comment by martinjagodic** [comment]
This can be achieved with [custom widgets](https://decapcms.org/docs/custom-widgets/), so I'm closing this as not planned.
