### ISSUE TITLE
UTC Timezone for Date Widget (without being a string)

### ISSUE THREAD

**Issue by ghost** [decaporg/decap-cms#1307]
**- Do you want to request a *feature* or report a *bug*?**
Feature
**- What is the current behavior?**
Date widget only returns date in Local Timezone
**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**
Ability to return date in specified timezone

**- Please mention your versions where applicable.**

Netlify CMS version:
Browser version:

Node.JS version:
Operating System:

**- Please link or paste your `config.yml` below if applicable.**

**Comment by tech4him1** [comment]
You sure can, just set the `format` option to a string with the value that you want. It accepts any Moment.js format: https://momentjs.com/docs/#/displaying/format/.

**Comment by tech4him1** [comment]
The output will be a string, if that's what you are asking?

**Comment by siliconchild** [comment]
Yes i was requesting for ISO8601 date in UTC

**Comment by erquhart** [comment]
Should be fixed by #1296.
