### ISSUE TITLE
Image validation

### ISSUE THREAD

**Issue by erquhart** [decaporg/decap-cms#1322]
**- Do you want to request a *feature* or report a *bug*?**

feature

**- What is the current behavior?**

No validation is available for the file/image widgets.

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**

Allow files to be validated by max size, and images by width/height.

**Comment by haileypate** [comment]
I like this a lot. One way I'd use it is to provide my users with a warning that the file they're about to publish is really big and could take too long to load. Or I might provide a warning when the image width is too small and that it may not look right

**Comment by Undistraction** [comment]
Would be great to have validations for:
- Filesize 
- Extension
- Width
- Height
- Aspect ratio (this would need to be a little bit fuzzy to deal with pixel-rounding).

**Comment by mb21** [comment]
How are you people currently preventing your users from uploading very large images? Or do you just resize them in the static site generator step? Do you have some hack in place, or use something like https://github.com/netlify/netlify-cms/blob/master/website/content/docs/uploadcare.md ? Thanks!

btw. I'm really looking forward to https://github.com/netlify/netlify-cms/issues/2243

**Comment by fabianrios** [comment]
one of my editors just upload a 58mb image to it. we need this.

**Comment by mb21** [comment]
As a stopgap, we could at least implement the file size check. The option would probably go into [the YAML config](https://www.netlifycms.org/docs/configuration-options/#media-library) like this?

      media_library:
        config:
          multiple: true # existing option
          maxFileSize: 100000  # in bytes

and then passed through the redux store all the way to `src/components/MediaLibrary/MediaLibrary.js#handlePersist`, where we could do something like:

    if (file.size > config.maxFileSize) {
       // alert ?

What do you think?

**Comment by fabianrios** [comment]
Better than nothing

**Comment by erquhart** [comment]
@mb21 that'd be a great PR, just needs to be camel_case (max_file_size).

**Comment by martinjagodic** [comment]
closed in #3028
