### ISSUE TITLE
Permanent Links via immutable fields?

### ISSUE THREAD

**Issue by brasilikum** [decaporg/decap-cms#1327]
I have the usecase where I need to be able to define fields that can only be set on creation an not changed later. The usecase are permanent links and references between objects.
Is there currently any way to realize this? How do people currently handle this?

Of course I could just tell this to contributors, but enforcing it is always more reliable.

**Comment by erquhart** [comment]
So the value can be updated if it's blank, but once it has a value and the entry is saved, the field is visible but disabled, correct?

**Comment by brasilikum** [comment]
yes!

**Comment by gnfzdz** [comment]
I'm interested in this feature as well. Is this something that you would accept contributions for?

**Comment by martinjagodic** [comment]
This can be achieved with [custom widgets](https://decapcms.org/docs/custom-widgets/), so I'm closing this as not planned.
