### ISSUE TITLE
Consider making isValid something other than an instance method (custom widgets).

### ISSUE THREAD

**Issue by knpwrs** [decaporg/decap-cms#1346]
When a custom widget with an `isValid` method is wrapped in a HOC, the following error is thrown when attemping to publish:

```
Uncaught TypeError: r.wrappedControlValid is not a function
```

It looks like `wrappedControlValid` is never set because my HOC is a stateless component, meaning it cannot be ref'd. The function which sets `wrappedControlValid` returns immediately if a ref is not possible: https://github.com/netlify/netlify-cms/blob/a5d4fd41a4a1f681b117bf6f40ce1263382680a9/src/components/Editor/EditorControlPane/Widget.js#L56-L67

I can probably temporarily fix this with [`toClass()`](https://github.com/acdlite/recompose/blob/936e49fbfd3a70f1beedc2578c39dbdabcf8ef99/docs/API.md#toclass) from recompose, though I'd argue that instance methods on components are sort of a React anti-pattern. I think it would probably be better to pass an `isValid` prop to the custom widgets. This change would ideally be done in a backwards-compatible way as to not bump the major version.

**Comment by erquhart** [comment]
Agreed, definitely open to a PR for this.

**Comment by martinjagodic** [comment]
Closing as stale
