### ISSUE TITLE
JSON files are saved with no newline at the end of file

### ISSUE THREAD

**Issue by kyleoliveiro** [decaporg/decap-cms#1382]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
Netlify CMS saves JSON data **without** a newline at the end of the file.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Configure a collection type with `format: "json"` and `extension: "json"`, then create and publish a new post in the Dashboard.

**- What is the expected behavior?**
JSON file should created **with** newline at the end of the file.

**Comment by erquhart** [comment]
This is being handled under #1302.

**Comment by aaronfranke** [comment]
Any update? #1302 was closed, but it seemed mostly good to go.

To answer the question from @erquhart:

> any reason not to add a trailing newline at the file level, regardless of type?

The POSIX definition of a text file includes that it should end with a newline character. The question is whether or not the file in question is treated as a text file. If it is, then it should have the trailing newline character. If it does not, then by POSIX definition we can only say it is a stream of bytes.

**Comment by tremby** [comment]
Same with YAML files.

**Comment by erezrokah** [comment]
If someone would like to submit a PR for this the place to start is https://github.com/netlify/netlify-cms/blob/26cd552746d6294387b9bdd961a73d5a531bf665/packages/netlify-cms-core/src/formats/frontmatter.ts#L34
