### ISSUE TITLE
"Published" indicator showing even though changes were made during publication

### ISSUE THREAD

**Issue by papandreou** [decaporg/decap-cms#1392]
**- Do you want to request a *feature* or report a *bug*?**

*bug*

**- What is the current behavior?**

If further changes are made to a field while the item is being published, the "Publishing" indicator will turn into "Published" even though the state of the editor does not correspond to what has been persisted. This is bad because:

1) It lowers the confidence wrt. whether the changes have actually been saved
2) It makes it impossible to save the subsequent changes without making further edits, because there is no "Publish" button.

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. Edit an item in a collection
2. Change some text in a field
3. Click Publish
4. While the publication progress bar is showing, make another change to a field

Observe that the "Published" indicator is shown even though the current contents of the fields doesn't correspond to what was persisted.

**- What is the expected behavior?**

That the "Publish" button is shown after the publication has completed, rather than the "Published" indicator.

**- Please mention your versions where applicable.**

Netlify CMS version: 1.8.4
Browser version: Chrome 66.0.3359.181/OSX

Node.JS version: 9.5.0
Operating System: 5.6.0

**- Please link or paste your `config.yml` below if applicable.**

**Comment by tech4him1** [comment]
I think the correct fix would be to lock the fields while publishing. @Benaiah?

**Comment by papandreou** [comment]
Since publication takes a several seconds (at least with the `github` and `git-gateway` backends), I think not locking the fields would give a slightly better UX.

**Comment by erquhart** [comment]
I'd expect the "published" logic to account for changes that happen during the publishing calls.
