### ISSUE TITLE
Cmd+a in markdown widget in editor component doesn't work correctly

### ISSUE THREAD

**Issue by papandreou** [decaporg/decap-cms#1393]
**- Do you want to request a *feature* or report a *bug*?**

*bug*

**- What is the current behavior?**

Clicking Cmd+a while editing the text of a markdown field in an editor component does not select all the text in the field. Instead, it moves the cursor out of the "inner" markdown widget and into the main body one. If you look closely, you can sometimes see that the text in the inner widget is selected, then cleared.

The behavior is slightly different if the main markdown widget has more content than the editor component with the markdown field. In that case, the result is that all text in the main markdown widget is selected, including the text in the custom widget.

I haven't dug into it, but it could seem like the event bubbling isn't cancelled so the event ends up being handled by both markdown editor widgets.

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. Register an editor component that contains a markdown field:

```js
CMS.registerEditorComponent({
  // Internal id of the component
  id: "youtube",
  // Visible label
  label: "Youtube",
  // Fields the user need to fill out when adding an instance of the component
  fields: [{
    name: 'id',
    label: 'Youtube Video ID',
    widget: 'markdown'
  }],
  // Pattern to identify a block as being an instance of this component
  pattern: /^youtube (\S+)$/,
  // Function to extract data elements from the regexp match
  fromBlock: function(match) {
    return {
      id: match[1]
    };
  },
  // Function to create a text block from an instance of this component
  toBlock: function(obj) {
    return 'youtube ' + obj.id;
  },
  // Preview output for this component. Can either be a string or a React component
  // (component gives better render performance)
  toPreview: function(obj) {
    return (
      '<img src="http://img.youtube.com/vi/' + obj.id + '/maxresdefault.jpg" alt="Youtube Video"/>'
    );
  }
});
```

2) Create a new item in a collection that has a `body` field.
3) Insert a Youtube component
4) Enter some text into the `Youtube Video ID` field.
5) Press Cmd+a

Observe that the cursor is moved to the bottom of the main markdown editor.

**- What is the expected behavior?**

That the cursor stays in the `Youtube Video ID` markdown editor and that all the text of the field is selected.

**- Please mention your versions where applicable.**

Netlify CMS version: 1.8.4
Browser version: Chrome 66.0.3359.181/OSX

Node.JS version: 9.5.0
Operating System: 5.6.0

**- Please link or paste your `config.yml` below if applicable.**

**Comment by martinjagodic** [comment]
Closing as stale
