### ISSUE TITLE
Italicising linked text issue

### ISSUE THREAD

**Issue by david-brophy** [decaporg/decap-cms#1394]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
**- If the current behavior is a bug, please provide the steps to reproduce.**
When I highlight some text that has links it it and try to italicise it e.g.

![highlight-and-italicise](https://user-images.githubusercontent.com/31471918/40717683-3884162a-6405-11e8-884c-5126e82f5b52.PNG)

When I go to the text view, this is how it comes out:

![incorrect](https://user-images.githubusercontent.com/31471918/40717684-38a76a26-6405-11e8-8e5d-d61dc55a9cdc.PNG)

And this is how it looks on the frontend:

![incorrect-output](https://user-images.githubusercontent.com/31471918/40717685-38cdcdd8-6405-11e8-821e-09859093e4bf.PNG)

This probably happens when making text bold too.

**- What is the expected behavior?**

This is what should happen when I highlight the text and click italic:

![correct](https://user-images.githubusercontent.com/31471918/40717681-3833637e-6405-11e8-8195-1aca212ffdf4.PNG)

And this is how it should look in the frontend:

![correct-output](https://user-images.githubusercontent.com/31471918/40717682-385a7ea0-6405-11e8-8139-6cb652deb798.PNG)

**- Please mention your versions where applicable.**
Netlify CMS version: ^1.0.0
Browser version: Firefox 60.0.1 64-bit

**Comment by erquhart** [comment]
I began addressing this in #686, but hit a snag and haven't been back to it. On the radar.
