### ISSUE TITLE
Internal Bug: Many internal errors are never shown to the user.

### ISSUE THREAD

**Issue by tech4him1** [decaporg/decap-cms#1430]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
Many of the internal errors the CMS has, especially in critical areas like loading and publishing, are attached to a Redux action, but don't alert the user, leading to a success (or no) message.

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**
All or most internal Redux errors should be accompanied by a notification. If it is an error we can handle on our own, it probably isn't hitting Redux.

**Comment by tech4him1** [comment]
We currently have notifs manually shown for error actions -- what about just binding them to all Redux errors?

**Comment by erquhart** [comment]
Centralized error handling for Redux actions makes sense, we have a lot of repetitive `notif` calls doing the same thing.

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
