### ISSUE TITLE
Nested Editor Components

### ISSUE THREAD

**Issue by moshie** [decaporg/decap-cms#1452]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
Registering nested editor components do not work and are not evaluated inside of the editor

**- If the current behavior is a bug, please provide the steps to reproduce.**

Consider the following hugo shortcode
```md
{{< row >}}
{{% column size="3" break="md" %}}
Column One
{{% /column %}}

{{% column size="9" break="md" %}}
Column Two
{{% /column %}}
{{< /row >}}
```
And the Two Editor Components
```js
// Grid
//
CMS.registerEditorComponent({
    id: "row",
    label: "Row",
    fields: [
        {
            name: 'content',
            label: 'Content',
            widget: 'markdown'
        }
    ],
    pattern: /^{{< row >}}((.|\n)*){{< \/row >}}$/,
    fromBlock: function(match) {
      return {
          content: match[1]
      };
    },
    toBlock: function(obj) {
        return '{{< row >}}' + obj.content + '{{< /row >}}';
    },
    toPreview: function(obj) {
      return (
          '<div class="row">' + obj.content + '</div>'
      );
    }
});

CMS.registerEditorComponent({
    id: "column",
    label: "Column",
    fields: [
        {
            name: 'size',
            label: 'Size',
            widget: 'number',
            min: 1,
            max: 12,
            default: 6
        },
        {
            name: 'break',
            label: 'Breakpoint',
            widget: 'select',
            options: [
                { value: 'sm', label: 'Phone' },
                { value: 'md', label: 'Tablet' },
                { value: 'lg', label: 'Desktop' }
            ],
            default: 'md'
        },
        {
            name: 'content',
            label: 'Content',
            widget: 'markdown'
        }
    ],
    pattern: /^{{% column size="(.*)" break="(.*)" %}}((.|\n)*){{% \/column %}}$/,
    fromBlock: function(match) {
      return {
          size: match[1],
          break: match[2],
          content: match[3]
      };
    },
    toBlock: function(obj) {
        return '{{% column size="' + obj.size + '" break="' + obj.break + '" %}}' + obj.content + '{{% /column %}}';
    },
    toPreview: function(obj) {
      return (
          '<div class="column--' + obj.break + '-' + obj.size + '">' + obj.content + '</div>'
      );
    }
});
```

**- What is the expected behavior?**
When nested Shortcodes are provided to the body they are evaluated by netlify.

![screen shot 2018-06-19 at 13 14 13](https://user-images.githubusercontent.com/3974301/41596595-bde16ce2-73c2-11e8-953a-b51ad840b129.png)

**- Please mention your versions where applicable.**
Netlify CMS version: 1.9.2
Browser version: Google Chrome Version 67.0.3396.87 (Official Build) (64-bit)
Node.JS version: N/A
Operating System: MacOs High Sierra

**- Please link or paste your `config.yml` below if applicable.**
Don't think this is required but please let me know if you need it.

**Comment by erquhart** [comment]
I would consider this more of a feature request since editor components are currently required to be block level components with no parent, so nesting is inherently unsupported.

**Comment by papandreou** [comment]
@moshie, I needed this myself, and ended up making [a terrible hack](https://github.com/papandreou/netlify-cms/compare/c34d012fcc548d8a63fb212904577e53f5e0c1e2...c1b4daf48fd7b056528a53b6d32f9eb9d7839369#diff-e8a45a7f3a4e3b2f6ff4addfb1317601) so that my shortcode syntax is transformed to something shortcode-like (`::: <name> <base64blob>`) before the markdown is parsed (and back again when reserialized). My custom components can then operate on the shortcode syntax.

It's a bit inefficient, but it works.

**Comment by erquhart** [comment]
Yeah, efficiency is precisely why we have the setup that we do. But there certainly comes a point where functionality trumps efficiency. Glad there's a workaround out there for now.

**Comment by robbymilo** [comment]
@moshie Did you ever find a solution? I'd like to try to contribute a solution here as nested shortcodes in previews would be very powerful for editors when making complex layouts. Any guidance @erquhart?

**Comment by moshie** [comment]
It's been a while I no longer work for the company I needed this for. 

Hope you manage to figure it out

**Comment by erquhart** [comment]
@robbymilo major changes have happened in the editor, so this situation may have improved. Are you seeing the same result as described in the original post?

**Comment by schindld** [comment]
Looks like the row/column components are rendered in the control pane now, but not in the preview pane still. The preview pane just shows

```
{{% column size="3" break="md" %}} Column One {{% /column %}} {{% column size="9" break="md" %}} Column Two {{% /column %}}
```

The row's html gets rendered in the preview pane. Here's the rendered html when viewing source:

```html
<div class="row">
{{% column size="3" break="md" %}}
Column One
{{% /column %}}



{{% column size="9" break="md" %}}
Column Two
{{% /column %}}
</div>
```

I think the row's toPreview gets called, but the column's toPreview doesn't.

**Comment by martinjagodic** [comment]
Closing as stale
