### ISSUE TITLE
Custom editor components with kramdown

### ISSUE THREAD

**Issue by bert-bruggeman** [decaporg/decap-cms#1464]
**- Do you want to request a *feature* or report a *bug*?**
Bug/Feature

**- What is the current behavior?**
Links in markdown with some kramdown magic, like `[Title](url){: .button }` can't be mached with a pattern in a custom editor component (code below)

**- What is the expected behavior?**
Default markdown items with kramdown (or other parsers') attributes can be used as editor components  

**- Markdown -** 
```
[A button](url){: .button }
[A second button](url){: .button }
```
**- Editor component -**
```
CMS.registerEditorComponent({
    id: "button",
    label: "Button",
    fromBlock: match => match && {
      title: match[1],
      url: match[2],
    },
    toBlock: data => `[${ data.title || '' }](${ data.url || '' }){: .button }`,
    toPreview: data => `<a href="${ data.url || '' }" class="button">${ data.title || '' }</a>`,
    pattern: /^\[(.*)\]\((.*)\)\{\:\ \.(.*)\ \}$/,
    fields: [{
        label: "Title",
        name: "title",
        widget: "string",
        required: true
      },
      {
        label: "Url",
        name: "url",
        widget: "string",
        required: true
      }],
});

```

**Comment by papandreou** [comment]
Related: https://github.com/netlify/netlify-cms/issues/1044

**Comment by erquhart** [comment]
Yep, exactly, this is due to us parsing Markdown with Remark _before_ processing editor components, as is outlined in the comments of #1044.

**Comment by martinjagodic** [comment]
Closing as stale
