### ISSUE TITLE
tabbed interface for fields

### ISSUE THREAD

**Issue by zolamk** [decaporg/decap-cms#1484]
**- Do you want to request a *feature* or report a *bug*?**
**feature**

**- What is the current behavior?**
right now when we add fields to a collection the fields are displayed one after the other on the same page, which can be daunting for a lot of fields, especially when you have a lot of list widgets.

**- What is the expected behavior?**
So i propose the CMS provides a configuration option that allows us to display a field in its' own tab

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
