### ISSUE TITLE
Combined CHANGELOG and GitHub Releases

### ISSUE THREAD

**Issue by axelboc** [decaporg/decap-cms#1544]
I'm loving the new mono-repo structure, but the [multiple changelogs](https://github.com/netlify/netlify-cms/blob/master/CHANGELOG.md) are going to make it hard to keep up with releases. For v2, I had to track down the [blog article](https://www.netlifycms.org/blog/2018/07/netlify-cms-2-0-launches-with-bitbucket-support-and-a-new-monorepo-architecture/) to even understand what was going on.

Would it be possible to **aggregate all the changelogs into one**, [like they do in Babel](https://github.com/babel/babel/blob/master/CHANGELOG.md), for instance?

Also, I use [GitPunch](https://gitpunch.com/) to keep track of new releases, and having the **changelog right in the GitHub Release** is very convenient. This used to be the case prior to v2.0, so I'd love to see it happen again! ❤️ Either way, thanks for all your awesome work!

**Comment by erquhart** [comment]
Agreed, the current release notes setup is rough. Other monorepo projects seem to be handling it better, such as React and Slate. I'll take a look at GitPunch.

@mittalyashu LogChimp creates external release notes, this issue is about providing release notes within GitHub, which is where developers expect to see them.

**Comment by jadbox** [comment]
There's also this Lerna tool that does changelog rollups:
https://github.com/lerna/lerna-changelog

**Comment by erquhart** [comment]
Looks cool! I'd try it if it could key off of conventional commits rather than requiring labels on every PR. Seems to use the GitHub API instead of Git on the local machine.

**Comment by martinjagodic** [comment]
@demshy found a way to generate release notes based on changelogs in all packages. This works retroactively, so release notes were generated for all versions since decap 3.0. See all releases here: https://github.com/decaporg/decap-cms/releases
