### ISSUE TITLE
CSS Class Support for inline images: alightright, align left

### ISSUE THREAD

**Issue by mryanb** [decaporg/decap-cms#1584]
Is there a way to add a CSS class to an inline image? It seems like the way this is handled in our builder is with something like `![](/images/gracehoppertocat.jpg) {.alignright}` This however breaks the rendering.

**Comment by mryanb** [comment]
Yes it is. I could also see the class being different depending upon the CSS of the site generator too which would be problematic.

**Comment by erquhart** [comment]
That's what editor components are for - check out `registetEditorComponent`: https://www.netlifycms.org/docs/custom-widgets/

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
