### ISSUE TITLE
Create MD version of "Git for Open Source Cheat Sheet" PDF

### ISSUE THREAD

**Issue by cory-wc** [decaporg/decap-cms#1635]
@verythorough has a PDF "Git for Open Source Cheat Sheet". We'd like to have a Markdown version that could be referenced in the Contributor Guide.

**Related Issues**
Issue 1038

**Comment by cory-wc** [comment]
Claiming. :) But I'm not able to find the resources directory that you referenced.

**Comment by verythorough** [comment]
Oops, we were talking about two repos at the same time. When @cory-wc and I chatted about this, I actually had the GDISF teaching materials repo in mind, which is where she ended up PR'ing the file. You can find it here: https://github.com/gdisf/teaching-materials/blob/master/resources/git-for-open-source-cheat-sheet.md

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
