### ISSUE TITLE
[docs] Internal docs links have different formats in site and repo views

### ISSUE THREAD

**Issue by verythorough** [decaporg/decap-cms#1646]
**Describe the bug**
Related to some discussion in #1600 and elsewhere, we currently can't have internal links between docs work in both GitHub and the netlifycms.org site, because they each require different URLs in the markdown.

**To Reproduce**
1. Go to https://github.com/netlify/netlify-cms/blob/master/website/content/docs/start-with-a-template.md
2. Click on the **tutorial** link in the third paragraph.
3. Get a GitHub 404. (The correct URL for the doc is https://github.com/netlify/netlify-cms/blob/master/website/content/docs/start-with-a-template.md)

If the link was changed to point to the correct URL, it would break the link on netlifycms.org.

**Expected behavior**
It would be awesome if links worked in both places. Previously, we fudged this by using all absolute links, but that has some problems of its own.

I think the best solution would be to point the links to the in-repo path, then add a transform to the website build (probably with `gatsby-transformer-remark`), converting the paths to the format required for use on netlifycms.org.

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
