### ISSUE TITLE
List Widget - add option to format front matter output as array

### ISSUE THREAD

**Issue by raniesantos** [decaporg/decap-cms#1682]
## Feature request

**Is your feature request related to a problem? Please describe.**

Its not much of a problem, just a preference.

The list widget currently produces this format in the front matter.

```
mylist:
  - foo
  - bar
```

I would prefer to have an option to tell the widget to output it like this

```
mylist: [foo, bar]
```

Jigsaw (the SSG I use) Jekyll and Hugo (two of the most popular SSGs) support this format. I assume front matter generally works the same across other SSGs.

**Describe the solution you'd like**
Add a `format` option for list widget.

Example: `format: "array"`

```
- {label: "Tags", name: "tags", widget: "list", format: "array", required: false}
```

**Describe alternatives you've considered**

*N/A*

**Additional context**

*N/A*

**Comment by misterr8472** [comment]
I'd like this too. At the same time, it seems Hugo doesn't have a problem with this, so I guess it's not such high priority.

**Comment by raniesantos** [comment]
Any SSG that uses YAML front matter should allow that syntax. At first I thought it was SSG-specific but it's in the default YAML syntax.

**Comment by raniesantos** [comment]
Is no one checking this issue?

**Comment by erquhart** [comment]
Both are valid yaml, why the preference?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by raniesantos** [comment]
Last time I checked NetlifyCMS doesn't produce .md files with arrays formatted like this.

**Comment by raniesantos** [comment]
It's preferrable for me when a post I'm creating has a long list of tags.

When I'm working on the md file in a code editor and there's a lot of them, the vertical list format takes up a lot of screen space before I can scroll down to the content.

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
