### ISSUE TITLE
Introduce an extension registration phase during bootstrapping.

### ISSUE THREAD

**Issue by erquhart** [decaporg/decap-cms#1686]
Extensions can be registered at any time - we should consider registering within a specific phase of bootstrapping to ensure there's a point when no further extensions will be registered.

For example, external media libraries can disable the global Media button, but if no library is registered, the button should show. Because there's no point when we can be sure that a media library won't still be registered, we have to show the button by default, so it's visible for a bit before the media library hides it.

Ideally all registrations would complete while the CMS loading screen is active. 

This isn't really possible when Netlify CMS is used via CDN - we'll likely need to allow the `netlify-cms` convenience package to bypass any such phase and allow registration any time as we do currently.

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
