### ISSUE TITLE
Ability to export content as html from RTF editor

### ISSUE THREAD

**Issue by aovestdipaperino** [decaporg/decap-cms#1746]
**Is your feature request related to a problem? Please describe.**
My blog uses html files instead of markdown. I would love for Netlify CMS to expose an option for each collection to let the user choose the format to use.

**Describe the solution you'd like**
Add an option called output-format. If absent or MD, everything stays as it is. If the option is html, before saving the file to github, the markdown would be converted to html.

**Describe alternatives you've considered**
I tried to use TinyMCE over the text area, but the script is incompatible and doesn't work.
An alternative would be a custom widget, but all the plumbing is already in place in the markdown control that it would be essentially overkill to have a totally separate one vs. an option for the existing one.

**Comment by tech4him1** [comment]
We could just use the `format` parameter that already exists rather than adding a new one.

Should this HTML output support frontmatter, or be pure HTML?

**Comment by tomrutgers** [comment]
The discussion we had on gitter little less than a week ago suggested pure html, generated from the same wysiwyg editor. 

**example of the expected behaviour**
If the `format` is set to `html` clicking the `bold` button results in `<strong>pretty bold text</strong>` instead of `**pretty bold text**`

**Comment by erquhart** [comment]
The CMS originally worked this way, not sure when we moved away from it. HTML was treated the same as Markdown, frontmatter was assumed (Jekyll supports both Markdown and HTML, and frontmatter for both).

**Comment by martinjagodic** [comment]
Closing as stale
