### ISSUE TITLE
Hold stricter markdown standard for preview

### ISSUE THREAD

**Issue by verythorough** [decaporg/decap-cms#1832]
**Is your feature request related to a problem? Please describe.**

Often when writing or editing content in markdown mode in the CMS editor, the preview doesn't represent the same html that will be built in the published site, because the CMS preview parser interprets markdown rules less strictly than the site generator's markdown parser.

Here's an example of two areas where this happens:
<img width="479" alt="sidebysidecompact" src="https://user-images.githubusercontent.com/6111186/47470313-15892b00-d7ba-11e8-97d0-a0276f12bfb5.png">
(Click the image to zoom in.)

In particular:
- The preview parser does not require an empty line before lists. In many generators, the lack of an empty line will cause the generator to interpret the list as part of the preceding content block. It looks like this: - here's a list item - in another block of text.
- The preview parser hides when an ordered list is broken by intermediate content. When you add a block of content between list items, markdown parsers will break the list into two lists, and most will restart the numbering on the second list. To avoid this, you need to indent the intermediate block so that it's treated as part of the first list item. (This is also more accurate semantically.) The preview parser hides this problem by adding a `start` attribute on the second list to match the typed item number.

**Describe the solution you'd like**
The preview parser should:
- display list items as part of the preceding block if they are not separated in the markdown by an empty line.
- not add a `start` attribute to ordered lists.

Here's a DevTools-hacked version of how I think the preview should interpret markdown similar to that in the first image:
<img width="527" alt="beingstrict" src="https://user-images.githubusercontent.com/6111186/47472103-29d12600-d7c2-11e8-8952-a1c5d21d08c2.png">

This will better match the behavior of common generators using stricter parsers, and will not break formatting in situations where the parser is more lax. Editors seeing the broken formatting in the preview will be encourages to fix their markdown, just as if they saw `##Heading` in a preview because they forgot to add a space after `##`.

Here's an example of the _current_ preview with more strictly formatted markdown:
<img width="525" alt="correctformat" src="https://user-images.githubusercontent.com/6111186/47471432-fd67da80-d7be-11e8-9b48-29351008f06a.png">

This doesn't break the preview, and actually matches some of the rich text editor styles. (Rich text inserts an empty line after all blocks and won't unindent indented lines, though there's currently no way to indent items in rich text mode.)

**Describe alternatives you've considered**
Discovering unexpected formatting after the build, and fixing the markdown as a result, I guess! 😛 That, and just remembering that the parser doesn't behave like my generator.

**Additional context**
The demos above were made in cms-demo.netlify.com, running Netlify CMS version 2.1.3

**Comment by erquhart** [comment]
Agreed - I'd like to see us eventually adapt markdown parsing based on the SSG in use, and even with consideration of SSG configuration, but for now at least getting closer to what _most_ SSG's do would be great.

**Comment by martinjagodic** [comment]
Closing as stale
