### ISSUE TITLE
investigate using popup + React.createPortal for previews instead of iframe

### ISSUE THREAD

**Issue by sw-yx** [decaporg/decap-cms#1891]
**Is your feature request related to a problem? Please describe.**

iframes are bad

**Describe the solution you'd like**

use react portals instead!

**Describe alternatives you've considered**

no change

**Additional context**

@erquhart wants it https://twitter.com/erquhart/status/1064645761277808645

in response to @ryanflorence's tweet

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
