### ISSUE TITLE
Links in Changelogs are broken

### ISSUE THREAD

**Issue by davidkazuhiro** [decaporg/decap-cms#1956]
**Describe the bug**
Links in the Changelog are broken.

**To Reproduce**

Go to  [packages/netlify-cms-core/CHANGELOG.md](https://github.com/netlify/netlify-cms/blob/a892ab16a1a0178e08fde17cfc7607527b6f2cfa/packages/netlify-cms-core/CHANGELOG.md)

```
* **netlify-cms-core:** duplicate key warning ([#1930](https://github.com/netlify/netlify-cms/tree/master/packages/netlify-cms-core/issues/1930)) ([9662eb2](https://github.com/netlify/netlify-cms/tree/master/packages/netlify-cms-core/commit/9662eb2))
```

Generates

> * **netlify-cms-core:** duplicate key warning ([#1930](https://github.com/netlify/netlify-cms/tree/master/packages/netlify-cms-core/issues/1930)) ([9662eb2](https://github.com/netlify/netlify-cms/tree/master/packages/netlify-cms-core/commit/9662eb2))

**Expected behavior**
It should be

```
* **netlify-cms-core:** duplicate key warning (#1930) (9662eb2)
```

which generates

> * **netlify-cms-core:** duplicate key warning (#1930) (9662eb2)

**Note**
Originally submitted PR to the CHANGELOG in #1942 without realizing that the changelogs are auto-generated by Lerna. So closed that PR and created this issue as suggested by @erquhart

**Comment by erquhart** [comment]
Thanks @davidkazuhiro! We'll see if anyone is up for digging in.

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
