### ISSUE TITLE
Rich Editor removes table column alignment

### ISSUE THREAD

**Issue by joerneu** [decaporg/decap-cms#1962]
**Describe the bug**

As soon as I edit anything in the Rich Editor any table column alignment is removed.

**To Reproduce**

Go to 

[CMS Demo](https://cms-demo.netlify.com/)

Switch to Markdown and enter:

```
Table:

| Left | Center | Right |
|------|:------:|------:|
| L1   | C1     | R1    |
| L123 | C123   | R123  |

```

Switch to Rich Editor:

=> Preview is correct.

- Type anything, anywhere, even outside of the table

=> Preview changes and all table cells are left-aligned.

Switch to Markdown:

Table is now:

```
| Left | Center | Right |
| ---- | ------ | ----- |
| L1   | C1     | R1    |
| L123 | C123   | R123  |

```

**Expected behavior**

Editing the document in the Rich Editor should not change the table's columns' alignments.

**Applicable Versions:**

 - Netlify CMS version: 2.3.1
 - Browser version All

**CMS configuration**

Official demo site.

**Comment by erquhart** [comment]
This is a symptom of the CMS not technically supporting tables yet. General issue here: https://github.com/netlify/netlify-cms/issues/961

Leaving this open for now.

**Comment by joerneu** [comment]
Ok, I understand.

A table widget as described in [#961](https://github.com/netlify/netlify-cms/issues/961) would be the "perfect" solution.

If the current version of Netlifly CMS could preserve the text alignment of a table column, I could wait for the perfect solution. As it is, unfortunately, I cannot use it at all.

Currently, the Rich Editor handles tables nicely. They are displayed for editing and in the preview. If the Rich Editor would not remove the text alignment, it would be enough to start with.

Maybe the enhancement could be a two step process:

1. Preserve special markdown like table column text alignments
2. Add a table widget with UI

**Comment by erquhart** [comment]
The issue is that our editor is mostly adherent to commonmark, whereas table alignment is a GFM (GitHub flavored markdown) thing. We don't currently have options for configuring that, but it's worth looking into.

**Comment by missmatsuko** [comment]
Is this actually still an issue? I tried pasting in the Markdown and switching between Rich Text and Markdown and the colons were not removed from the Markdown code. The preview also renders the columns with alignment classes.

**Comment by joerneu** [comment]
In the current version of the demo it is still an issue. The alignments of the columns are removed **after** you type something in the Rich Editor.

**Comment by erquhart** [comment]
Update: this is not a general issue for supporting tables in markdown, created #2845 for that. Will leave this open as it targets a specific aspect of support.

**Comment by martinjagodic** [comment]
Closing as stale
