### ISSUE TITLE
Reimplement all-contributors using bot

### ISSUE THREAD

**Issue by tech4him1** [decaporg/decap-cms#2015]
**Is your feature request related to a problem? Please describe.**
https://github.com/all-contributors/all-contributors-bot/issues/5

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tech4him1** [comment]
@erquhart @talves @verythorough Any reason to hold off on this?

**Comment by erquhart** [comment]
@tech4him1 I assumed the bot handled merge conflicts proactively (not sure why I made that assumption, it's nontrivial functionality). Adding contributors wasn't the part I was most concerned with automating - it was rebasing pull requests when they inevitably conflict with one another. I'd like to see that functionality before bringing this back personally.

There's discussion here: https://github.com/all-contributors/all-contributors-bot/issues/62

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tech4him1** [comment]
@erquhart Right, I agree with you on that. What if the bot just pushed, without creating a PR?

**Comment by erquhart** [comment]
Oh just saw your comment about directly committing, that might be an even better option!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by verythorough** [comment]
This would be so great!

I like the idea of committing directly to avoid PR merge conflicts.

**Comment by jakebolam** [comment]
We recognize there is a gap here. We're totally planning to address this and have netlify and many others benefit from this. 

Some UX we've seen is users regularl tag the wrong user, typos/auto complete. This same problem affects mentioned contributions. 

Before we proceed on either option we will get an RFC going. (I think it would be difficult to support both right now). 

Some discussion has started here and on https://github.com/all-contributors/all-contributors-bot/issues/62

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
