### ISSUE TITLE
Support for AWS CodeCommit

### ISSUE THREAD

**Issue by jpray** [decaporg/decap-cms#2070]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I am wondering if it support for AWS CodeCommit has been considered.  Based on their [API docs](https://docs.aws.amazon.com/codecommit/latest/APIReference/Welcome.html), how hard might it be to add it? 

**Describe alternatives you've considered**
None

**Additional context**
I love this project!

**Comment by talves** [comment]
This is a good question. It would definitely be feasible. How hard is relative to knowledge of the API and writing a custom backend for the CMS.

**Comment by erquhart** [comment]
I can hardly imagine a service that one could not create a backend for, the question is how robust that backend can be. CodeCommit doesn't really provide a Git API, so you can't work directly with blobs and trees, or even make commits (only directory via `PutFile`.

Almost certainly possible to do, just need to work through the caveats.

**Comment by talves** [comment]
> Git API, so you can't work directly with blobs and trees, or even make commits (only directory via `PutFile`.

What other commits would be missing?

**Comment by erquhart** [comment]
For example, we want to do multiple files per commit for batching content in the workflow, but we can't with this API, as we don't control commits. You create or update a single file at a time and their platform generates the commit.

**Comment by jpray** [comment]
That makes sense.  CodeCommit is pretty lackluster overall, and the limited API is a bummer.  It's really cool that Netlify CMS can use such APIs right from the frontend.  Has there been discussion around having an optional backend app that that would work on a local version of the repo and then push those changes to cloud git instances?  A more complex setup, but maybe it would simplify the interfaces with cloud providers?

**Comment by talves** [comment]
@jpray I am in the works on something that uses that strategy. Eventually, I hope to release more info if I can get it off the ground.

**Comment by jpray** [comment]
I really like what you all have done with this CMS.  For now I'm using Github, but if the powers that be demand I bring things inside AWS, then perhaps I'll be able to spend time working on a CodeCommit integration.  Might be slower and generate an uglier git history, but it's good to hear that it should be possible.  Cheers!

**Comment by caarl** [comment]
@jspray @talves This recent announcement may help with integration: https://aws.amazon.com/about-aws/whats-new/2019/02/aws-codecommit-supports-programmatic-creation-of-commits-contain/

**Comment by erodrig** [comment]
Comment so this keeps open, I in particular will like this, given my sites are huge.

Some context any medium size blog will have a couple hundred entries each one will contain images, 
so my sites are like 5G in size, on images that need to be converted to generate responsive representations, I need AWS power for doing that, is supper slow to use open CI platforms for this.

**Comment by erquhart** [comment]
Curious, what static site generator(s) are you using, if any?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by erodrig** [comment]
Gatsbty, of course someone will say just pay some cloud service for the images, but I will lose so many features from gatsby and will need to do stuff manually to pull all variations of the images

**Comment by erquhart** [comment]
Gotcha. Just use GitHub with AWS. I'm sure we'll get a CodeCommit backend at some point, but it isn't required for your use case.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by erquhart** [comment]
Would love to see this. I'm hoping to see us consolidate a lot of general backend logic to a shared library, which _should_ make individual backends a lot more straightforward to create, but hard to say for sure.

**Comment by k3a1zzz** [comment]
+1

**Comment by dronaar** [comment]
+1

**Comment by erquhart** [comment]
Please do not post “+1” comments, they cause everyone subscribed to this issue to be notified unnecessarily.

You can signal your request for this to be prioritized by “thumbing up” the initial post up top.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kevbarns** [comment]
Is there any news regarding this topic ? still open, no assignee(s) and no comment since last year 🥴

**Comment by erezrokah** [comment]
Hi @kevbarns, this is open for community contribution.
See work in progress for https://github.com/netlify/netlify-cms/pull/4384 and https://github.com/netlify/netlify-cms/pull/4427

**Comment by benhulan** [comment]
@kevbarns I would be happy to help you with this, if possible

**Comment by mnordhaus** [comment]
Does this issue still make sense?
AWS Discontinues Code Commit: https://aws.amazon.com/de/blogs/devops/how-to-migrate-your-aws-codecommit-repository-to-another-git-provider/

**Comment by martinjagodic** [comment]
@mnordhaus, thanks for pointing this out. Let's focus on backends that we already support. Since AWS discontinued its service, we will not pursue this, so I'm closing this issue.
