### ISSUE TITLE
Standardized commits with commitizen support

### ISSUE THREAD

**Issue by lmcorreia** [decaporg/decap-cms#2075]
**Is your feature request related to a problem? Please describe.**
Coming from some time away from this project, it took me a bit to figure out everything I needed to do for my contributions to be ready for review without creating much hassle for the reviewers.

**Describe the solution you'd like**
Due to the problem briefed above, I think it would be beneficial to try to implement something like https://github.com/commitizen/cz-cli

**Describe alternatives you've considered**
Honestly haven't searched for anything similar. ¯\_(ツ)_/¯

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
