### ISSUE TITLE
Image upload fails with 500 error 

### ISSUE THREAD

**Issue by aamorozov** [decaporg/decap-cms#2106]
It errors in both cases when uploading into the media folder and when uploading within the image widget directly. 

Exists for me in netlify-cms >2.4.0, testing with earlier versions at the moment. The netlify identity is configured for github. 

Here is the error stack:

![screen shot 2019-02-18 at 10 22 53 pm](https://user-images.githubusercontent.com/10227658/52988085-e8e1ca80-33cb-11e9-8ca8-26e8875f41a0.png)

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
