### ISSUE TITLE
Large Media git LFS errors (when site has a global Netlify password)

### ISSUE THREAD

**Issue by sanscheese** [decaporg/decap-cms#2148]
**Describe the bug**
After setting up Large Media for repo, I am unable to work (`push`, `pull`, `clone` etc) with the remote repo if LFS items are added in the media folder.

Error in terminal from `git pull` after uploading an image via remote NetlifyCMS admin:

```
Downloading static/images/cms/kendal-james-1413779-unsplash.jpg (3.3 MB)
Error downloading object: static/images/cms/kendal-james-1413779-unsplash.jpg (35441d0): Smudge error: Error downloading static/images/cms/kendal-james-1413779-unsplash.jpg (35441d0b9617530a17efd169d2e32fcdc4d0de248aeff608b1f04911c6fcd185): batch response: Expected json type, got: "text/html"
 
Errors logged to /Users/ME/Sites/my-site/.git/lfs/logs/20190307T172529.144713.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: static/images/cms/kendal-james-1413779-unsplash.jpg: smudge filter lfs failed
First, rewinding head to replay your work on top of it...
Downloading static/images/cms/kendal-james-1413779-unsplash.jpg (3.3 MB)
Error downloading object: static/images/cms/kendal-james-1413779-unsplash.jpg (35441d0): Smudge error: Error downloading static/images/cms/kendal-james-1413779-unsplash.jpg (35441d0b9617530a17efd169d2e32fcdc4d0de248aeff608b1f04911c6fcd185): batch response: Expected json type, got: "text/html"
 
Errors logged to /Users/ME/Sites/my-site/.git/lfs/logs/20190307T172530.067361.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
```

**To Reproduce**
- Set up Netlify Large Media for project (commit `.netlify/state.json` and `.gitattributes`) 
- Log in to the NetlifyCMS and upload image to Media section

**Applicable Versions:**

 - Netlify CMS version: 2.5.1
 - Git provider: GitHub
- OS: Mac
 - Browser version chrome 72

**CMS configuration**
```
backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor

media_folder: "static/images/cms"
public_folder: "/images/cms"

collections:
...
```

**Additional Info:**
- updated image shows in Netlify Large Media control panel
<img width="1139" alt="screenshot 2019-03-07 at 17 43 14" src="https://user-images.githubusercontent.com/313383/53977272-92c99280-4100-11e9-9d45-6594e2659d73.png">

- File in GitHub
<img width="1000" alt="screenshot 2019-03-07 at 17 42 17" src="https://user-images.githubusercontent.com/313383/53977326-ae349d80-4100-11e9-996e-0a002011dc1a.png">

**Comment by sanscheese** [comment]
I have narrowed down this issue is occurring due to the Netlify site having a global password. Is this a known limitation? The hope has been to be able to have a password protected staging version.

**Comment by frankspin89** [comment]
i encountered the same problem

**Comment by abstracthat** [comment]
Also ran into this. Removing the password fixes it but that seems like a problem for a project in pre-production still.

**Comment by martinjagodic** [comment]
Closing this as stale, because Netlify Large Media is deprecated.
