### ISSUE TITLE
Bold headers not shown while editing rich text

### ISSUE THREAD

**Issue by dotellie** [decaporg/decap-cms#2388]
**Describe the bug**

When editing in the markdown component using the rich text mode, there is no distinction between normal and bold text within a heading. This is also a problem with the preview but that's not my main problem at least.

**To Reproduce**

1. Go to edit a page
2. Using the markdown mode of the markdown widget, insert the following on a new line `## A partially **bold** header`
2. Switch to rich text mode

**Expected behavior**

I should be able to see that the header is bold where it's bold.

**Screenshots**

![image](https://user-images.githubusercontent.com/4590037/59698027-270ebf80-91ef-11e9-8553-c12b332fc135.png)

**Applicable Versions:**

 - Netlify CMS version: 2.9.1
 - Git provider: GitLab
 - OS: Fedora 30
 - Browser version Chrome 73

**Comment by erquhart** [comment]
cc/ #2402

**Comment by lorenzode** [comment]
I can confirm this, one of our content editors reported this:

"There is also an issue when switching between rich text and markdown, headings don't reflect in markdown, for instance (nor do italic, numbers etc.). They work only if manually inserted in markdown but then they don't show in rich text mode."

**Comment by martinjagodic** [comment]
Closing as stale
