### ISSUE TITLE
Document that Netlify CMS Gatsby plugin should be registered last

### ISSUE THREAD

**Issue by erquhart** [decaporg/decap-cms#2392]
#2012 outlined an issue that was due to a webpack-altering Gatsby plugin being registered after the Netlify CMS plugin. Gatsby plugins that alter the Webpack config, and potentially others, such as those that alter the Babel config, must be registered before the Netlify CMS plugin because the CMS plugin creates a new build using the Webpack/Babel config, so plugins that come after don't get the chance to influence that build.

We should document specifics, but ultimately recommend that the Netlify CMS plugin be registered as late as possible. Only plugins that specifically require being registered last should come after.

Docs targets:

- Netlify CMS docs Gatsby guide
- Gatsby docs Netlify CMS guide
- `gatsby-plugin-netlify-cms` readme

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
