### ISSUE TITLE
create a better widget for content editing similar to medium.com or WP Gutenberg

### ISSUE THREAD

**Issue by badpenguin** [decaporg/decap-cms#2398]
**Is your feature request related to a problem? Please describe.**

Following the documentation i've created a "blog" collection with a "body" field that uses the default "markdown widget".
This results in a very poor editor with very few features.
Many peoples nowadays are used to medium.com or WP Gutenberg.

A basic list of the missing features i see, are:
- set image's align and size;
- arrange content's blocks via drag and drop;
- add youtube/vimeo videos easily;
- add block of source code with syntax highlight;

**Describe the solution you'd like**
It would be nice to have a new widget that integrates a better editor.
For example this seems to be usable: https://github.com/front/gutenberg-js

I don't know if the tricky part is to have a markdown output,
honestly on the site generator i can parse anything you will throw at me
and i don't strictly require markdown.

**Comment by tomrutgers** [comment]
Related to https://github.com/netlify/netlify-cms/issues/1503 and https://github.com/netlify/netlify-cms/issues/245

**Comment by erquhart** [comment]
The markdown widget is almost finished being completely revamped, stay tuned. Much of what you're talking about will either be addressed or at least have a better path forward.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by badpenguin** [comment]
> The markdown widget is almost finished being completely revamped, stay tuned.

Thanks for the good news! Any idea in which version number will be released?

**Comment by badpenguin** [comment]
> Much of what you're talking about will either be addressed or at least have a better path forward.

If is it available in some online branch i will be happy to do testing

**Comment by erquhart** [comment]
You can follow #2402 for updates 👍

**Comment by andreaslans** [comment]
Can this be viewed as fixed?

I am investigating netlify CMS as a lightweight alternative for those of our customers that dont have the need for our "fullblown" option of Wagtail CMS.

But it is not clear to me how we could create an "open ended" editing experience for our editors right now in Netlify CMS. In Wagtail we have the concept of a "streamfield" a JSON representation of data where the editor can freely add one or many premade blocks (made by us) in any order they wish. How can we achieve something like this in Netlify CMS? 

The fields option in the config.yaml seems to locked down, and the markdown widget do not seem to support blocks in this way, or am I missing something?

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
