### ISSUE TITLE
Utilize space more effectively in admin screen design

### ISSUE THREAD

**Issue by austincondiff** [decaporg/decap-cms#2536]
I know this was mentioned in #1356 and #1122, but is there any progress made in allowing users to utilize their full viewport instead of constraining the editor and preview to a set pixel amount? It seems like it is as simple as removing `max-width` property from the container div.

That being said, it would be nice for the main collections area to be full width as well. I know there currently isn't a whole lot being displayed at the moment, however I would be in favor of adding more details such as the last modified date to both make these screens more useful and fill up the space.

Additionally, as I am editing an entry, especially regarding objects and lists, it seems to take up a large amount of space. I need to scroll a ways down and I can only see a few items at a time. I feel that we could do a little better here.

**Comment by erquhart** [comment]
We're totally open to PR's for the improvements that folks want to see!

**Comment by martinjagodic** [comment]
Closing as stale
