### ISSUE TITLE
Nuxtjs Documentation cant get it to work

### ISSUE THREAD

**Issue by enricoschaaf** [decaporg/decap-cms#2659]
**Describe the bug**
After following the guide on how to set up nuxtjs + netlify-cms i will get the ERROR Could not resolve routes when running the generate command. Also i get FATAL Invalid left-hand side expression in prefix operation.

**To Reproduce**
To reproduce you basiclly just have to follow the docs on how to set up nuxt and netlify cms, the error happens to me when i start to add
`  generate: {
    routes: function () {
      const fs = require('fs');
      return fs.readdirSync('./assets/content/blog').map(file => {
        return {
          route: `/blog/${file.slice(2, -5)}`, // Remove the .json from the end of the filename
          payload: require(`./assets/content/blog/${file}`),
        };
      });
    },
  },`

**Expected behavior**
I expected this part of the code to generate the routes for the blog articles

**Screenshots**
![Capture](https://user-images.githubusercontent.com/54645197/64440784-e37c7100-d0cc-11e9-9278-e4743f08f1ba.PNG)
)

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [GitHub]
 - OS: [e.g. Windows 10]
 - Browser version [chrome  76.0.3809.132]

 - Node.JS version:  v12.6.0 >(using NPM)

**CMS configuration**
`backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'assets/content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }`

**Additional context**
Full github repository
https://github.com/enricoschaaf/github-issue

**Comment by enricoschaaf** [comment]
I closed it because I found the instruction as a template on Twitter by the same user.
https://github.com/xdesro/nuxt-netlify-cms-starter
Don't know what I did wrong but this solved it for me. Maybe it could be linked in the docs.

**Comment by nttdataxd** [comment]
I am also getting an error after following the docs and trying to run generate, was there ever any fix to this or is https://github.com/xdesro/nuxt-netlify-cms-starter now the real starter?

**Comment by brachkow** [comment]
Examples from docs still lead to this errors. For myself I resolved this issue via 
```
generate: {
    async routes() {
      const contentPaths = ['docs'];

      const files = [];
      contentPaths.forEach(async (path) => {
        const file = await $content(path).fetch();
        files.push(file);
      });

      const generated = files.map((file) => {
        return {
          route: file.path === '/index' ? '/' : file.path,
          payload: fs.readFileSync(`./content/${file.path}${file.extension}`, 'utf-8'),
        };
      });

      return generated;
    },
  },
```

**Comment by erezrokah** [comment]
Re-opening the issue until we can verify the guide

**Comment by s-en-o** [comment]
(Context: deploying with Netlify by following docs from [NetlifyCMS with Nuxt](https://www.netlifycms.org/docs/nuxt/))

I tried https://github.com/xdesro/nuxt-netlify-cms-starter but still throwing error (also in Vercel) and solution suggested by @brachkow is the one that works for me. (Quoted below).

> 
> 
> Examples from docs still lead to this errors. For myself I resolved this issue via
> 
> ```
> generate: {
>     async routes() {
>       const contentPaths = ['docs'];
> 
>       const files = [];
>       contentPaths.forEach(async (path) => {
>         const file = await $content(path).fetch();
>         files.push(file);
>       });
> 
>       const generated = files.map((file) => {
>         return {
>           route: file.path === '/index' ? '/' : file.path,
>           payload: fs.readFileSync(`./content/${file.path}${file.extension}`, 'utf-8'),
>         };
>       });
> 
>       return generated;
>     },
>   },
> ```

Thanks @brachkow 🙏🏼

**Comment by martinjagodic** [comment]
Closing as outdated
