### ISSUE TITLE
Please allow me to add some text before toggle icon by using Boolean Widget

### ISSUE THREAD

**Issue by DamengRandom** [decaporg/decap-cms#2677]
Please allow me to add some text content before the boolean toggle icon by using 'Boolean Widget'.

Thus, user can directly see what content switched on or off.

Cheers,

Netlify CMS team

**Comment by d4rekanguok** [comment]
Would setting a hint & a clear label be enough for your use case?

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
