### ISSUE TITLE
Save netlify URL in project instead of globally

### ISSUE THREAD

**Issue by saenglert** [decaporg/decap-cms#2702]
**Is your feature request related to a problem? Please describe.**
Netlify saves the netlify URL for local development globally instead of an on project basis.

This means if I am working on two projects A and B and I set up A before B, B will use As netlify URL to pull for example collections.

When logging in to the backend via netlify identity there is an option to reset the development URL, however logging out/in and changing the URL manually every time I switch projects is quite tedious. 

**Describe the solution you'd like**
The development URL should be set per project for example in `config.yml` under `backend.netlifyurl` and be used from there instead of being manually added.

**Describe alternatives you've considered**
I considered doing it manually all the time but then again I'm a programmer and I like to automate things.

**Additional context**
This feature request could be part of #2335 to improve the local development experience.

**Comment by saenglert** [comment]
Just ran across this case:

Steps
* Switching from Netlify project A to B
* The same user exists on netlify site A and B (for example an admin account) 
* The current branch of B doesn't exist on A

Result
Stuck at login with "Branch not found" message and no option to log out.

**Comment by erquhart** [comment]
Agreed that we need to improve this, the rub is that it's handled externally through [`netlify-identity-widget`](https://github.com/netlify/netlify-identity-widget), so ideally the solution would happen there.

**Comment by martinjagodic** [comment]
Closing as stale
