### ISSUE TITLE
An option to disallow editing folder collection items

### ISSUE THREAD

**Issue by gitjul** [decaporg/decap-cms#2734]
**Is your feature request related to a problem? Please describe.**
My issue is related to the problem with the identifier field and slug not staying in sync after a collection item is updated. https://github.com/netlify/netlify-cms/issues/1576
The "solution" I thought of to this issue in my blog is to simply not allow updating a collection item, in my case a tag/category - the user should have to remove the old and create a new one instead.

**Describe the solution you'd like**
I would like the possibility to enable creating and deleting items in a folder collection without allowing users to edit them.
Would probably be simplest if it was a configuration option:

```
create: true
edit: false
```

**Additional context**
I'm opening this as a feature request but my first intention is to ask whether there is already something like that in place. So far I wasn't able to find it, if there is a way to achieve this already please point me to it. Thanks!

**Comment by erquhart** [comment]
Definitely a problem worth solving - I do think that updating the slug is still ideal. If we were to go the route you're describing, though, I'd rather see disallowing edits per-field rather than to an entire entry.

**Comment by gitjul** [comment]
> If we were to go the route you're describing, though, I'd rather see disallowing edits per-field rather than to an entire entry.

Yes, this sounds even better, definitely.

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
