### ISSUE TITLE
CMS writes to wrong file

### ISSUE THREAD

**Issue by Juhannuspukki** [decaporg/decap-cms#2739]
**Describe the bug**
My customer somehow managed to create a blog post that ended up overwriting a completely unrelated page of the site. 

**To Reproduce**
Unknown, but you can see it happening here, [commit f097814](https://github.com/Juhannuspukki/empire/commit/f0978145226c42dee8a03f9c5aa8176ae1234c82):
https://github.com/Juhannuspukki/empire/commits/master

It is worth noting that the file being overwritten was edited slightly before, in [commit 3339792](https://github.com/Juhannuspukki/empire/commit/3339792b67dcb704d59b1b7d5fa7afe36a318c4a).

I tried writing a test blog post after this happened and it worked as expected.

**Expected behavior**
Creating a blog post creates a blog post instead of overwriting a random file.

**Applicable Versions:**
 - Netlify CMS version: 2.9.7
 - Git provider: GitHub
 - Browser version: unknown

**CMS configuration**

Item the user tried to create:

```
- label: "FI Blogposts"
    name: "fi-blogposts"
    folder: "site/content/finnish/blogi"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    filter: {field: "isPost", value: true}
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Banner", name: "banner", widget: "image"}
      - {label: "Banner alt text", name: "alt", widget: "string"}
      - {label: "Is post?", name: "isPost", widget: "hidden", default: true}
      - {label: "Body", name: "body", widget: "markdown"}
```

The item that ended up being edited was located in
site/content/finnish/palvelut/_index.md

Editorial workflow is enabled.

[Full config here.](https://github.com/Juhannuspukki/empire/blob/master/site/static/admin/config.yml)

**Comment by erquhart** [comment]
^2.13 is the semver range, what version is printed to the console when the CMS loads?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Juhannuspukki** [comment]
> ^2.13 is the semver range, what version is printed to the console when the CMS loads?
> 
> Sent with [GitHawk](http://githawk.com)

Version 2.9.7, updated the original post as well

**Comment by erquhart** [comment]
Wow that's strange - my guess is that the title of that blog post,  `Palvelut`, has something to do with it, as that's in the path of the actual updated file. Definitely need to look into this.

**Comment by Juhannuspukki** [comment]
Issue still occurs after disabling editorial workflow. See [this commit.](https://github.com/Juhannuspukki/empire/commit/f0f7ce72dd2d5cdc315f179826e1796907caf57d)

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
