### ISSUE TITLE
No return after clicking "prevent this page from creating further dialogs"

### ISSUE THREAD

**Issue by michi-zuri** [decaporg/decap-cms#2822]
When testing Netlify with a potential customer (in a setting similar to a low-budget usability testing described by Steve Krug in his famous book Don't Make Me Think) I saw how the test person clicked the checkbox to prevent further dialogs. This caused her not to be able to finish a simple task: "create a new FAQ entry, then delete it".

1. Go to https://cms-demo.netlify.com/
2. Click login
3. Click on quick add-> FAQ
4. Write something, then click Save
5. Now click on Delete and cancel
6. click on Delete again and tick the checkbox to prevent further dialogs, then cancel. 
7. Try to delete the page now, a normal person will not succeed within a few minutes.

**Expected behavior**
No possibility to silence confirmation dialogs. 

**Applicable Versions:**
Netlify CMS demo available here: https://cms-demo.netlify.com/
netlify-cms-app 2.9.8-beta.4
netlify-cms-core 2.13.0-beta.4
netlify-cms 2.9.8-beta.4
Browser versions: [Firefox quantum 69.0.1, Microsoft Edge, etc.]

**Additional context**
https://stackoverflow.com/questions/20672490/how-to-know-whether-modal-boxes-alert-prompt-confirm-have-been-disabled-i

**Comment by erezrokah** [comment]
Hey @michi-zuri I wasn't able to reproduce this with Chrome/Brave/Safari.
I was able to reproduce with Firefox and found this: https://superuser.com/questions/796842/disable-prevent-this-page-from-creating-additional-dialogs-for-certain-website

A possible solution is to switch to modals instead of alerts.

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
