### ISSUE TITLE
image widget - allow entering an external URL

### ISSUE THREAD

**Issue by johtso** [decaporg/decap-cms#2831]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to explicitly specify an external url in the image widget.

**Describe the solution you'd like**
Allow providing a URL string instead of uploading an image.

It seems that the widget behaves well if you edit the data directly to contain an external url, displaying the thumbnail. This may not be too difficult to implement?

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
