### ISSUE TITLE
Translating the Documentation

### ISSUE THREAD

**Issue by helrabelo** [decaporg/decap-cms#2882]
As a Brazilliam, I am aware that many people do not have fluent english, I'd like to help them out by volunteering for translating the docs content to portuguese.

Maybe we can have it translated to other languages as well?

**Comment by erezrokah** [comment]
This is a good idea. We should first discuss how to support multiple languages (probably look at other projects). For example `react` has a repo+domain per translation:
https://github.com/reactjs/reactjs.org
https://github.com/reactjs/ru.reactjs.org

https://en.reactjs.org/
https://ru.reactjs.org/

**Comment by erquhart** [comment]
We could do multiple packages in the website directory

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lancaluis** [comment]
Hey guys, some news about that? I'd like to help the community as well

**Comment by erezrokah** [comment]
Hi @iansinnott and thank you for suggesting to help.
We don't have a plan on how to do this (yet) so figuring a way to set up the translation process would be a good start.
We can have all the translations in the same repo or use separate repos like [React](https://github.com/netlify/netlify-cms/issues/2882#issuecomment-554722667).
Same for deployment, we could deploy everything under the same domain and have a dropdown for selecting the language or use a subdomain per language.
We would need to investigate the approach that makes sense for use first.

**Comment by martinjagodic** [comment]
Decap is maintained by a small team, and we don't have the capacity to manage translated documentation. Today we have great translation tools available, so I suggest users to use that.

We will keep accepting contributions for translation of the CMS.
