### ISSUE TITLE
TypeScript type definitions

### ISSUE THREAD

**Issue by yurist38** [decaporg/decap-cms#2926]
**Is your feature request related to a problem? Please describe.**
Surprisingly, I didn't find anything about TypeScript support in the issues list. So, I'd like to ask you where are you in terms of supporting TS?

**Describe the solution you'd like**
The best way is to provide TS definitions within NPM package(s).

**Describe alternatives you've considered**
Release TS definitions as a separate NPM package(s) (`@types/<NAME-OF-ORIGINAL-PACKAGE>`)

**Additional context**
I actually just written TS definitions for `netlify-cms-app` NPM package (origin is actually in `netlify-cms-core` If I'm not wrong). I'd like to open source my typings that other devs can use them. That's why I wanted to discuss with you what is the best way to do this? I can either open a PR for the current repo that you can release these types withing the packages mentioned above OR I can open a PR for [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) and get them released within separate packages. If you ask me, I'd prefer the first option. What do YOU think, guys? Thanks!

**Comment by erezrokah** [comment]
That's great @yurist38! I'm prefer with the first option too

**Comment by yurist38** [comment]
Thanks for the quick reply @erezrokah ! Great to hear this. Let me prepare the PR then.

**Comment by martinjagodic** [comment]
I consider this closed in above mentiones PRs, even if just partially.
