### ISSUE TITLE
Replace absolute URLs with relative ones

### ISSUE THREAD

**Issue by kylekirkby** [decaporg/decap-cms#2932]
**Is your feature request related to a problem? Please describe.**

We have two environments for our static sites staging.x.org and www.x.org. Users of NetlifyCMS sometimes have the tendency to add absolute URLs instead of relative ones e.g `https://www.linaro.org/news/` instead of `/news/`. This means the link will only work on one of the website environments. Also, it is good to be consistent with using either relative or absolute URLs.

**Describe the solution you'd like**

We would like to supply a list of hosts that the markdown/text/string widgets would strip from URLs before submitting a pull request.

```yaml
...
relative_url_hosts:
- https://www.linaro.org/
- https://linaro.org
- https://staging.linaro.org/
```

**Describe alternatives you've considered**
- Widget field validation (currently cannot find and replace though)
- Custom Widgets

Is this something that should be done with a custom widget or do you think this would be useful to other NetlifyCMS users?

Cheers!

Kyle

**Comment by tomrutgers** [comment]
You could use a pattern with the default string widget to check for absolute urls and use a hint to indicate that the user should use relative paths. https://www.netlifycms.org/docs/widgets/#common-widget-options

I would personally handle this on the front-end, since I've got all the tools available there to strip and replace markdown and strings. That way I wouldn't have to bother the editor with instructions on what to input.

**Comment by kylekirkby** [comment]
@tomrutgers, yes it would be good to not have them worry about what content they are adding and just have an option to replace absolute URLs with the relative equivalents! I'll add a RegEx to the string widgets, where possible, to start with!

**Comment by erquhart** [comment]
Internal linking is a whole thing we haven’t even discussed yet, but I do have notes on how it might work. Let’s keep this open unless an existing issue is found that covers it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by martinjagodic** [comment]
Closing as stale
