### ISSUE TITLE
Keyboard Shortcuts for the Slate Editor

### ISSUE THREAD

**Issue by kalebheitzman** [decaporg/decap-cms#3005]
It would nice to have keyboard shortcuts for the slate editor for making text bold, italic, adding links etc that match up to the windows/mac defaults in other editors.

command+b for bold
command+i for italic
command+k for adding a link

Maybe something like

command+shift+2 for an h2 and so forth.

**Comment by kalebheitzman** [comment]
@see https://medium.com/@brendanrc/making-keyboard-shortcuts-in-slatejs-simple-9bfa1a10ed7c

**Comment by erquhart** [comment]
Yeah that's a regression from the Slate overhaul, we used to have them.

**Comment by mediamaker** [comment]
this would be a huge usability and productivity improvement.
