### ISSUE TITLE
List items separated by new lines (in text field)

### ISSUE THREAD

**Issue by danielkellyio** [decaporg/decap-cms#3018]
**Is your feature request related to a problem? Please describe.**
Kind of. The list widget is awesome but after some nesting it get's a little insane. In order to clean up the interface a bit I think it'd be nice to have the option to separate list items via a new line in a text field. The comma separated doesn't really fit my needs as each item is long enough to merit it's own line but having a new field for every one makes it harder to copy and paste a list and just makes the visual nesting a little overwhelming.

**Describe the solution you'd like**
I would like to see and option something like this:
```
{ label: Test List, name: testList, widget: list, newLineSeperated:true }
```

**Describe alternatives you've considered**
Just using the `field` option is ok, just not ideal

**Additional context**
Thanks!

**Comment by erquhart** [comment]
So you're currently using a list widget with a bunch of string widgets as children, and want the UI to be less cluttered, is that accurate?

**Comment by danielkellyio** [comment]
that is correct

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
