### ISSUE TITLE
Nested lists in markdown widget tab/untab inconsistently

### ISSUE THREAD

**Issue by erquhart** [decaporg/decap-cms#3045]
**Describe the bug**

Tabbing and untabbing a nested list item causes unexpected indentation of its siblings

**To Reproduce**

1. Create a list item with a nested list inside
2. Set the cursor on a list item in the nested list
3. Press <kbd>Shift</kbd>+<kbd>Tab</kbd>
4. The list item is unindented to be sibling to the parent list item, while its original siblings remain in place
5. Press <kbd>Shift</kbd>
6. The list item is indented back to its original place as expected, but the original siblings are indented further so they remain children of the indented list item

**Expected behavior**

A list item with a nested list should only indent its child list on tab if the child list is selected, otherwise only the list item itself should be indented.

**Screenshots**

![nested-list-tab](https://user-images.githubusercontent.com/2112202/71919082-ca0a3500-3151-11ea-855e-d9f9df36d54e.gif)

**Applicable Versions:**

 - Netlify CMS version: 2.10.2

**Comment by kaganjd** [comment]
Adding a related report from Community: https://community.netlify.com/t/ordered-and-unordered-lists-in-netlifycms-ui-editor/16655

Video repro here: https://www.youtube.com/embed/xkNbq9c4e3w

**Comment by homerhanumat** [comment]
Any progress on this issue?  Non-technical colleagues would find the list widgets useful.

**Comment by martinjagodic** [comment]
Solved in Decap 3
