### ISSUE TITLE
Discussion: Netlify CMS Office Hours

### ISSUE THREAD

**Issue by erezrokah** [decaporg/decap-cms#3203]
In order to increase engagement with the community we would like to discuss the possibility of having office hours every week/two weeks.

### Purpose
Provide people with an opportunity to ask questions, provide feedback and contribute to the protect.

### Mechanism
Zoom?

### Agenda Proposals
- Collect questions before hand, answer the most upvoted ones.
- Demos of community projects/new features.
- Acknowledge contributors. 

### Code Of Conduct
- Be nice to everyone :)
- Always open to new people.
- A single person should not take control of the conversation.

### Technicalities
- Share recordings and notes.

### Not a
- Support channel - we can use issues for that so due to meetings time restrictions and better long term documentation.

Thoughts? Ideas?

**Comment by brianzelip** [comment]
I think it's a great idea.

**Comment by apolopena** [comment]
Yes a great idea!

**Comment by austincondiff** [comment]
So, when is this party going to start!? 🎉

**Comment by erezrokah** [comment]
I'll schedule something this week.

**Comment by erezrokah** [comment]
Does next Monday (April 13) at 5PM UTC work?

**Comment by austincondiff** [comment]
Works for me. What are we using? Zoom, Slack?

**Comment by erezrokah** [comment]
I’ll post a zoom link on the slack on Monday and link from here to avoid zoom bombing.

**Comment by erezrokah** [comment]
> Does next Monday (April 13) at 5PM UTC work?

Let's push for 5:30PM UTC if that's ok.

**Comment by apolopena** [comment]
Works for me 4/13/20 @ 5:30PM UTC

**Comment by erezrokah** [comment]
This is the google calendar event (still without the zoom link):
https://calendar.google.com/event?action=TEMPLATE&tmeid=NHFoNGU4NXUxamduNnM1YmZpNWswa3ZpaWkgZXJlekBuZXRsaWZ5LmNvbQ&tmsrc=erez%40netlify.com

**Comment by erezrokah** [comment]
Google Calendar event: https://calendar.google.com/event?action=TEMPLATE&tmeid=M2czbGJzczV2ZThxbzJoZjU4aWVtZm1xZDEgbmV0bGlmeS5jb21fODlnMGlnaGZjNTRmN2RoNXA0ZnFtdG10NDRAZw&tmsrc=netlify.com_89g0ighfc54f7dh5p4fqmtmt44%40group.calendar.google.com

**Comment by erezrokah** [comment]
Zoom link available here https://netlifycms.slack.com/archives/CPMJH823F/p1586798252119400

**Comment by erezrokah** [comment]
Notes and recording: https://drive.google.com/drive/folders/13hdsi1GBgtHaTlndEJr3YwFdLHmnzD9u

**Comment by paultannenbaum** [comment]
Is this still going on or did you guys wrap up? FYI, I can not see the zoom link @erezrokah posted because of not having access to the slack channel

**Comment by erezrokah** [comment]
Hi @paultannenbaum, the meeting was from 5:30 PM UTC to 6:00 PM UTC. You can join the slack here https://www.netlifycms.org/chat.
I don't want to post the link publicly here as to avoid [zoom bombing](https://en.wikipedia.org/wiki/Zoombombing).

**Comment by jeremyzilar** [comment]
I'd be open to joining one of these

**Comment by Pearce-Ropion** [comment]
@erezrokah Is the slack still publicly available? All the links around the site lead to a slack page that says the link is currently not active.
![screencapture-netlifycms-slack-join-shared-invite-enQtODE1NTcxODA5Mjg1LTRjYWExM2MyZDJmODA3YmVkMjI2YmQwZDg2ZDUyYTMyM2Y3Zjc1ZTJhNDBkYmMwNjA2ZTkwODY4YjZjNGNlNTE-2020-11-05-17_19_28](https://user-images.githubusercontent.com/32177944/98314572-1b11d200-1f8b-11eb-9aac-7eb1b1298ceb.png)

**Comment by erezrokah** [comment]
Thanks for raising this @Pearce-Ropion, let me check if anything changed there

**Comment by naton** [comment]
Any scheduled meeting coming up soonish..?

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
