### ISSUE TITLE
Optional slug field - generating deploy preview links

### ISSUE THREAD

**Issue by zslabs** [decaporg/decap-cms#3226]
**Is your feature request related to a problem? Please describe.**
Somewhat related to [this PR](https://github.com/netlify/netlify-cms/issues/3084)

**Describe the solution you'd like**

We have blog posts that also have a custom `slug` field that can be filled out when desired to produce something different. Otherwise, it falls back to the `title`. 

When the `slug` field is required, I can do `preview_path: '/blog/{{fields.slug}}'` but since it's optional, I'm unsure if there's a way to create a fallback.

Example:

```
---
title: My post
slug: my-custom-slug
---

Post content
```

Should generate `/blog/my-custom-slug`

```
---
title: My post
---

Post content
```

Should generate `/blog/my-post`

**Comment by zslabs** [comment]
If I can provide anymore clarification, please let me know. If this is isn't possible right now - that's totally fine as well; just wanted to make sure I'm not missing anything. If someone knows of the file where this is done; I can also look into adding this functionality.

**Comment by erezrokah** [comment]
This is a good place to start:
https://github.com/netlify/netlify-cms/blob/8d67de0e681e02ddbf811eecc5e4744b324b7e61/packages/netlify-cms-core/src/lib/formatters.ts#L102

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
