### ISSUE TITLE
redirect_uri doesn't contain the query part of the CMS URL (implicit auth with gitlab)

### ISSUE THREAD

**Issue by czinkos** [decaporg/decap-cms#3254]
**Describe the bug**
Cannot use CMS at URL with query parameters. I'd like to use a query param to refer to different config.yml files:

  http://example.com/cms/v1/index.html?config=http://example.com/path/to/config.yml

After I login to gitlab it redirects back to:

  http://example.com/cms/v1/index.html

Result is: config.yml not found.

redirect_uri param in the auth request does not contain the query part of the URL.

**Expected behavior**
Should be redirected back to the original URL with query parameters. It would be useful to use one CMS application with many configs.

**Applicable Versions:**
 - Netlify CMS version: "netlify-cms-app": "2.11.18"
 - Git provider: GitLab

Thank you.

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
