### ISSUE TITLE
Bold + Italics creates bad Markdown

### ISSUE THREAD

**Issue by carlmjohnson** [decaporg/decap-cms#3291]
**Describe the bug**

My writers often want bold+italics, like

> _**[Spotlight PA](https://www.spotlightpa.org/)** is an independent, nonpartisan newsroom powered by The Philadelphia Inquirer in partnership with the Pittsburgh Post-Gazette and PennLive/Patriot-News. [Sign up for our free weekly newsletter.](https://www.spotlightpa.org/newsletters/)_

However, the Markdown editor creates this as 

    ***[Spotlight PA](https://www.spotlightpa.org/)** is an independent, nonpartisan 
    newsroom powered by The Philadelphia Inquirer in partnership with the Pittsburgh 
    Post-Gazette and PennLive/Patriot-News.
    [Sign up for our free weekly newsletter.](https://www.spotlightpa.org/newsletters/)*

and our site (Hugo+Goldmark) gets confused by the three stars in a row and borks the output.

**To Reproduce**

Create bold+italic text in Markdown editor.

**Expected behavior**

If it output `_**bold** and italic_` (_**bold** and italic_), I believe it is less likely that a Markdown engine would get confused by it.

**Applicable Versions:**
 - Netlify CMS version: 2.10.23

**CMS configuration**
```
...
  - label: Body
    name: body
    widget: markdown
```

**Comment by martinjagodic** [comment]
Closing as stale
