### ISSUE TITLE
Custom editor components don't work when in a particular order

### ISSUE THREAD

**Issue by danielkellyio** [decaporg/decap-cms#3328]
**Describe the bug**
I have created 2 custom editor components as follows with patterns as follows:
`\[~box (.*?) ~\]`
`\[~youtube (.*?) ~\]`

Then using the editor components I'm able to produce the following markup:

```
[~youtube {"url":"https://www.youtube.com/watch?v=xxxxx"} ~]

[~box {"content":"Hello"} ~]

[~youtube {"url":"https://www.youtube.com/watch?v=xxxxx"} ~]
```

The strange thing is that the 2 youtube shortcodes work just fine in this setup but the box doesn't. Or if I remove the last youtube shortcode, the box and the remaining youtube shortcode work fine. I was able to use javascript debug to figure out that the box shortcode get's tokenized as a paragraph but I don't know why.

**To Reproduce**

**Expected behavior**
Both shortcodes to work consistently no matter the order or frequency

**Screenshots**
Box not working:
<img width="1326" alt="Screen Shot 2020-02-25 at 9 33 34 PM" src="https://user-images.githubusercontent.com/7635209/75309517-ea33a780-5816-11ea-9df4-833b186026ef.png">
Box working:
<img width="1298" alt="Screen Shot 2020-02-25 at 9 33 52 PM" src="https://user-images.githubusercontent.com/7635209/75309528-f0c21f00-5816-11ea-9fa5-66620c1e4b94.png">

**Applicable Versions:**
 - Netlify CMS version: netlify-cms-app 2.11.23, netlify-cms-core 2.19.0, netlify-cms 2.10.26
 - Git provider: GitHub
 - OS: Mac 10.14.6
 - Browser version Chrome 80.0.3987.116

**CMS configuration**
probably not necessary for this issue. Let me know if I should provide. Thanks!

**Additional context**
Understandable if this is probably a fault with my pattern, but I can't for the life of me figure out why and just want to make sure it is just me and not something about the cms code. Thanks!

**Comment by erquhart** [comment]
I haven’t figured out a great way to validate for this, but patterns have to begin with a start string anchor (`^`). See if that fixes it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by danielkellyio** [comment]
I have tried starting the pattern with `^` to no avail. Also I’d really like for the short codes to be able to be used inline inside other short codes which I can’t do starting them that way. For instance I also have a button short code that I can use inside the box like this: 
```
[~box {"content":"I am a box with a button \n\n[\~button {\"label\":\"And now click me\",\"link\":\"https://google.com\",\"classes\":\"is-primary\"} \~button]"} ~box]
```
( inside my toPreview code I’m unescaping the nested short code and rendering it). 

It works sometimes in the editor and all the time on my front end but hangs up in the editor when in a certain order as above. 

I’ll post my code here shortly that handles the short codes (on my phone right now). 

Thanks!

**Comment by danielkellyio** [comment]
Here's an example of what I'm trying to do: https://github.com/danielkellyio/shortcode-issue-demo

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
