### ISSUE TITLE
Update Netlify CMS from within the app

### ISSUE THREAD

**Issue by austincondiff** [decaporg/decap-cms#3353]
It wouldn't seem too terribly difficult to update the `netlify-cms` version in the project's `package.json` and then trigger a deploy. Then we would watch for the completion of that deploy and refresh the page. 

If there is a build error for whatever reason we could alert the user and give them the option to roll back and handle the update manually.

When the user loads up the app, we could send a request to check for updated versions. If one exists we unobtrusively notify the user that an update is available and display a button they can click to start the update process.

**Comment by erezrokah** [comment]
`package.json` changes shouldn't be an issue, lock files (e.g. `yarn.lock`) will be difficult to handle. In order to have reproducible builds one needs to use a lock file. Some build systems are set up in a way that when the `package.json` doesn't match the lock file the build fails.

**Comment by austincondiff** [comment]
Maybe a subsequent push or the update command could be done via Netlify?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by martinjagodic** [comment]
We don't want to hand user too much power, and updating dependencies is potentially dangerous. I am closing as not planned.
