### ISSUE TITLE
Some console errors not visible for browsers with dark mode

### ISSUE THREAD

**Issue by erquhart** [decaporg/decap-cms#3431]
**Describe the bug**

<img width="698" alt="Screen Shot 2020-03-16 at 12 36 50 PM" src="https://user-images.githubusercontent.com/2112202/76780183-f5795380-6782-11ea-8f37-e0caf037455c.png">

**Expected behavior**

Custom console log styling should take both light and dark backgrounds into consideration.

**Comment by martinjagodic** [comment]
Closing as stale
