### ISSUE TITLE
Slow initial page load of editorial workflow page with many draft articles

### ISSUE THREAD

**Issue by hpenton** [decaporg/decap-cms#3468]
**Describe the bug**
The first time I load the CMS and try to access an article or the editorial workflow page, it takes around ~30 seconds to load the page. Subsequent article load times are acceptable.

**To Reproduce**
1. Create somewhere in the region of 80 draft articles (I believe I have 83)
2. Reload the contents page of the CMS
3. Attempt to load an article.
4. Observe slow load time.

**Expected behavior**
The page loads somewhere in the same region as subsequent page loads.

**Applicable Versions:**

 - gatsby-plugin-netlify-cms: 4.1.2
 - netlify-cms-app: 2.11.29

 - Node.JS version:
12.16.1

**Additional context**
The netlify-cms-app is being used to customise a preview template and editor component

**Comment by martinjagodic** [comment]
Closing as stale
