### ISSUE TITLE
Google identity works through invite link but not after accessing site/admin

### ISSUE THREAD

**Issue by dougajmcdonald** [decaporg/decap-cms#3477]
**Describe the bug**
When using the google provider in netlify identity (with the netlify identify widget) the setup in the netlify UI seems fine. But when I invite users (with a google account), they receive the email click `accept the invite` and in the widget can click, continue with google, they are logged in and can use netlify cms as expected.

However, if the same user (me) tries to access `<site>/admin` I cannot login with my google account

**To Reproduce**
 Pre-reqs: 
- Add a site to netlify with netlify-cms
- enable identify
- add google as a provider
- invite a user with a google account
- the user receives the email and clicks the accept invite link
- the user clicks `continue with google` (and is logged in successfully)

1. The user later accesses `<site>/admin`

2. I get the login prompt as expected:

![image](https://user-images.githubusercontent.com/1190042/77581911-739dce80-6ed6-11ea-95cd-985cea9a76d2.png)

3. Clicking login with netlify displays the prompt, with an option to `continue with google`

![image](https://user-images.githubusercontent.com/1190042/77582032-9d56f580-6ed6-11ea-9d4d-ce67fde0bce6.png)

4. If I click, continue with google, I am presented with an option to select and account. If I select my already logged in account (I have several) I am redirected back to the `login with netlify` prompt and not logged in.

**Expected behaviour**
If I accept the invite > continue with google (not setting a password) > when I try to login again and select `continue with google` I expect to be able to login without providing a password if my google account is logged in.

**Additional context**
Oddly, if when I accept the invite, I **set a password instead of selecting continue with google.** 

When I hit <site>/admin and select login with netlify, then type in my google email with the password I set manually, it logs in fine.

**Applicable Versions:**
netlify-cms-app 2.11.27
netlify-cms-core 2.21.0
Windows: 10
Chrome: Version 80.0.3987.149 (Official Build) (64-bit)

**CMS configuration**
Don't think it's relevant here, omitted for brevity

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
