### ISSUE TITLE
Markdown Editor, RichText on, remove an added component?

### ISSUE THREAD

**Issue by apolopena** [decaporg/decap-cms#3531]
Hopefully this makes sense: Is there anyway to remove a component added to the markdown editor via the 'add component' button without changing the state of the editor back to "markdown" mode and then manually removing the string that was created by adding the component in the first place?

I have a feeling the answer is 'no' but I thought I would ask just in case.

**Comment by apolopena** [comment]
There was a glitch with github and it made me post this issue twice. Thanks.

**Comment by erquhart** [comment]
It isn’t obvious, but if you select the component itself (clicking the label is a good way), you can press backspace to delete it.

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
