### ISSUE TITLE
Markdown is not shown in WYSIWYG when creating duplicate

### ISSUE THREAD

**Issue by jannis701** [decaporg/decap-cms#3545]
**Describe the bug**
If you create a duplicate of a published entry all data from the entry will be taken to a new form. However, the markdown-WYSIWYG field is empty. You have to switch to markdown-source and back to WYSIWYG to see the content.

**To Reproduce**
1. config test-repo as backend and define at least 1 collection that uses a markdown-field and use the default publish_mode 
2. Log in and navigate to create (publish) a new entry in the collection with content in the markdown-field using the WYSIWYG-view of the editor
3. Select "create duplicate" in the publish-menu

the markdown-field seems to be empty (unless you switch to source-view and back)

**Expected behavior**
the markdown-field should immediately show the copied content

**Applicable Versions:**
netlify-cms-app 2.12.3
netlify-cms-core 2.23.3
netlify-cms 2.10.39
 - Git provider: gitlab or test-repo
 - OS: ubuntu
 - Browser version firefox 74.0

**Comment by barthc** [comment]
This issue is fixed in PR #3366
