### ISSUE TITLE
What are some examples of the CMS being used?

### ISSUE THREAD

**Issue by bdougie** [decaporg/decap-cms#365]
# What is this?

Looking for examples/blog posts of this CMS being used with different Static Site Generators. I am looking to add a section to the docs for new and existing users can reference. 

# What we are looking for:
The most common use case I have seen is the CMS being used for a blog, but I am looking use cases outside this scope.

- marketing pages
- company sites
- client pages like restaurants or small business
- anything else

Please provide your examples in the comments for now and I will start.

PR pending: #366

**Comment by erquhart** [comment]
We should consider putting a CTA on the cms website inviting devs to add their project here. Perhaps in the readme, too.

**Comment by bdougie** [comment]
Yeah - that is a great idea, I will loop Eli once we have two or more examples.

**Comment by erquhart** [comment]
We can add Smashing right away, too.

**Comment by erquhart** [comment]
Thanks for this @maciejmatu! I think the intention for a CTA inviting devs to add their site more applied to the examples page itself. Maybe if we had a more well groomed "showcase" it'd be worth putting on the front page. Those are just my thoughts, though. Anyone else? @verythorough?

**Comment by verythorough** [comment]
Agreed. I think that CTA looks great, but makes more sense on the examples page for now.

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
