### ISSUE TITLE
Image Filenames are Transformed into all lower-case

### ISSUE THREAD

**Issue by acarnwath** [decaporg/decap-cms#4288]
Although I agree with the issue raised here: https://github.com/netlify/netlify-cms/pull/853 that the _comparison_ of names should be case-insensitive, our team has a situation where we migrated a site over and have assets that have capitalized names (e.g. Organizational_Pledge.pdf); these files exist and function fine in our site. However, when we try to update them (replacing in place) using the NetlifyCMS Media interface, it does so, but it also transforms the filenames into all lower case (e.g. organizational_pledge.pdf).  This breaks a lot of links coming from outside of the website (ads, external sites, etc.), so we have to manually update it in Git, which obviously is not ideal.

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
