### ISSUE TITLE
Do I need a Custom Widget or is there another Solution? 

### ISSUE THREAD

**Issue by headapples** [decaporg/decap-cms#4296]
I'm trying to create responsive image markup in one click straight from the Netlify CMS UI for a non-technical editor. 
 
 As any HTML is also valid markdown I feel like a custom Widget would do the job nicely. I simply want something that outputs the actual HTML markup but using an image file chosen from the Media gallery as the source. The HTML will also have netlify image transform query parameters (I'm using Netlify Large media) appended to each image src and srcset, but these will be the same for each image chosen. 

 I'm also using 11ty for this project and have also explained the different approaches I have tried here: 
     https://github.com/11ty/eleventy/issues/1414  
(However, I do feel that this could just as easily be a Netlify CMS solution so any guidance would be greatly appreciated).

**Comment by erezrokah** [comment]
Hi @headapples, if you just need to use it in the markdown editor a custom editor component might do the trick:
https://www.netlifycms.org/docs/custom-widgets/#registereditorcomponent
https://github.com/netlify/netlify-cms/blob/8ad007a1fa5fb766491c4b26b3b951c7d63de7aa/packages/netlify-cms-editor-component-image/src/index.js

**Comment by headapples** [comment]
@erezrokah Thanks so much for taking the time to actually think about this and reply. I really appreciate it. I'll have a play around with the custom component direction. That second reference you supplied looks especially useful as I hadn't read that yet.

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
