### ISSUE TITLE
Signing into netlifyCMS brings me to "Not Found"

### ISSUE THREAD

**Issue by AJTJ** [decaporg/decap-cms#4318]
**Describe the bug**
As the title suggests, once I sign into my netlifyCMS through netlify/git-gateway it brings me to the "Not Found" as seen in this screenshot:

![Screen Shot 2020-09-13 at 8 28 12 PM](https://user-images.githubusercontent.com/29932896/93130074-fe9a9d00-f69f-11ea-9ca7-581b0eb3bc43.png)

If I refresh or click `content` or `media` it brings me somewhere useful, but how do I change this so that it goes directly to `content`?

**Update:**
As far as I know this error only exists while using `git-gateway` and not while using the proxy server.

**Applicable Versions:**

 - Netlify CMS version: "netlify-cms-app": "^2.12.20",
 - Git provider: github
 - OS: macOS 10.14
 - Browser version evergreen chrome

 - Node.JS version:
10.15 (locally)

**CMS configuration**
config.js here: https://github.com/Yukon-Literacy-Coalition/ylc_website_v2/blob/master/src/CMS/config.js
repo here: https://github.com/Yukon-Literacy-Coalition/ylc_website_v2

**Comment by jankohlbach** [comment]
is this a cors problem? for me any requests that go to /.netlify/git/gitlab/repository/files the cors is failing and I don't know why

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
