### ISSUE TITLE
Preview Templates are flickering on update

### ISSUE THREAD

**Issue by AJTJ** [decaporg/decap-cms#4324]
**Describe the bug**
So, it seems like my preview components in the CMS are flickering, i.e. reloading the images and custom fonts _every time_ I update the component with new copy in the CMS. This ONLY seems to happen when my site is hosted online at https://amazing-almeida-cc9291.netlify.app/ it does NOT come up when I run it locally in the build environment or when I build and serve it locally. Thus, this is rather hard to debug. If it happened everywhere I would imagine it to be a React component issue (wherein the entire component is being updated every time)

I think this video captures the issue better than words: https://streamable.com/z7ncqq

**To Reproduce**
The repository can be viewed here: https://github.com/Yukon-Literacy-Coalition/ylc_website_v2

To reproduce you would need to have access to the CMS at https://amazing-almeida-cc9291.netlify.app/ 

**Expected behavior**
I imagine it should not be flickering. I'm not sure why this reloading behaviour is _only_ happening when the site is hosted online.

**Applicable Versions:**
Netlify CMS version: "netlify-cms-app": "^2.12.20",
Git provider: github
OS: macOS 10.14
Browser version evergreen chrome
Node.JS version:
10.15 (locally)

**CMS configuration**
https://github.com/Yukon-Literacy-Coalition/ylc_website_v2/blob/master/src/CMS/config.js

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
