### ISSUE TITLE
Object field "collapsed" not working

### ISSUE THREAD

**Issue by paultannenbaum** [decaporg/decap-cms#4355]
**Describe the bug**
We are using netlify cms in conjuction with Gatsby via the `gatsby-plugin-netlify-cms`. I have tried several variations of using the [Object Widget](https://www.netlifycms.org/docs/widgets/#object)'s property `collapsed` throughout our app and am not seeing any kind of behavior change. For reference I have tried using the List Widget's `collapsed` property, and am seeing that work as expected.

**To Reproduce**
1. In your template configuration, create an `Object` widget with the configuration `collapsed: true`
2. Navigate to CMS backend

**Expected behavior**
I expect to see the Object's fields collapsed instead of expanded.

**Applicable Versions:**
`netlify-cms-app 2.12.3`
`netlify-cms-core 2.23.3`
 - Git provider: Github
 - OS: MacOS 10.14
 - Tested in all browsers
 - Node.JS version: 11.15

**CMS configuration**
We are using a JS configuration via the gatsby integration. This is what a sample widgte looks like:

```
export default {
  label: 'Hero',
  name: 'hero',
  widget: 'object',
  collapsed: true,
  fields: [
    {
      label: 'Heading',
      name: 'heading',
      widget: 'string',
      collapsed: true,
    },
    {
      label: 'Heading Width',
      name: 'headingMaxWidth',
      widget: 'number',
      default: 400,
      min: 200,
      max: 540,
    },
    {
      label: 'Subheading',
      name: 'subheading',
      widget: 'string',
      required: false,
    },
    {
      label: 'Subheading Width',
      name: 'subheadingMaxWidth',
      widget: 'number',
      default: 400,
      min: 200,
      max: 540,
    },
    {
      label: 'Button Text',
      name: 'buttonText',
      widget: 'string',
    },
    {
      label: 'Button Link',
      name: 'buttonUrl',
      widget: 'string',
      required: false,
    },
    {
      label: 'Image',
      name: 'image',
      widget: 'image',
    },
    {
      label: 'Thumbnail',
      name: 'thumbnail',
      widget: 'image',
      required: false,
    },
  ],
}
```

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
