### ISSUE TITLE
Default value on file collection string field fails

### ISSUE THREAD

**Issue by mikestopcontinues** [decaporg/decap-cms#4363]
**Describe the bug**

I have a string field with a default value on a file in a file collection that doesn't get populated, while an identical config works in a folder collection.

**To Reproduce**
```js
{
collections: [{
  name: 'main',
  label: 'Main Pages',
  singular_label: 'Page',
  preview_path: '{{fields.slug}}',
  format: 'yaml-frontmatter',
  editor: {preview: false},
  create: false,
  delete: false,
  files: [{
    label: 'Home',
    name: 'home',
    file: `content/page/home.md`,
    fields: [
      {label: 'Title', name: 'title', widget: 'string', default: 'Home'},
    ],
  }],
}]
}
```

**Expected behavior**

I expect the default value to apply.

**Applicable Versions:**

Most recent everything.

**Additional context**

I'm manually initializing, and doing my config in JS.

**Comment by tomrutgers** [comment]
A bit of background as to why this isn't working: The default value of a widget is only set upon creation and as a file in a file collection isn't created through the CMS, the default value can't be set. Default values only work with folder collections.

**Comment by mikestopcontinues** [comment]
Maybe a good solution is to have the CMS create the files in a file collection? It's a bit of a pain that it doesn't anyway.

**Comment by martinjagodic** [comment]
File collection not creating files is intentional. Closing as not planned.
