### ISSUE TITLE
API_ERROR: tree.path contains a malformed path component

### ISSUE THREAD

**Issue by nolafs** [decaporg/decap-cms#4365]
Hi,

I am having issue with online version of the CMS. My collection works prefectly fine in my local development enviroment but once online, the cms is throwing an error when saving a new item to the collection

**Failed to persist entry: API_ERROR: tree.path contains a malformed path componen**t

```
- name: "clinicians"
    label: "Clinicians"
    label_singular: 'Clinician'
    create: true
    show_preview_links: true
    folder: "site/content/find-a-clinician"
    media_folder: ''
    public_folder: ''
    path: '{{slug}}/index'
    identifier_field: title
```

I need the following folder structure:

- find-a-clinician
   - slug
        - index.md

**Expected behavior**
Local and online version of the cms behaving differently.

**Applicable Versions:**

 - Netlify CMS version: ^2.10.57
 - Git provider: GitHub
 - OS: MacOS

**Comment by erezrokah** [comment]
Hi @nolafs do you mind sharing the entire `config.yml` or at least the fields configuration for that collection?

**Comment by nolafs** [comment]
It seems to be fixed. I believe netlify build had an old version cached of the CMS. After I cleared and double checked the version number in packages.json, the error went away. Thanks for looking into it.

**Comment by erezrokah** [comment]
Thanks for following up!

**Comment by erezrokah** [comment]
@nolafs can you follow up on my comment since you re-opened the issue? Also please share the CMS versions as shown in the browser console logs

**Comment by DrewNull** [comment]
I was getting this same error in my own project. It was due to a mistake in the `slug` pattern in one of my collections defined in config.yml. Instead of `slug: {{title}}/index`, I had accidentally written `slug: {{name}}/index`. There was no `name` frontmatter field defined, so it was failing with the above error code whenever I tried to create a new item of that collection from the CMS.

**Comment by nolafs** [comment]
Yeah, I started new project and the issue has returned. This time, refreshing the cache only is not working at all. 

```
- name: "procedures"
  label: "Procedures"
  folder: "content/procedures"
  slug: "{{proceduresCategories}}/{{slug}}"
  path: "{{speciality}}/{{proceduresCategories}}/{{slug}}"
  media_folder: '/src/assets/uploads'
  public_folder: 'assets/uploads'
  view_groups:
  - label: Speciality
    field: speciality
  - label: Procedures Category
    field: proceduresCategories
  editor:
    preview: false
  create: true
  fields:
  - { label: "Layout", name: "layout", widget: "hidden", default: "procedures" }
  - { label: "Title", name: "title", widget: "string" }
  - widget: string
    name: slug
    label: Slug
    required: true
    pattern: [ '^[a-z0-9]+(?:-[a-z0-9]+)*$','A slug can have no spaces or special characters' ]
  - { label: "Publish Date", name: "publishDate", widget: "datetime" }
  - { label: "Published", name: "published", widget: "boolean", default: true }
  - { label: "Body", name: "body", widget: "markdown" }
  - { label: "Speciality",
      name: "speciality",
      widget: "relation",
      multiple: false,
      required: false,
      collection: "speciality",
      search_fields: [ "slug" ],
      value_field: "slug",
      display_fields: [ "title" ] }
  - { label: "Procedures Category",
      name: "proceduresCategories",
      widget: "relation",
      multiple: false,
      required: false,
      collection: "speciality",
      search_fields: ["proceduresCategories.*"],
      value_field: "proceduresCategories.*.slug",
      display_fields: [ "proceduresCategories.*.title" ] }
```

**Comment by erezrokah** [comment]
A good way to debug this issue is to open the browser console and look at the network tab.
It should have the request that fails, and in the payload we should be able to see the malformed path.

**Comment by nolafs** [comment]
The path seems too look correct to me.

:path: /.netlify/git/github/git/trees/master:content%2Fprocedures%2Fspine%2F%2Fcomplex

**Comment by erezrokah** [comment]
Hi @nolafs, you should examine the POST data of the request. There should be a tree object with the file path structure

**Comment by nolafs** [comment]
Good spot, I must make them required but this does not seem to be the issue. I already checked that.

**Comment by nolafs** [comment]
I believe I is this part 

```
  slug: "{{proceduresCategories}}/{{slug}}"
  path: "{{speciality}}/{{proceduresCategories}}/{{slug}}"
```

In order to have the following folder structure:

- speciality -|
     - proceduresCategories -|
                 - slug
                
I had to add proceduresCategories to the slug or it just places it outside of the folder or I can see them in netlify cms backend.

**Comment by nolafs** [comment]
Ok, I believe there is an issue with using relation widget of proceduresCategories. It has to select the category from a list. The strange behaviour through as if you use the same field in slug, it works but the path does not pick it up.

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
