### ISSUE TITLE
Is it Possible to Save To Local Repo Instead of Remote ?

### ISSUE THREAD

**Issue by goldcoders** [decaporg/decap-cms#4429]
The Way Netlify CMS work on live site, is it make push to the remote repo...
Its Ok but If The Build Time of the Repository is 1 min... Its Kinda Slow 
To Deploy Site and See changes and wait for 1 min...

I have another built a wrapper on hugo site using netlify-cms and netlify-cms-proxy...
Which allows you to use cms easily updating locally...

Its cool, but I needed it to make a git commit every save to the local repo instead of not doing anything at all..

Is there a way to highjack that with netlify-cms-proxy 
I would like to   Save to A Local Git Repo...
when saving a Collection or file
Instead of doing nothing...

But then Add an extra Button Of Livesync or do a git push

I wanna utilize as much as possible little or to none a third party integration of doing it , or by creating another wrapper like 
electron or tauri on top of this just to be able to make native command calls to git and netlify....

Any help would be appreciated thanks

**Comment by erezrokah** [comment]
Hi @goldcoders, you can run the local proxy server in `git` mode:
https://github.com/netlify/netlify-cms/blob/277a1519bed31145910a67e22e0f51c46e8e2006/packages/netlify-cms-proxy-server/src/index.ts#L21

`MODE=git npx netlify-cms-proxy-server`

It's still very experimental (and needs a repo with no pending changes), but it will generate a local commit on each save.

Another options is to set up a separate watchman on the repo files, and act on that.

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
