### ISSUE TITLE
Diff links in the CHANGELOG.md are broken

### ISSUE THREAD

**Issue by bradvogel** [decaporg/decap-cms#4484]
The links in https://github.com/netlify/netlify-cms/blob/a90795ed9a98d90ac8d3ca3cd02e0785894b3d08/packages/netlify-cms-app/CHANGELOG.md to view the comparison between versions are broken:
![image](https://user-images.githubusercontent.com/821706/96589247-93ea0c00-12b2-11eb-840a-a71732679ce4.png)
![image](https://user-images.githubusercontent.com/821706/96589264-977d9300-12b2-11eb-8ae2-7e252d5ce2df.png)

**Comment by erezrokah** [comment]
Related to https://github.com/lerna/lerna/issues/1538

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
