### ISSUE TITLE
Pasting from Google Docs clears formatting

### ISSUE THREAD

**Issue by inwardmovement** [decaporg/decap-cms#4488]
Pasting content from Google Docs clears formatting, for example using [cms-demo.netlify.com](https://cms-demo.netlify.com/):

Rich text copied from GDoc:
> **This is bold** and _this is italic_.

When pasted into NetlifyCMS in rich text editor becomes:
> This is bold and this is italic.

See https://github.com/netlify/netlify-cms/issues/991

**Comment by inwardmovement** [comment]
While waiting for a fix, one can workaround this via the [Paste as Markdown](https://chrome.google.com/webstore/detail/paste-as-markdown/lmelpnmpkekjahgdihfajfebaddffokl) Chrome extension: just "paste as Markdown" in the Markdown field of the editor after copying from GDocs, and the Rich Text field is then populated accordingly to GDocs.

**Comment by martinjagodic** [comment]
Closing as stale
