### ISSUE TITLE
Placeholder support for fields

### ISSUE THREAD

**Issue by bdot** [decaporg/decap-cms#450]
**- Do you want to request a *feature* or report a *bug*?**

This is a feature request

**- What is the current behavior?**
Currently placeholders are not supported at field level. That is we can have a slug something like below at collection level but it doesn't work if used at field level.
```
slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
```

**- What is the expected behavior?**
For example having a Field definition:
```
- {label: "Slug", name: "slug", widget: "hidden", default: "{{slug}}"}
```

Should produce an entry in the actual document body 
Expected outcome in the body for an article titled "Netlify CMS is awesome" should be 
```
slug: netlify-cms-is-awesome
```

**Comment by erquhart** [comment]
The slug placeholder is very specific to slugs - maybe we should consider just putting slugs in the frontmatter? Not certain if that would negatively affect various build tools.

The ability to edit slugs is covered under #445.

**Comment by dardub** [comment]
In Gatsby it's very common pattern to use the slug in the frontmatter. Right now I think we have to create the slug independently to use in Gatsby.

So adding the slug to frontmatter in some way would help Gatsby integration at the very least.

**Comment by anarchivist** [comment]
Slugs in frontmatter is also common for Jekyll; see https://jekyllrb.com/docs/permalinks/#template-variables for more details.

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
