### ISSUE TITLE
Netlify CMS stuck in "Loading entry"

### ISSUE THREAD

**Issue by sandoche** [decaporg/decap-cms#4517]
I have a JSON file with an array containing about 440 items.
When I open this file in the content manager it stays stuck in `Loading entry` with the loading animation and my browser CPU usage goes up to 25% and the memory goes around 1GB on Brave or 2GB on firefox.

I tried with an array containing 30 items and it worked perfectly.

**Applicable Versions:**
* netlify-cms-app 2.13.1
* netlify-cms-core 2.33.1
* netlify-cms 2.10.66
* Git provider: GitHub
* OS: Windows 10

I tried in brave browser (chromium) and Firefox

**CMS configuration**
The configuration is here: https://github.com/sandoche/CuratedStack-nocode-template/blob/main/static/admin/config.yml
The content file is here: https://github.com/sandoche/CuratedStack-nocode-template/blob/main/content/links.json (this one works because it has around 30 items in the array of `links`, you could duplicate the items to get +400 items to reproduce the error.

**Comment by sandoche** [comment]
Actually it finally finished loading on Firefox after more than 10 minutes. I didn't make it work on chrome it seemed to crash before.
At the end is so slow that it's unsable and it takes a lot of resources.

![image](https://user-images.githubusercontent.com/3635348/97644876-5b30fc00-1a43-11eb-9103-bdbb702f2f18.png)

I guess it's the same problem as #3415

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
