### ISSUE TITLE
HTML of Dynamic routes changed after deploying to Netlify and render 'Not Found Page ' before rendering the actual page

### ISSUE THREAD

**Issue by Skobraf** [decaporg/decap-cms#4535]
**Describe the bug**
I built a website using gatsby, the landing page works fine on the production since it's statically served during the build time, I have created a gatsby-node file to fetch dynamic data depending on the id in the route. `user/:id` in the /app I wrapped the routes with Apollo Provider since the communication with the server is done with GraphQl.
After navigation into " user/:id "the page render not found at first, then render the actual page wrapped inside a Section and Container that doesn't exist in my original code also as changing the className of the last `<div>` to head / main 
Code works fine in development and in build in localhost

**To Reproduce**
<img width="498" alt="Screen Shot 2020-11-05 at 11 58 10 AM" src="https://user-images.githubusercontent.com/17176117/98232771-5ea21700-1f5e-11eb-8df6-d9d71e1b5d18.png">

**Expected behavior**
The page should render fine like the development environment and in build in localhost

**Screenshots**

**Applicable Versions:**
-Gatsby app

**CMS configuration**

**Additional context**
The page is rendering Not Found for a second (depending on connexion speed), then fetch the Dynamic page wrapped in code that I didn't create and the last divs get their classNames changed

**Comment by erezrokah** [comment]
Hi @Skobraf, this is repo is meant to support Netlify CMS (a content management system developed by Netlify).
Looks like you question is not related to the CMS itself (if it does can you fill in the missing items from the issue template?).
I recommend posting your question here https://community.netlify.com/.
Providing a reproduction scenario or a repo would be very helpful too.
