### ISSUE TITLE
Ctrl+z doesn't work when typing in Hebrew

### ISSUE THREAD

**Issue by paazca** [decaporg/decap-cms#4543]
**Describe the bug**
When my keyboard language is set to Hebrew, pressing ctrl+z doesn't do anything, though other keyboard shortcuts such as ctrl+b do work. In order to undo I must switch my keyboard language to English and only then ctrl+z works correctly.

**To Reproduce**
Set the keyboard language to Hebrew, and pressing ctrl+z won't do anything.

**Expected behavior**
Pressing ctrl+z while typing in languages other than English should undo.

**Comment by joyously** [comment]
Adding a button for Undo was mentioned here: https://github.com/netlify/netlify-cms/issues/4062#issuecomment-735936424

**Comment by martinjagodic** [comment]
Closing as stale
