### ISSUE TITLE
Expose React Directly (thoughts?)

### ISSUE THREAD

**Issue by iansinnott** [decaporg/decap-cms#4568]
Would project maintainers be open to this? Rather than (or in addition to) exposing `h` we could expose `React` itself. Perhaps on the `CMS` object rather than `window`.

### Why

* React is a hard dependency of the project and is useful for extending the CMS. Utilizing the full functionality of React would make extending the CMS easier, perhaps even simpler.
* Babel et al can be configured to rewrite JSX to whatever is needed, `CMS.React.createElement` for example.

I'd be happy to PR this but wanted to get feedback first.

**Comment by Pearce-Ropion** [comment]
You can already use the full functionality of React. If you configure webpack to build your CMS instance such that it also bundles react and css you can import whatever you want. 

You should checkout gatsby's netlify CMS plugin. Even if you don't use gatsby you could probably extrapolate what you'd need  to do to use React in whatever way you want to.

**Comment by iansinnott** [comment]
Thanks @Pearce-Ropion. My thinking was that bundling React oneself would include a second copy of React, which is not ideal. If `React` was exposed globally then webpack could be configured to use that instead, however I'm not sure if that type of aliasing is possible if `React` is not exposed.

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
