### ISSUE TITLE
Bullet points not displaying on page render

### ISSUE THREAD

**Issue by austinmdem** [decaporg/decap-cms#4576]
Hey there,
Setup a blog page for my company and everything has been working great, but we noticed the bullet points are not working. Please help!

this is screenshot of the editor using their bulletpoints.
**Describe the bug**

![Screen Shot 2020-11-11 at 7 03 30 PM](https://user-images.githubusercontent.com/1585384/98890473-e1404000-2450-11eb-8cc4-8360974ada54.png)

**To Reproduce**

**Expected behavior**
to show bullet points
but when I publish it shows this:
**Screenshots**

![Screen Shot 2020-11-11 at 7 01 48 PM](https://user-images.githubusercontent.com/1585384/98890574-295f6280-2451-11eb-8a9c-76f7761eab53.png)

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**
backend:
  name: github
  branch: development
  repo: (removed for work)
 
media_folder: static/img
public_folder: /img

collections:
  - name: blog
    label: Blog
    folder: src/posts
    create: true
    fields:
      - { name: template, label: Template}
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date, date_format: YYYY-MM-DD }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: image, label: Image, widget: image }
      - { name: body, label: Body, widget: markdown }
  - name: services
    label: Services
    folder: src/services
    create: true
    fields:
      - { name: template, label: Template}
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date, date_format: YYYY-MM-DD }
      - { name: title, label: Title }
      - { name: service, label: Service}
      - { name: image, label: Service Image, widget: image }
      - { name: serviceCountryImg, label: Country Image, widget: image, required: false}
      - { name: subscription, label: Subscription Needed?}
      - { name: quickAnswer, label: Quick Answer?}
      - { name: description, label: Description, required: false}
      - { name: body, label: Body, widget: markdown }

**Additional context**

**Comment by ClaireDMT** [comment]
Hello,

Same problem here.
It works with numbers though.

![image](https://user-images.githubusercontent.com/45850166/160577231-7a5d1ad7-675e-45cf-a741-037bccbc3bf5.png)

![image](https://user-images.githubusercontent.com/45850166/160577482-3019a70a-3a15-4bc3-84d3-acebb7f1f394.png)

**Comment by flycoolman** [comment]
I have the same issue. It's been over 2 years not resolved.

**Comment by martinjagodic** [comment]
Closing as stale
