### ISSUE TITLE
Docs: move relevant features from Beta section to permanent docs

### ISSUE THREAD

**Issue by erezrokah** [decaporg/decap-cms#4608]
We have a bunch of features we can move from the Beta section to the permanent docs.

I think everything under https://www.netlifycms.org/docs/beta-features/ except `i18n` and `Nested collections` can be moved

It would make sense to move each feature at a time to make sure we're not cluttering the docs

**Comment by regromrob** [comment]
Hi @erezrokah may I be assigned to this issue please?

**Comment by glowreeya-01** [comment]
Hi @erezokah
Is this this ooen to be worked on?

**Comment by martinjagodic** [comment]
Closing in favor of #7040
