### ISSUE TITLE
markdown editor: allow image upload / do not disable "Add Component" button

### ISSUE THREAD

**Issue by LukasGentele** [decaporg/decap-cms#4611]
**Is your feature request related to a problem? Please describe.**
When using the markdown editor, the UX for inserting existing or uploading new images is not great since the "Add Component" button is disabled in markdown mode. So, I need to switch to the WYSIWYG editor first, then upload/insert the image there and then switch back to markdown.

**Describe the solution you'd like**
Why no simply leave the "Add Component" button in the editor enabled and have the same flow of "1) opening image selector popup 2) upload/select 3) insert image into the editor" for the markdown mode?

**Describe alternatives you've considered**
1) Allowing to drag&drop images into the editor would also be an option that could simplify things.
2) When switching to markdown, the editor buttons could generally change to buttons for the markdown editor instead of just showing the disabled buttons for the WYSIWYG editor. I mean, GitHub does the same for their markdown editor.

**Additional context**

**Comment by taineriley1** [comment]
Hi @LukasGentele @erezrokah,

Our users also experience this issue, and often use the Rich Text editor as it provides a better experience for them.

Elaborating on this issue, it would be great to have all of the formatting buttons at the top of the markdown widget available in markdown mode. Adding the markdown syntax by clicking a button would be easier for some users than typing it into the editor, and it doesn't make sense for some buttons to be disabled but not others if it's possible to have them all enabled.

See the video for a better explanation: https://youtu.be/u1QooafFKhw

Thanks,
Taine

**Comment by martinjagodic** [comment]
Closing as stale
