### ISSUE TITLE
Japanese IME bug when entering image alts and titles in rich text editing mode

### ISSUE THREAD

**Issue by hand-dot** [decaporg/decap-cms#4629]
**Describe the bug**

The Japanese IME does not allow you to type correctly.
The same problem may occur not only with Japanese IMEs, but also with other IMEs.

**To Reproduce**

1. Switch Rich Text editing mode.
2. Create Image.
3. Type Something 'alt' or 'title' in Japanese IME.
4. The characters you entered are not displayed correctly. 

**Expected behavior**

 Be able to type Japanese correctly in the image alto and title.

**Screenshots**

![Screen Recording 2020-11-24 at 12 51 22](https://user-images.githubusercontent.com/24843808/100047433-cfe63300-2e55-11eb-8f01-4128f6893cde.gif)

**Applicable Versions:**
 - Netlify CMS version: 
    - netlify-cms-app 2.13.3
    - netlify-cms-core 2.34.0
 - Git provider: GitHub
 - OS: macOS Catalina Version 10.15.6
 - Browser version Google Chrome Version 87.0.4280.67
 - Node.JS version: 14.15.0

**CMS configuration**

```
publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Tags",
          name: "tags",
          widget: "list",
          max: 5,
          min: 1,
          default: [],
        }

```

**Comment by martinjagodic** [comment]
Solved in Decap 3
