### ISSUE TITLE
Automagical field population on object paste

### ISSUE THREAD

**Issue by lucadalli** [decaporg/decap-cms#4672]
**Is your feature request related to a problem? Please describe.**
Consider a `translation` Object widget with fields `x` and `y`. If an editor already has the object they need to populate into the CMS available to them in JSON format ex `{ "x": 25, y: "50" }`, they need to copy-paste the value of each field one at a time. This is tolerable for smaller objects like this one, but becomes very tedious with a large number of fields.

**Describe the solution you'd like**
1. Click within the Object bounds but not on a particular field to focus the Object field.
2. Paste the entire object which was copied into the clipboard in a compatible format ex. `{ "x": 25, y: "50" }`
3. Individual fields are automagically populated
![image](https://user-images.githubusercontent.com/75124593/100939569-c5cbd080-34f6-11eb-8ba7-a1b47032cd3b.png)

**Describe alternatives you've considered**
1. Copy-pasting values into the fields one-by-one.
_Very tedious._
2. Pasting the object directly into the file, circumventing the CMS.
_Editor does not have access to files, only CMS_

**Additional context**

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
