### ISSUE TITLE
Add the "delete" property to file-level configurations

### ISSUE THREAD

**Issue by theredwillow** [decaporg/decap-cms#4730]
@tomrutgers is frequently having to address beginners who think they can add the "delete" property to "file"'s themselves. However, you can currently only add it to the "collection"'s.

https://github.com/netlify/netlify-cms/issues/1937#issuecomment-444877801
https://github.com/netlify/netlify-cms/issues/2481#issuecomment-547281102

This would be very helpful for situations (like pages) where you'd like to use the page template for the main/index page, but you can't store it in the editable folder collection because you have to child-proof the CMS for your client. The current set-up forces you to make a separate file collection of "required pages" or something like that so they can't be deleted but the other ones can.

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.

File collections are meant for files that are always there, so this would not add much value.
