### ISSUE TITLE
Date in filename should reuse an existing date field when available

### ISSUE THREAD

**Issue by pmpinto** [decaporg/decap-cms#4735]
**Is your feature request related to a problem? Please describe.**
Yes! 
When I have a `date` field and in the `slug` property I mention `{{day}}` the value outputted will come from today's date, regardless of a value in the `date` field.

**Describe the solution you'd like**
Whenever there's a field from which a date can be inferred, like `date`, the `slug` property should inherit that day for all the date properties available for it. This should probably be an opt-in thing under another config.

**Describe alternatives you've considered**
Alternatively we would also have a `slug_date_field` field which would have the `name` value of the date field, like `publish_date`.

**Additional context**
It's weird when you set a blog post for the future and end up with a inconsistent result (considering today is 17 Dec):
Publish date: 2020-12-21
Permalink: `2020-12-21-the-blog-post-title`
File name: `2020-12-17-the-blog-post-title.md`

**Comment by martinjagodic** [comment]
Closing as stale.
