### ISSUE TITLE
Can we have snippets?

### ISSUE THREAD

**Issue by pmpinto** [decaporg/decap-cms#4736]
**Is your feature request related to a problem? Please describe.**
No.
We would like our content team to be able to easily introduce blocks of text or even custom tags directly from the CMS without the need to copying from somewhere else and pasting it in the CMS.

**Describe the solution you'd like**
Following the same approach Netlify CMS already uses for folder collections, we could have a _special_ folder collection that would be identified in some way (some new property perhaps) as a snippets collection.
Inside this folder we could have snippet files:
```
my-custom-snippets
|-- link-table.md
|-- youtube-video.md
```
Each file is a snippet. Just a block of text that would be inserted in a specific point in the "body" of an blog post for instance.

This could be accessed from the already existing rich text toolbar.

**Describe alternatives you've considered**
A not so clean solution could be setting these manually in the config file.
But the beauty of the approach above is that it could act both as a snippet collection as well as a normal collection, so team members could add snippets that would be available for the whole team, from within the CMS itself.

**Comment by martinjagodic** [comment]
Closing as stale.
