### ISSUE TITLE
Adding Lithuanian TRANSLATION

### ISSUE THREAD

**Issue by mistermantas** [decaporg/decap-cms#4755]
Hi,

I want to make a PR for a Lithuanian translation.

I found this issue from the start of 2020:

https://github.com/netlify/netlify-cms/pull/3141

Is this the correct way to do it? Should I do it for a separate repository? Not quite sure about the procedure since it's been a long time since I've written JavaScript haha. Trying to follow along with this instruction in the meantime, that is, until there is a translation in the official language DB.

https://www.netlifycms.org/docs/configuration-options/#locale

**Comment by erezrokah** [comment]
Hi @mistermantas, that's great thank you!

The PR you linked is the right way to do it. I suggest using:
https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-locales/src/en/index.js

as a baseline as it is has all the translations.

**Comment by mistermantas** [comment]
Perhaps I am too eager, but do you know when the translations could be merged / go live?

**Comment by erezrokah** [comment]
Usually we do it in a few days/less, but I can guarantee a timeline (especially now due to upcoming holidays).
