### ISSUE TITLE
datetime, datepicker and label miss match when picker_utc set to true

### ISSUE THREAD

**Issue by pdkn** [decaporg/decap-cms#4784]
**Describe the bug**
datetime picker and date label do not match up ( possibly when UTC is set to true? (I'm in GMT timezone))

**To Reproduce**
1. create a datetime picker with below YAML
2. set date to 7th July 2016
3. notice the picker is set to 06/06/2016 ( a day out )

**Expected behavior**
Expect the date picker and date label to match.

**Screenshots**

https://user-images.githubusercontent.com/186148/103370865-dfe0da80-4ac5-11eb-98c9-b243a789ec46.mov

**Applicable Versions:**

 - Netlify CMS version:  2.14.8
 - Git provider: GitHub
 - OS: Mac
 - Browser version [e.g. chrome 22, safari 11]

**CMS configuration**

`- name: 'testimonials'
    label: 'Testimonials'
    folder: 'app/content/testimonials'
    create: true
    slug: '{{slug}}_{{date}}'
    format: 'json'
    sort: 'published_at:desc'
    identifier_field: 'name'
    fields:
      - { label: 'Name', name: 'name', widget: 'string'  }
      - { label: 'Date', name: 'date', widget: 'datetime', date_format: true, time_format: false, format: "Do MMMM YYYY", picker_utc: true }
      - { label: 'Testimonials', name: 'testimonial', widget: 'text'}
      - { label: 'Homepage', name: 'homepage', widget: 'boolean', default: false }`

**Additional context**

**Comment by pachicodes** [comment]
Hey, I am new to open source and would like to work on this issue!

**Comment by erezrokah** [comment]
Hi @pachicodes and welcome 👋
A contribution for this would be great!
The place to start should be somewhere here:
https://github.com/netlify/netlify-cms/blob/ada552dc147e268acf0a2d6cbea0d7107cb3ed73/packages/netlify-cms-widget-datetime/src/DateTimeControl.js#L144

and our contributing guide is [here](https://github.com/netlify/netlify-cms/blob/master/CONTRIBUTING.md).

Please comment on the issue if you any questions.
Thanks!

**Comment by pachicodes** [comment]
Hi @erezrokah rhank youfor being so welcoming!

I thought I would have time for this but I just started a new job and I am busier than I expected so I no longer will be able to contribute.
Sorry about that!

**Comment by AshtarCodes** [comment]
Hi, I'd like to work on this issue! Is it still available/open?

**Comment by erezrokah** [comment]
Hi @AshtarCodes, I believe it is! I've assigned you to it. Thanks you ❤️ Please let me know if you have any questions

**Comment by AshtarCodes** [comment]
No problem. Thanks, I will!

**Comment by AshtarCodes** [comment]
@erezrokah Hi Erez, I'm not sure how to use the yaml to recreate the issue. I was able to get the CMS build running and checked the blog post date picker, and did not find the issue. Could you point me to a resource for recreating with yaml? Also would you prefer I reach out through the slack group? I joined recently. Thank you!

**Comment by AshtarCodes** [comment]
Hi @erezrokah, 

I used the above YAML to deploy the CMS on a gatsby template, and I haven't been able to recreate the bug. Below are two videos (chrome, and firefox) where I try to recreate it. I'm new to this, so feel free to let me know if there is something obvious I may have missed.  

https://res.cloudinary.com/ashsheran1/video/upload/v1614651885/Video/Content_Manager_-_Google_Chrome_2021-03-01_21-11-09_olcuad.mp4

https://res.cloudinary.com/ashsheran1/video/upload/v1614651889/Video/Content_Manager_Firefox_Developer_Edition_2021-03-01_21-09-16_nnayry.mp4

Applicable Versions:

    Netlify CMS version: 2.10.91 (I think)
    Git provider: GitHub
    OS: Windows 10 Home Build 19041
    Browser version [e.g. chrome 88, Firefox developer edition 87]

**Comment by pdkn** [comment]
Thanks for looking at this. I haven’t had time myself. This is likely a time zone bug. I assume you are in USA? Try UK timezone.

**Comment by anibali** [comment]
I'm getting a similar issue from an Australian time zone (GMT+10).

My configuration:
```yaml
- {label: "Incident date", name: "incident_date", widget: "datetime", date_format: "D/M/YYYY", time_format: false, picker_utc: true, format: "YYYY-MM-DD", default: "", hint: "The date of the alleged incident."}
```

My preview code:

```javascript
var dateFormat = new Intl.DateTimeFormat('en-US', { month: 'long', day: 'numeric', year: 'numeric', timeZone: 'UTC', timeZoneName: 'short' });
var incidentDate = Date.parse(entry.getIn(['data', 'incident_date']));
// ...
h('tr', {}, [
  h('td', {}, h('b', {}, 'Incident date:')),
  h('td', {}, dateFormat.format(incidentDate)),
]),
```

What happens in the date picker (tested at 4:48 PM, August 23 my time):

https://user-images.githubusercontent.com/226707/130403566-d341f17d-e62c-4307-bd42-b291ea4c3d7b.mp4

**Comment by martinjagodic** [comment]
I can't replicate the OG issue with just the config provided, I would also need the preview template code.

I did replicate @anibali issue, but this is just a matter of parsing the date with your preview template. The value set by the CMS is correct.

I am closing this issue as not reproducible. If anyone finds something similar, please share both your config and preview code.
