### ISSUE TITLE
Media Manager - Asset tagging / filtering - Feature Request

### ISSUE THREAD

**Issue by MattyBFiresprite** [decaporg/decap-cms#5029]
Hi 

We love netlify and the CMS, we do! Our web agency used the technology to build our website at firesprite.com.

We're using netlify CMS and now we have quite a lot of imagery uploaded in there, it's getting a bit unwieldy.  Do you guys think it would be possible to add metadata tags to media in the future or something similar so that assets can be filtered or organised?

thanks!

**Comment by erezrokah** [comment]
Hi @MattyBFiresprite, we have several issues about improving the media library:
https://github.com/netlify/netlify-cms/issues/2557
https://github.com/netlify/netlify-cms/issues/2243
https://github.com/netlify/netlify-cms/issues/4965
https://github.com/netlify/netlify-cms/issues/1032
https://github.com/netlify/netlify-cms/issues/3240

Can you please update the issue description to match our [feature request template](https://github.com/netlify/netlify-cms/issues/new?assignees=&labels=type%3A+feature&template=feature_request.md&title=Please+replace+with+a+clear+and+descriptive+title) to we can better estimate how it fits into current issues?

**Comment by MattyBFiresprite** [comment]
Sorry - I need coffee - have mistakenly opened a new ticket with a more precise description- -please delete this one. Apologies.
