### ISSUE TITLE
"hint" isn't documented on configuration options page.

### ISSUE THREAD

**Issue by mikelehen** [decaporg/decap-cms#5062]
**Describe the bug**
I had trouble discovering the `hint` option that can be applied to any field (added via https://github.com/netlify/netlify-cms/pull/1429).  I now see that it is documented on the *Widgets* page, but it isn't documented under the `fields` documentation on https://www.netlifycms.org/docs/configuration-options/#fields and I think it probably should be?

**Screenshots**
![image](https://user-images.githubusercontent.com/206364/110173728-e8021280-7db3-11eb-9530-f67b116865b4.png)

**Comment by tomrutgers** [comment]
The fields object itself doesn't have any configuration, it's just a list of widgets, so suggesting it's possible to set a hint property for the fields object might not be a good idea.

**Comment by mikelehen** [comment]
The widgets page [says](https://www.netlifycms.org/docs/widgets/#common-widget-options) there are 3 options available on all fields:
![image](https://user-images.githubusercontent.com/206364/110215003-513d6080-7e5c-11eb-80e3-890a422b29e0.png)

The fields [documentation](https://www.netlifycms.org/docs/configuration-options/#fields) documents 2 of them (required and pattern) but not `hint`.  
![image](https://user-images.githubusercontent.com/206364/110215075-ac6f5300-7e5c-11eb-87e9-413596e9c40d.png)

It's not clear to me why `hint` would be special and not be documented in both places.

**Comment by erezrokah** [comment]
I don't see any harm in adding `hint` under `fields` and also making it more clear that those fields are per object and not for the entire `fields`.
@mikelehen  would you like to submit a PR for it?
