### ISSUE TITLE
Can't type some diacritics in rich text/markdown editor (Windows-1250, ISO 8859-2 characters like ď or ť)

### ISSUE THREAD

**Issue by mikz** [decaporg/decap-cms#5108]
**Describe the bug**
You can't type some characters using Windows-1250, CP-1250, ISO 8859-2 keyboard characters in Safari 14.0.x on macOS.
Specifically ď or ť characters. You type those by first using the diacritics ˇ and then d making a ď. Or ˇ plus t to make ť.
Instead of the diacritics character the normal latin one is used. Using Czech keyboard layout.
This happens only in Rich text/Markdown editor. Works in other input fields. Works in Chromium based browsers.

**To Reproduce**

Open any Rich or Markdown editor.
Type in **ˇ** followed by **d**. 

**Expected behavior**
See character **ď**

What happens instead:
see just plain **d**

**Screenshots**

https://user-images.githubusercontent.com/154571/111054324-ff07cb00-846b-11eb-9407-fb3fd284a37f.mov

**Applicable Versions:**
 - Netlify CMS version: Tested version from 2.10.40 to 2.10.99
 - OS: macOS Big Sur
 - Browser version: Safari Version 14.0.3 (16610.4.3.1.4)

**Additional context**
This used to work about 3 months ago. Looks like some Safari release broke this. Initially I assumed it was Netlify CMS version, since I'm using latest 2.x, but I tested versions going 1 year back and still can reproduce the issue in Safari.

**Comment by mikz** [comment]
BTW I'm happy to dig in if you could give me pointers where to find the relevant code. It looks to me like it might be in the slate editor.

**Comment by erezrokah** [comment]
Hi @mikz I can't think of a specific place that can cause this.
The code for the markdown editor is here https://github.com/netlify/netlify-cms/blob/560f17d8bdbde9536f80a66f8d50524f5480a719/packages/netlify-cms-widget-markdown/src/MarkdownControl/RawEditor.js

**Comment by mikz** [comment]
netlify-cms is using old Slate (0.49, from 2019). 

Character composition is a difficult topic  from the looks of the issues in Slate tracker. Latest slate supports character composition correctly. I've tried debugging the editor and indeed it looks like latest Safari changed order of some events and broke Slate 0.49. It is not able to recognise the composed character.

**Comment by mikz** [comment]
Any plans to update Slate?

**Comment by erezrokah** [comment]
Hi @mikz, see https://github.com/netlify/netlify-cms/issues/1347#issuecomment-809187277
