### ISSUE TITLE
Guide for custom widgets does not work (written for outdated deps?)

### ISSUE THREAD

**Issue by hermanbanken** [decaporg/decap-cms#5139]
When following the guide for custom widgets I'm having issues when I follow the steps outlines in the guide.
My repository with reproduction scenario:
https://github.com/hermanbanken/hugocrypt/tree/master/widget
https://github.com/hermanbanken/hugocrypt/tree/15c7eba0d2ccd3956cb76f298746809241f39f11 (permalink)

**Describe the bug**
Opening the editor (clicking "New") with a custom widget causes the error 

```
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

**To Reproduce**
Enable the commented out field of posts:

```yaml
      # - { label: 'Users', name: 'users', widget: 'hugocryptUsers' }
```

click "New" for posts. The error shows.

**Expected behavior**
Showing an editor

**Screenshots**
<img width="952" alt="Screenshot 2021-03-21 at 17 16 03" src="https://user-images.githubusercontent.com/791189/111912269-257bc680-8a69-11eb-8817-12d7118b3f08.png">

**Applicable Versions:**
 - Netlify CMS version: 2.10.100 (latest?)
 - Git provider: none (local dev)
 - OS: OSX Catalina
 - Browser version: Chrome
 - Node.JS version: 12

**CMS configuration**
See repo at the top.

**Additional context**
The fact that netlify-cms ships with the production React bundle does hinder the debugging. It would be great if using a React development build was possible. I think it should be outlined in the guide how to set that up, for people without deep Webpack/ES6-module-loading knowledge.

**Comment by martinjagodic** [comment]
Closing as stale
