### ISSUE TITLE
Allow customisation of git push command

### ISSUE THREAD

**Issue by Undistraction** [decaporg/decap-cms#5223]
**Is your feature request related to a problem? Please describe.**
There is currently no way to have Netlify CMS pass push options to the remote repo when pushing. [Push options](https://git-scm.com/docs/git-push#Documentation/git-push.txt--oltoptiongt) are really useful for customising pipeline behaviour and a good alternative to using branch names to change CI behaviour. For example it would be nice to be able to tell Netlify CMS to deploy to the CMS environment and skip certain build stages. Here is an example for Gitlab:
```
git push -o ci.variable='EXCLUDES=static,unit,e2e'
```

**Describe the solution you'd like**
It would be nice if Netlify CMS provided a config param to define flags to add to `git push`. 

**Describe alternatives you've considered**
The only other alternative is to change CI behaviour based on branch, but this doesn't really work with dynamic branches.

**Comment by erezrokah** [comment]
Hi @Undistraction, the CMS does't use the `git` protocol, it uses each provider API to manage content.
e.g. https://github.com/netlify/netlify-cms/blob/e32ffdf587a7a75f6116da990209a648f4ad01fe/packages/netlify-cms-backend-github/src/API.ts#L1437

Some CIs support using commit messages for the same use case, which you should be able to configure via https://www.netlifycms.org/docs/beta-features/#commit-message-templates

**Comment by martinjagodic** [comment]
Closing as stale.
