### ISSUE TITLE
More than one * in formula ends up being moved around to italic

### ISSUE THREAD

**Issue by lsolesen** [decaporg/decap-cms#5252]
**Describe the bug**

**To Reproduce**

In my repo I Netlify CMS created this commit after updating using the CMS https://github.com/motionsplan/motionsplan-dk-jekyll/pull/85/commits/de011ebb79444ae95746ab217477f1bc8716c6d5#diff-c9808a953d6ec002a541961d4a2611d8cce232a4efd31a3104c1cc0d43ccf2d4R70

I have the following formula writting in:

    {% include math formula="PBF = \frac{0.988 * BMI + 0.344 * weight (kg) + 0.094 * age - 30.18}{height (m)^2}" %}

After editing with the netlify cms the to * are moved, so it becomes:

    {% include math formula="PBF = \frac{0.988  *BMI + 0.344*  weight (kg) + 0.094 * age - 30.18}{height (m)^2}" %}

I would like to avoid that, as that messes up the formula.

**Expected behavior**

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: 2.0.11
 - Git provider: GitHub
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

https://github.com/motionsplan/motionsplan-dk-jekyll/blob/master/admin/config.yml

**Additional context**

**Comment by erezrokah** [comment]
Hi @lsolesen, have you considered using a [custom editor component](https://www.netlifycms.org/docs/custom-widgets/#registereditorcomponent) to wrap the formula data?

**Comment by lsolesen** [comment]
I hadn't considered that. But taking up your suggestion, I added a lot of custom editor components. Got most of them to work including the math-related custom widget. Might however still be a bug, that it strips whitespace around written in formulas.

When the formula was just written like this:

    PBF = 1.34 * BMI * 12.47

Then it got escaped like this:

    PBF = 1.34 \* BMI \* 12.47

**Comment by erezrokah** [comment]
> Might however still be a bug, that it strips whitespace around written in formulas.

Yep, keeping this open pending further investigation

**Comment by martinjagodic** [comment]
Closing as stale
