### ISSUE TITLE
Netlify CMS moves around the frontmatter

### ISSUE THREAD

**Issue by lsolesen** [decaporg/decap-cms#5253]
**Describe the bug**

I put my frontmatter in a particular order in my config.yml - https://github.com/motionsplan/motionsplan-dk-jekyll/blob/master/admin/config.yml

However, after saving with the Netlify CMS it puts the frontmatter in another order, than specified in the the config.yml file.

This is an example after saving with the Netlify CMS where `last_modified_at` and `permalink` went to the top of the frontmatter instead of the title.
https://github.com/motionsplan/motionsplan-dk-jekyll/pull/78/files

Any chance to avoid this?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: 2.0.11
 - Git provider: GitHub
 - OS:
 - Browser version chrome 22
 - 
 - Node.JS version:

**CMS configuration**

https://github.com/motionsplan/motionsplan-dk-jekyll/blob/master/admin/config.yml
**Additional context**

**Comment by erezrokah** [comment]
We are sorting the keys here https://github.com/netlify/netlify-cms/blob/6561939d42c518d90f90d5e181eb5f74dbab6bb8/packages/netlify-cms-core/src/formats/helpers.js#L2, so maybe there's a bug in that code.

**Comment by AbdallahAbis** [comment]
@lsolesen How can I reproduce that? so I have a experience debugging.

**Comment by bytrangle** [comment]
@lsolesen : In the Markdown file created, I saw that the fields `permalink` and `last_modified_at` are below `title` field. Isn't that how it's supposed to be?

**Comment by lsolesen** [comment]
If I edit using the editor then it moves around --> https://github.com/motionsplan/motionsplan-dk-jekyll/pull/88/files

**Comment by martinjagodic** [comment]
Closing as stale
