### ISSUE TITLE
A  EditorComponent wit relation does not fill in the relation when reloading

### ISSUE THREAD

**Issue by lsolesen** [decaporg/decap-cms#5260]
**Describe the bug**

I have added a relation widget to a custom editor component https://github.com/motionsplan/motionsplan-dk-jekyll/blob/master/admin/index.html#L140.

```
CMS.registerEditorComponent({
    // Internal id of the component
    id: "exercise",
    // Visible label
    label: "Exercise",
    // Fields the user need to fill out when adding an instance of the component
    fields: [
      {name: 'key', label: 'Key', widget: 'relation', collection: 'exercises', search_fields: ["title", "key"], value_field: "key", display_fields: ["title", "key"]}
    ],
    // Pattern to identify a block as being an instance of this component
    pattern: /^\{% include exercise key=\"(\S+)\" %\}$/,
    // Function to extract data elements from the regexp match
    fromBlock: function(match) {
      return {
        key: match[1]
      };
    },
    // Function to create a text block from an instance of this component
    toBlock: function(obj) {
      return '{% include exercise key="' + obj.key + '" %}';
    },
    // Preview output for this component. Can either be a string or a React component
    // (component gives better render performance)
    toPreview: function(obj) {
      return (
        '<p>Exercise: ' + obj.key + '</p>'
      );
    }
  });
```

I works properly when wanting to fill in the widget. When I switch to Markdown mode the code has been properly set in. Switching back to Rich Text however, the custom editor component is shown but does populate with the chosen relation.

![Screenshot - 2021-04-13T075715 422](https://user-images.githubusercontent.com/148026/114503713-05859000-9c2e-11eb-9fb4-dc94e723be70.png)

![Screenshot - 2021-04-13T075751 788](https://user-images.githubusercontent.com/148026/114503727-09b1ad80-9c2e-11eb-8f90-332c3d21c494.png)

![Screenshot - 2021-04-13T075810 579](https://user-images.githubusercontent.com/148026/114503732-0b7b7100-9c2e-11eb-923f-8fcee091230a.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: 2.10.111
 - Git provider: GitHub
 - OS: [e.g. Windows 7]
 - Browser version chrome 89.0.4389.114

 - Node.JS version:

**CMS configuration**

https://github.com/motionsplan/motionsplan-dk-jekyll/blob/master/admin/config.yml

**Additional context**

**Comment by arpadgabor** [comment]
Hey @lsolesen , I'm using a similar setup with a relation widget in a project and it works fine. Try `console.log(match)` in the `fromBlock` method. Most likely the problem is related to the regex.

**Comment by lsolesen** [comment]
@arpadgabor Thanks for your reply

```
0: "{% include exercise key="43" %}"
1: "43"
```

It returns the correct key?

**Comment by martinjagodic** [comment]
Closing as stale
