### ISSUE TITLE
Customise the front-matter ouput generated by NetlifyCMS

### ISSUE THREAD

**Issue by eurecomphil** [decaporg/decap-cms#5263]
**Is your feature request related to a problem? Please describe.**
I would like to customize the way Netlify CMS writes down fields in the front-matter. I've spent two days looking for this answer but I've found nothing until now.
BTW, Netlify CMS is just amazing. Thank you for the work done, since then, my users stopped putting markdown files in the wrong places :-)

**Describe the solution you'd like**
I am using (old) HUGO + academic theme, and I need to have in the content markdown generated by NetlifyCMS, as follows (otherwise Hugo does not compile) :  
Either this :  
```
url_icon:
  - icon: envelope
    link: mailto:toto@toto.om
  - icon: institution
    link: http://www.toto.com 
```
or this :
```

[[url_icon]]
icon = "institution"
link = "http://www.toto.com"
[[url_icon]]
icon = "envelope"
link = "mailto:toto@toto.om"
```
**QUESTION : ** Is there any way to do this with Netlify CMS ? 

**Describe alternatives you've considered**
I am using the NetlifyCMS "duplicate" button everytime I want to create a new content but it is a shame not fully use this amazing tool which is Netlify CMS

**Comment by jasikpark** [comment]
Maybe you can make a custom widget? Wouldn't that be a map essentially?

**Comment by martinjagodic** [comment]
Closing as stale
