### ISSUE TITLE
Cannot write accents with dead keys - markdown editor

### ISSUE THREAD

**Issue by yajo** [decaporg/decap-cms#5306]
**Describe the bug**

While writing non-English content with accents, my keyboard requires combining 2 keystrokes (accent - then letter. Spanish has áéíóúü). The accented letter is erased in the markdown editor.

**To Reproduce**

Just write with dead keys accents in markdown editor.

**Expected behavior**

Normal writing.

**Screenshots**

https://user-images.githubusercontent.com/973709/116125493-75c7f300-a6bd-11eb-8a7a-45e580d25653.mp4

**Applicable Versions:**

 - Netlify CMS version:  netlify-cms-app 2.14.46, netlify-cms-core 2.39.6, netlify-cms 2.10.117
 - Git provider: Gitlab
 - OS: Fedora 33 Silverblue
 - Browser version Firefox 87.0

**CMS configuration**

https://www.recallstack.icu/admin/config.yml

**Additional context**

It seems to work fine on Chromium.

**Comment by pmarcus93** [comment]
This is happening to me as well. 
I write in Brazilian Portuguese and I'm having the same issues with characters such as ç, ã, á, é and so on.

OS: Pop_OS! 21.10.
Browser: Firefox 95.0.1 (64-bits).

**Comment by Yajo** [comment]
Interestingly, today I tested on Firefox on Windows and it works. So, it seems the buggy combination is Firefox + Linux.

**Comment by miltonbolonha** [comment]
Tag widget cannot have these Brazilians characters :(
I need those.

**Comment by vitorrloureiro** [comment]
I'm also having this problem in macOS Safari (tested in v16 and v16.1, macOS Monterey and macOS Ventura).

**Comment by freesteph** [comment]
NetlifyCMS uses Slate under the hood, which seems to have fixed the problem now. Typing accents on:

https://www.slatejs.org/examples/richtext

works fine. 

Slate's current release is [0.87.0](https://github.com/ianstormtaylor/slate/releases/tag/slate%400.87.0)
[Netlify uses 0.47](https://github.com/netlify/netlify-cms/blob/65343c1238af85e9151abb6bbba3770a08091176/packages/netlify-cms-widget-markdown/package.json#L36).

Maybe a simple upgrade would do the trick?

**Comment by mitchbox** [comment]
When will the team upgrade the Slate?

**Comment by vitorrloureiro** [comment]
> When will the team upgrade the Slate?

I was looking at their support forum and apparently this is not maintained anymore. I found that there's a fork of it. I haven't tried it yet but looks interesting: [Static CMS](https://staticjscms.netlify.app)

**Comment by mitchbox** [comment]
Too bad... Thank you for sharing the information.

**Comment by martinjagodic** [comment]
Fixed in Decap 3
