### ISSUE TITLE
Pasting HTML along with Markdown in Rich Text Editor breaks markdown syntax

### ISSUE THREAD

**Issue by pmpinto** [decaporg/decap-cms#5369]
**Describe the bug**
Like the title reads, when you paste HTML along with your markdown content in the Rich Text editor, you end up with a broken markdown syntax.

The same doesn't happen when pasting in Markdown mode.

And saving the changes doesn't affect this behaviour, so it's an editor thing.

**To Reproduce**
Content example:
```markdown
<h1>Hi</h1>
Oh, hello world! Take [this](https://github.com/netlify/netlify-cms/) with you.
```

1. Copy the content above
2. Paste it in the rich text editor
3. Notice the link isn't actually transformed as a link
4. Switch to the markdown mode
5. Notice the `\` before the link (which breaks the link syntax):
    ```markdown
    <h1>Hi</h1>
    Oh, hello world! Take \[this](https://github.com/netlify/netlify-cms/) with you.
    ```

You can repeat the steps above but on step 2 instead of pasting in rich text, do it in markdown.
The issue is gone, `\` isn't there.

**Expected behavior**
I would expect the editor to be able to deal with both HTML and markdown, and _especially_ not break my markdown syntax.

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.10.124]
 - Git provider: GitHub
 - OS: macOS 11.2.3
 - Browser version: Brave v1.21.77

**CMS configuration**

The file is too big, and I'm not sure which parts, if any, can be related to this issue. Let me know if this is needed.

**Additional context**

**Comment by martinjagodic** [comment]
Closing as stale.
