### ISSUE TITLE
Unable to add Netlify CMS to a Gatsby Site

### ISSUE THREAD

**Issue by castasint** [decaporg/decap-cms#5389]
I am trying to add netlify cms plugin(using npm install netlify-cms-app gatsby-plugin-netlify-cms but I am getting the below error. I'm following this post [https://www.gatsbyjs.com/docs/how-to/sourcing-data/sourcing-from-netlify-cms/](https://www.gatsbyjs.com/docs/how-to/sourcing-data/sourcing-from-netlify-cms/). Any advice on how it can be fixed?

Error: 
![image](https://user-images.githubusercontent.com/16588875/118278025-1e13ef00-b4e7-11eb-92bb-b4d51be6a3d7.png)

My Package.Json file:

![image](https://user-images.githubusercontent.com/16588875/118278074-2a984780-b4e7-11eb-83e3-6e38d68ca386.png)

**Comment by boehs** [comment]
```traceback
unsentRequest.js:41 GET https://[censored]/.netlify/git/settings 400
[sic]
auth.js:112 API_ERROR: Git Gateway Error: [object Object]
    at new t (https://unpkg.com/netlify-cms@%5E2.0.0/dist/netlify-cms.js:54:90143)
    at new i (https://unpkg.com/netlify-cms@%5E2.0.0/dist/netlify-cms.js:54:90450)
    at https://unpkg.com/netlify-cms@%5E2.0.0/dist/netlify-cms.js:520:10667
    at async https://unpkg.com/netlify-cms@%5E2.0.0/dist/netlify-cms.js:520:10268
```
also having issues with unpkg, git sign in fails.

**Comment by smashercosmo** [comment]
You're using npm 7 which automatically installs peer dependencies. But as you can see from the error, there are conflicts between different versions of dependencies. Easy way to fix it is to opt out of this behaviour by running ```npm i netlify-cms-app gatsby-plugin-netlify-cms --legacy-peer-deps```

**Comment by martinjagodic** [comment]
Solved by @smashercosmo
