### ISSUE TITLE
"Remember Me" option for login

### ISSUE THREAD

**Issue by tech4him1** [decaporg/decap-cms#539]
We should probably have a way for users to choose whether or not they should stay logged in over CMS reloads, etc. Right now, whenever a user logs in, the OAuth `access_token` is stored until the user logs out, so that the user does not need to re-login every time the CMS is reloaded. Some users, however, may not want this (e.g. if they are using a shared computer).

We would need to implement this somehow on the login screen, and pass the value to the backend when the login is `dispatch`ed. We can then check if it is checked or not when we go to store the credentials: [src/backends/backend.js#L85](https://github.com/netlify/netlify-cms/blob/master/src/backends/backend.js#L85).

**Comment by tech4him1** [comment]
How should this look on the login screen? The benefit of the login screen as it stands is its simplicity, but I don't know a better location to add a "Remember Me" box.

**Comment by erquhart** [comment]
Yep, it would have to happen on the login screen.

**Comment by tech4him1** [comment]
Should the value of the "Remember Me" checkbox should be saved, so the user does not need to check/uncheck it every time.

**Comment by erquhart** [comment]
Yep, agreed.

**Comment by neutyp** [comment]
Hmm, do we have a larger issue to redesign the login experience? We need some bigger UI thinking there

**Comment by erquhart** [comment]
@neutyp no, not yet. Please feel free to open new issues.

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
