### ISSUE TITLE
Do not remove quotation marks from frontmatter

### ISSUE THREAD

**Issue by lsolesen** [decaporg/decap-cms#5439]
**Describe the bug**

I have a value like this in my frontmatter:

```
coords:
    - "1,4,5,3,45,34"
```

However, after editing the post the quotation marks are removed so, and now it is no longer considered a string in liquid. That means I can no longer just {{ c }}, as this will output `14534534` and not like `1,4,5,3,45,34` which it would before removing the quotation marks.

**To Reproduce**

The quotation marks seems to always be removed like here - https://github.com/motionsplan/motionsplan-dk-jekyll/pull/74/files#diff-e2e171531dbff3ff531fa7df1eb53dc5720cd96416379996ffd3e7306bbd73f2L36

**Expected behavior**

Make it possible to have a comma separated list as a string. Maybe a setting on the individual widget.

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: 2.10.131
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

https://github.com/motionsplan/motionsplan-dk-jekyll/blob/master/admin/config.yml

**Additional context**

**Comment by erezrokah** [comment]
Hi @lsolesen, does removing the quotation marks has any negative effect?

If you past the content [here](https://onlineyamltools.com/convert-yaml-to-json) you'll see those are still parsed as strings.

**Comment by lsolesen** [comment]
Yes. It has started outputting without the commas.

**Comment by martinjagodic** [comment]
Closing as stale

**Comment by loup-brun** [comment]
**On the feature request to allow force-quoting strings:** I have a project using Jekyll, removing the quotation marks indeed alters the output, e.g.:

```yaml
# dimensions, in cm
# with Jekyll, this will output 254, missing the comma
height: 25,4
# this will be parsed correctly
width: "12,5"
```
 
> If you paste the content [here](https://onlineyamltools.com/convert-yaml-to-json) you'll see those are still parsed as strings.

Well, that depends on the front-matter parsing engine. Jekyll uses [`safe_yaml`](https://github.com/dtao/safe_yaml/), and this impacts the output (the ability to force-quote a string via Decap would be desirable here). For the record, [this answer on StackOverflow](https://stackoverflow.com/a/22235064) specifies that for values containing special characters (including the comma `,`), quotes are needed:

> Use quotes if your value includes special characters, (e.g. `:`, `{`, `}`, `[`, `]`, `,`, `&`, `*`, `#`, `?`, `|`, `-`, `<`, `>`, `=`, `!`, `%`, `@`, `\`).
