### ISSUE TITLE
Display author of the changes in the Workflow tab

### ISSUE THREAD

**Issue by pmpinto** [decaporg/decap-cms#5466]
**Is your feature request related to a problem? Please describe.**
Say you're working on the same file as a team mate of yours. You both have pending changes on that file. Both changes appear under the Workflow.
How do you know which one is yours?
You would need to click and search for your changes to make sure.

**Describe the solution you'd like**
A small line like `{avatar} {name}` or really just `{name}` below the collection name inside the change card would do just fine.

**Describe alternatives you've considered**
None

**Additional context**
A quick mockup:
<img width="453" alt="Screenshot 2021-06-01 at 16 36 04" src="https://user-images.githubusercontent.com/4265830/120351125-804a5d80-c2f7-11eb-80aa-4191c859fb22.png">

**Comment by himanshu007-creator** [comment]
Hi! i would like to work on this issue

**Comment by himanshu007-creator** [comment]
I would need some help, as i am new here, Please guide me for what needs to be be done and where. This will make it easier for me to contribute next  time😄

**Comment by erezrokah** [comment]
Hi @himanshu007-creator, thank you for looking into this.
The code for rendering the workflow card is here:
https://github.com/netlify/netlify-cms/blob/444f30689b366f2479a0039414a314a809b2b980/packages/netlify-cms-core/src/components/Workflow/WorkflowCard.js

You'll need to propagate that information from each backend, for example from here:
https://github.com/netlify/netlify-cms/blob/444f30689b366f2479a0039414a314a809b2b980/packages/netlify-cms-backend-github/src/API.ts#L583

Also see https://github.com/netlify/netlify-cms/blob/master/CONTRIBUTING.md

**Comment by himanshu007-creator** [comment]
hi @erezrokah! sorry i was on vacations. I am unable to understand the changes. Can you pinpoitn the chanegs needed. 
P.S ( i will be better prepared for next time)

**Comment by erezrokah** [comment]
Hi @himanshu007-creator, the end result should be adding the post author in workflow tab:
![image](https://user-images.githubusercontent.com/26760571/122924659-adc27e00-d36e-11eb-937c-60257550fb13.png)

to each post as seen in the issue description.

The UI code to change is here https://github.com/netlify/netlify-cms/blob/444f30689b366f2479a0039414a314a809b2b980/packages/netlify-cms-core/src/components/Workflow/WorkflowCard.js#L136

but you'll need to get that information from each backend as I mentioned in my previous comment.

**Comment by pr0grammm** [comment]
Hello @erezrokah I would like to work on this feature please! Post author here refers to the author of the PR right? So for the GitHub backend for exampIe, I would need to propagate the value of pullRequest.user.login I guess? Please correct me if I am mistaken.

**Comment by erezrokah** [comment]
Thanks @pr0grammm! I think you're correct with all you questions/answers

**Comment by pr0grammm** [comment]
Thanks, please check out the PR 🙂
