### ISSUE TITLE
Improve Table /Overflow UX

### ISSUE THREAD

**Issue by willbuck** [decaporg/decap-cms#5659]
**Is your feature request related to a problem? Please describe.**
Being unable to see all the content on a page and not see a horizontal scroll bar makes actually seeing that content difficult. The content editing window gives no indication the published result will have horizontal overflow

See screenshots below:

<img width="2203" alt="Screen Shot 2021-07-30 at 4 06 31 PM" src="https://user-images.githubusercontent.com/242604/127712249-f39931c5-931e-48e2-ab2c-65080b8ea7ae.png">
<img width="2253" alt="Screen Shot 2021-07-30 at 4 08 18 PM" src="https://user-images.githubusercontent.com/242604/127712259-7df9ca8d-1c5f-4c0c-a0bf-07f81fe727a4.png">
<img width="2253" alt="Screen Shot 2021-07-30 at 4 09 51 PM" src="https://user-images.githubusercontent.com/242604/127712271-9ecd7218-3790-41ad-ad8d-040020200a3d.png">

**Describe the solution you'd like**
I would love to see either / and:
- The content preview in the editing pane warn me what might cause horizontal overflow
- The content area in the published result expand to meet overflowing content

**Describe alternatives you've considered**
Not sure

**Additional context**
First time looking at this repo, but I really admire Netlify's work and mission broadly and would love to have a solid CMS solution like this one to empower HR/Marketing to own a company website!

I was looking for how one might do Google OAuth so they could do so, and bumped across this issue. I feel like it might be a tough sell to them to use the solution generally without a slightly richer preview!

**Comment by abdmmar** [comment]
Hi! @erezrokah, can I try to take this issue?

**Comment by erezrokah** [comment]
Sure @abdmmar, that would be great.
The site code is here:
https://github.com/netlify/netlify-cms/tree/edaf9804eb51c90bfedb666b1747caf33f12b048/website/src/components
https://github.com/netlify/netlify-cms/tree/edaf9804eb51c90bfedb666b1747caf33f12b048/website/src/pages

**Comment by erezrokah** [comment]
Going to re-open as https://github.com/netlify/netlify-cms/pull/5680 only partially fixes this.
The deploy preview part is still missing

**Comment by willbuck** [comment]
Thank you all so much!

**Comment by Ranzeb** [comment]
I am new to open-source contributions and I want to contribute.  Can I handle this issue?

**Comment by martinjagodic** [comment]
This was done a while ago
