### ISSUE TITLE
Make 'Save' button's state more visible

### ISSUE THREAD

**Issue by taineriley1** [decaporg/decap-cms#5701]
**Is your feature request related to a problem? Please describe.**

The 'Save' button is currently disabled when no changes are made to the entry, and is grey in colour. It is enabled when changes are made to the entry, and is blue in colour. However, the difference between the 2 states is not obvious enough. The button needs to be more prominent and easier to distinguish between the states.

**Describe the solution you'd like**

Change the styling of the button to make it more obvious when enabled.
I suggest making the background color of the button darker to make it stand out against the white more. Making the text of the disabled state a lighter grey would also help.

**Describe alternatives you've considered**

Any other larger styling changes to the button would make it too different from other buttons in the UI.

**Additional context**

![image](https://user-images.githubusercontent.com/40375803/128813008-0941b4bd-13f1-49a0-af07-87f6065085a6.png)
**Figure: Disabled 'Save' button**

![image](https://user-images.githubusercontent.com/40375803/128813130-a1ba3fea-885d-4a8c-8e2b-7a339eb50b98.png)
**Figure: Enabled 'Save' button - colours are soft and similar to grey disabled state**

![image](https://user-images.githubusercontent.com/40375803/128973507-7cae653c-2ebb-4dd9-83a0-13090378721c.png)
**Figure: Example of less prominent disabled 'Save' button style**

![image](https://user-images.githubusercontent.com/40375803/128812927-1dea6bf7-6770-4657-aaf1-001c19db03dc.png)
**Figure: Example of more prominent enabled 'Save' button style**

**Comment by martinjagodic** [comment]
Closing as stale

**Comment by benjaminbilgehan** [comment]
i dont see the SAVE button at all

**Comment by martinjagodic** [comment]
save button appears only in editorial workflow
