### ISSUE TITLE
Content added directly to a markdown file with a text editor does not appear in CMS web portal

### ISSUE THREAD

**Issue by jamesbungay** [decaporg/decap-cms#5735]
**Describe the bug**
I am using Netlify CMS to manage the text/image content of a website (not for a blog). I have added some data directly to a markdown file using a text editor, instead of inputting it into the CMS web portal. This data can then be correctly accessed from the CMS using GraphQL to use in the website, however it does not appear in the web portal of the CMS when you go to edit it.

**To Reproduce**
1. Add data directly to a markdown file, using a text editor.
2. Open web portal.
3. Navigate to the corresponding collection/file. Data is not present in web portal.

**Expected behavior**
Content should appear in the web portal as if it was inputted there directly.

**Screenshots**
<img width="704" alt="Screenshot 2021-08-22 at 12 01 59" src="https://user-images.githubusercontent.com/64200169/130352725-1915d758-a92e-4fee-a69d-c6c4285c60bf.png">
<img width="681" alt="Screenshot 2021-08-22 at 12 02 50" src="https://user-images.githubusercontent.com/64200169/130352726-dd133adb-6c14-4a0a-a96e-df1cb755cc60.png">
<img width="1421" alt="Screenshot 2021-08-22 at 12 03 13" src="https://user-images.githubusercontent.com/64200169/130352728-5175c700-aeee-43b4-a83d-9802bdb72f3b.png">

**Applicable Versions:**

 - Netlify CMS version: 5.10.0
 - Git provider: GitHub
 - OS: MacOS 10.15.5
 - Browser version: Safari 13.1.1 and Firefox 90.0.1 (tested on both)
 - Node.JS version: 15.12.0

**CMS configuration**
<img width="1122" alt="Screenshot 2021-08-22 at 12 06 57" src="https://user-images.githubusercontent.com/64200169/130352818-63a76705-567d-4267-805f-de1186c811c5.png">

**Comment by Asdf0717** [comment]
Hello, we are a group of researchers developing machine learning techniques to locate issues suitable for newcomers, and our model considers this issue as likely a "good first issue". May we recommend you to label it as a "good first issue" so newcomers know where to choose?

Thank you!

**Comment by rohan-kulkarni-25** [comment]
Hey, @jamesbungay @erezrokah  will like to work on these issues and add my contributions.
will like to have guidance from you to get done with this . I am having a windows machine will it work or needs Mac device only ?

**Comment by martinjagodic** [comment]
Closing as stale
