### ISSUE TITLE
Update the SlateJS Editor

### ISSUE THREAD

**Issue by taineriley1** [decaporg/decap-cms#5795]
**Is your feature request related to a problem? Please describe.**

The SlateJS rich text editor currently used in Netlify CMS is at v0.47. This version was released in May 2019, with the current version at v0.61. Although there are several breaking changes involved in updating this, Netlify CMS is now over 2 years behind the current version and it would be great to remove this technical debt.

**Describe the solution you'd like**

Migrate the Slate rich text editor in Netlify CMS to the latest version of SlateJS (greater than v0.61).

**Describe alternatives you've considered**

An alternative rich text editor may be a viable option because upgrading SlateJS is essentially a full rewrite anyway. E.g. QuillJS (https://quilljs.com/)

**Additional context**

**Comment by erezrokah** [comment]
Related to https://github.com/netlify/netlify-cms/issues/5652

**Comment by bytrangle** [comment]
Do we have a singular place for discussing upgrading Slate.js?

**Comment by erezrokah** [comment]
Hi @bytrangle, I link related issues in https://github.com/netlify/netlify-cms/issues/5652, but I think we should use this issue (#5795) for the discussion. WDYT?

**Comment by bytrangle** [comment]
Actually, I like Taine Riley's list of things to consider before upgrading, especially **"Determine whether it is worthwhile updating Slate to the latest version"**.

I recently fixed a bug with Slate the new version and none of things I learned with old Slate was applicable to new Slate. The latter is a new paradigm and I'm not even sure if upgrading Slate or using an alternative will cause the least pain.

I'm fine with either issue, but it'd be great if there is a way to keep Riley's list in the merged discussion.

**Comment by erezrokah** [comment]
> I'm fine with either issue, but it'd be great if there is a way to keep his list in the merged discussion.

💯 

Taine's [issue](https://github.com/SSWConsulting/SSW.Rules/issues/679) is not on the CMS repo so it gets less visibility from the CMS community.

I'm good with copying whatever we think is relevant

**Comment by freesteph** [comment]
This would fix https://github.com/netlify/netlify-cms/issues/5306

**Comment by luksak** [comment]
AFAIK slate hasn't been updated so far.

**Comment by luksak** [comment]
As an alternative there is now also https://editor.stackoverflow.design

**Comment by martinjagodic** [comment]
Solved in Decap 3!
