### ISSUE TITLE
Multi-Select or Single Select Radio & Checkbox Widget

### ISSUE THREAD

**Issue by talmax1124** [decaporg/decap-cms#5838]
In many blogs, there is almost always a group of 2 or more especially when in a big group. I especially need this widget for my team when making blogs. If this could be a feature or if someone has already this implemented, it would be great! Thanks!

**Comment by talmax1124** [comment]
I've Tried the widget from Kaorlis & no luck

**Comment by Sanju3001** [comment]
Hi @erezrokah @talmax1124, I would like to work on this, could you please assign it to me and provide more details? Thanks!
