### ISSUE TITLE
error messages due to failed login are covered by the login button

### ISSUE THREAD

**Issue by amirbey** [decaporg/decap-cms#5904]
**Describe the bug**
When a login is failed, the error message displayed is covered by the login button due to a margin-top: -40px styling on the button.

**To Reproduce**

Steps to reproduce the behavior. For example:
1. Attempt to login to www.example.com/admin  with credentials that will result in an unsuccessful authentication and will return **authorization:github:error:{"message":"Some error message"}** in
```
const script = `
    <script nonce="${res.locals.cspNonce}">
      (function() {
        function receiveMessage(e) {
          window.opener.postMessage(
            'authorization:github:error:{"message":"Some error message"}',
            e.origin
          )
        }
        window.addEventListener("message", receiveMessage, false)
        // Start handshare with parent
        window.opener.postMessage("authorizing:github", "*")
      })()
    </script>
  `;
```

2. You will see:

<img width="789" alt="Screen Shot 2021-10-14 at 10 41 27 AM" src="https://user-images.githubusercontent.com/1261794/137524258-a2353b01-ba9b-4dab-b07a-542bc60ee4f9.png">

**Expected behavior**
Expect to see a visible and unobstructed error message.

<img width="773" alt="Screen Shot 2021-10-14 at 10 32 54 AM" src="https://user-images.githubusercontent.com/1261794/137524330-6f167500-7d41-4b99-b1ef-a2d4c364f581.png">

**Screenshots**
See above

**Applicable Versions:**

 - Netlify CMS version: 2.10
 - Git provider: GitHub

**CMS configuration**
N/A

**Additional context**

**Comment by erezrokah** [comment]
Hi @amirbey, can you share a step by step reproduction, possibly in a public repo?
I'm not able to understand the reproduction steps.

Specifically:
>Attempt to login to www.example.com/admin with credentials that will result in an unsuccessful authentication and will return authorization:github:error:{"message":"Some error message"} 

This points to an example site

Also, I'm not sure in what context the script you shared is executed

**Comment by amirbey** [comment]
I have experienced this when using a Node.js [external oAuth client](https://www.netlifycms.org/docs/external-oauth-clients/) where the callback is called with an error.

Looking at [this example code](https://github.com/vencax/netlify-cms-github-oauth-provider/blob/bad35f2972691acdfb6397377aa656afc4f0b148/callback.js#L51),
this scenario should be created as long as _**mess**_='error'

**Comment by martinjagodic** [comment]
Closing as stale.
