### ISSUE TITLE
Allow concurrent search queries

### ISSUE THREAD

**Issue by medfreeman** [decaporg/decap-cms#597]
**- Do you want to request a *feature* or report a *bug*?**

Feature

**- What is the current behavior?**

At the moment, the code can perform search queries at any point in time through redux store [search `query` action](https://github.com/netlify/netlify-cms/blob/5b502aa68004118d8036d99f14126e998ddc5533/src/actions/search.js#L125-L142).
However, the [`QUERY_SUCCESS` reducer](https://github.com/netlify/netlify-cms/blob/5b502aa68004118d8036d99f14126e998ddc5533/src/reducers/search.js#L53-L60) which handles storing the `queryHits`, will overwrite this object by creating a new one with the latest query results, indexed by `controlID` keys.

That means multiple queries requested at a near point in time would result in potentially only one query result (the last one in time) being available in the store.

The problem was encountered while implementing #591  .

**- What is the expected behavior?**

The [`QUERY_SUCCESS` reducer](https://github.com/netlify/netlify-cms/blob/5b502aa68004118d8036d99f14126e998ddc5533/src/reducers/search.js#L53-L60) should mutate the state by adding the results to the query object, indexed by `controlID` keys, instead of rewriting the entire object.

NB: ~~what's written here is also applicable to the other exported search actions and reducers (i.e `searchEntries`)~~

**Comment by erquhart** [comment]
Note: Mehdi ran into this because the relation widget and the primary CMS search bar share actions, reducers, and state.

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
