### ISSUE TITLE
Failed seeing “Deploy preview links” in the editor toolbar

### ISSUE THREAD

**Issue by EmmetZC** [decaporg/decap-cms#5975]
**Describe the bug**
I created a Hugo Site Starter and cannot see Deploy Preview Links after editing one of the posts.

**To Reproduce**
1. Deploy site to Netlify with one click in page [Start with a Template](https://www.netlifycms.org/docs/start-with-a-template/)
![image](https://user-images.githubusercontent.com/6105862/141124135-80ce6267-c210-4870-88f6-187ac815b0a3.png)
2. Waiting for deployment to finish
3. open https://netlify.vspirit.cn/admin/ (aka the site netlify created for me, while `vspirit.cn` is my own domain) and edit any of the pages.

**Expected behavior**
According to [Deploy Preview Links](https://www.netlifycms.org/docs/deploy-preview-links/)
I should have seen a link called "view preview" like image below, which I didn't.
![](https://www.netlifycms.org/img/preview-link-unpublished.png)

**Screenshots**
No "view preview" button found.
![image](https://user-images.githubusercontent.com/6105862/141124688-a9d58dcb-1b83-4210-ae37-451aa09b5e17.png)

**Applicable Versions:**
You may see them directly from the repo you created for me:
https://github.com/EmmetZC/one-click-hugo-cms

**Comment by EmmetZC** [comment]
I guess there might be some steps I missed or you missed in the document. Thus I'd rather mark this issue as `help wanted` than `bug` but didn't find that option.

**Comment by martinjagodic** [comment]
Closing as stale. To ask for help please open a [discussion](https://github.com/decaporg/decap-cms/discussions/new/choose) or join us on [Discord](https://decapcms.org/chat)
