### ISSUE TITLE
Error in docs, cannot submit fix via the CMS

### ISSUE THREAD

**Issue by usernamenumber** [decaporg/decap-cms#6120]
## Docs issue
I believe there is an error in the [docs for `registerwidget`](https://www.netlifycms.org/docs/custom-widgets/#registerwidget). It lists the arguments `control` and `preview`, but it looks like it's actually `controlComponent` and `previewComponent` ([example](https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-widget-text/src/index.js))

## CMS issue
I tried twice to submit a fix using the "Edit this page" link at the top of the docs but encountered two problems:

1. Even though the url looks like it should have linked me directly to the editor for the custom widgets page, I instead ended up at the root of `/admin` and had to navigate my way to the page
2. When I tried to submit my fix, I only had a save button, and when I tried to use it I got an API error, shown below

![image](https://user-images.githubusercontent.com/188349/149334360-ff2e63b1-c666-4adf-a556-911797df894e.png)

**Comment by martinjagodic** [comment]
Closing as stale.
