### ISSUE TITLE
Netlify CMS: Git Gateway error

### ISSUE THREAD

**Issue by im-coder-lg** [decaporg/decap-cms#6172]
**Describe the bug**
This is a dupe, but I need some quick help. Git Gateway fails in my CMS.

**To Reproduce**
I don't know. This affects only me.

**Expected behavior**
I am supposed to get in

**Screenshots**
Need to do this soon

**Applicable Versions:**

 - Netlify CMS version: 2.10
 - Git provider: GitHub
 - OS: [e.g. Windows 7] It is Windows 7
 - Browser version Vivaldi 5

 - Node.JS version: 16

**CMS configuration**

https://github.com/im-coder-lg/docusaurus-blog/blob/main/static/admin/config.yml

**Additional context**

Can I allow select users, ie. only me to authenticate via GitHub Auth? If yes, then how? I want my CMS to be secure, so that others can't log in and edit the content inside it.

**Comment by erezrokah** [comment]
Hi @im-coder-lg, do you mind adding the missing parts of the issue template. Specifically the error you're getting and the steps you took to set up the CMS?
That makes it much easier to solve the problem.

Regardless, you probably want to update your branch configuration from `master` to `main` here https://github.com/im-coder-lg/docusaurus-blog/blob/b9e089eb094d2bec5b01d5144072780fab51fcb8/static/admin/config.yml#L3

**Comment by im-coder-lg** [comment]
I will do it soon, I am going to be busy for now.

**Comment by martinjagodic** [comment]
Closing as stale.
