### ISSUE TITLE
Require all fields in components in markdown widget

### ISSUE THREAD

**Issue by marceleq27** [decaporg/decap-cms#6326]
Hi, is there a way to require fields (for ex. alt, title and img in image component) in markdown widget?

**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Maybe prop in config?
```
 - {
          label: "Bio",
          name: "bio",
          widget: "markdown",
          pattern: ["^.{1,300}$", "Maximum length exceeded"],
          required_component_fields: true
   }
```

**Describe alternatives you've considered**
Custom component, but is it necessary?

**Additional context**
N/A

**Comment by erezrokah** [comment]
Hi @marceleq27, do you mind filling all the fields from https://github.com/netlify/netlify-cms/issues/new?assignees=&labels=type%3A+feature&template=feature_request.md&title=Please+replace+with+a+clear+and+descriptive+title?

I'm having a hard time understanding this feature request.

Is it about requiring that an editor component will be a part of the Markdown? For example if you have a Youtube editor component, each markdown should have at least 1?

**Comment by marceleq27** [comment]
Hmm, let me explain it better. 

Right now if you are writing for ex. blog post in markdown widget, you can save file even if you have empty fields in Image. I want to make this fields required.

![image](https://user-images.githubusercontent.com/51132547/160134778-be1e9e96-b86d-47ff-a4e7-948c381b3c36.png)

**Comment by marceleq27** [comment]
Hi, yes, kinda, solution is simple - migrate to Storyblok :D

**Comment by martinjagodic** [comment]
Closing as stale.
