### ISSUE TITLE
Publish button not responsive in other languages

### ISSUE THREAD

**Issue by adorebo** [decaporg/decap-cms#6355]
**Describe the bug**
In the CMS, when publishing, the dropdown coming from the "publish" button appears unresponsive, and text is cropped inside the 3 choices if we change the locale (at least in French, but I expect others too).

**To Reproduce**
Steps to reproduce the behavior :
1. Change locale of the CMS to French " locale: 'fr' " in config.yml
2. Go to publish a post with the CMS
3. Click on "Publish"
4. You get that ↓
![image](https://user-images.githubusercontent.com/47522397/161058949-1c03f2bd-4c7e-4276-9fde-78795db85507.png)

**Expected behavior**
The dropdown could be responsive and adapt its width to its content, or having a bigger min-width to cover all cases.
![image](https://user-images.githubusercontent.com/47522397/161059369-9f92f5ca-5d43-4f1c-81f1-8f2c9b2db312.png)

**Applicable Versions:**
 - Netlify CMS version: netlify-cms-app 2.15.70 netlify-cms-core 2.55.0 netlify-cms 2.10.190
 - Git provider: GitHub
 - OS: Windows 10
 - Browser version Firefox 92.02

**CMS configuration**
locale: 'fr'
logo_url: /images/Element.png
backend:
  name: git-gateway
  branch: main
media_folder: "static/images/uploaded" 
public_folder: "images" 
collections:
....

I think this can be solved without too much hassle, just wanted to put it out there, 
feels janky for the client, but no big deal, just *aesthetics* and overall sleekness.

Thanks for your time and bravo, awesome tool !

**Comment by ghughes13** [comment]
Mind if I take this?
