### ISSUE TITLE
Use official widgets as child component in a new Widget ?

### ISSUE THREAD

**Issue by laurent-d** [decaporg/decap-cms#6369]
Hi,

Thanks for the amazing job done with Netlify CMS !!!
I try to develop a widget to manage art direction layout blocks.

I'm facing a big wall : 
Is there an easy way to implement or re-use The Netlify file uploader in my widget as child component ?
Or to do this i need to make a kind of nested container ?
Or is it not possible by design and i have to recode it ?

Before posting this question, i made a big search to on Documentations, Github issues and Forum community without any result :/

Picture is better than a long speech, what i'm working on :

https://user-images.githubusercontent.com/6553086/161732478-07332afa-e7ec-4da0-8316-9314bf7261d5.mov

Thanks if you reading this and have a good day :)

**Comment by martinjagodic** [comment]
I'm closing this as it is a question rather than an issue. If you need more help, please start a [discussion](https://github.com/decaporg/decap-cms/discussions/new/choose) or join us on [Discord](https://decapcms.org/chat).
