### ISSUE TITLE
Netlify CMS dev-mode

### ISSUE THREAD

**Issue by alolalo** [decaporg/decap-cms#6371]
I'm using Netlify CMS and moving a blog over to it, and what is really annoying is the login time-out. It is set too tight and when you're working with larger files you often move away from it for bit.

This resets your blog-post because the recovery feature that stores a back-up, doesn't have any versioning that can make me see what it recovered. It's usefull, but not in the sense of accuracy. 

**Describe the solution you'd like**

I would like either the time-out to be a user setting, or there is a "dev-mode" setting that disables the time-out when in CMS-mode. The first is done in the config.yml, the latter solution in the UI

**Describe alternatives you've considered**

Creating a crawler that acts like I'm actually on the website

**Additional context**

![image](https://user-images.githubusercontent.com/48421977/162145218-2598b8b0-8257-4f8f-a63f-6e909d169078.png)

**Comment by martinjagodic** [comment]
Closing as stale
