### ISSUE TITLE
netlify-cms-app.js:54 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'filter')

### ISSUE THREAD

**Issue by nolafs** [decaporg/decap-cms#6462]
**Describe the bug**
All forms working fine on local development stack but on live CMS, creating new collections throws an error and does not display any fields at all. Previous created content, shows all the fields perfectly fine. It seems it only effects the new view.

**To Reproduce**
I have no idea but I am getting the following error and the page stays on loading.

Using config file path: "https://luxury-marzipan-bd9173.netlify.app/admin/config.yml"
netlify-cms-app.js:54 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'filter')
    at listFiles (netlify-cms-app.js:54:81030)
    at async Promise.all (index 0)
    at async V.processEntry (netlify-cms-app.js:34:37125)
    at async netlify-cms-app.js:34:46856

```
const news = {
    name: "news",
    label: "News",
    label_singular: "News Article",
    description: "News collection",
    show_preview_links: true,
    folder: "site/content/news",
    path: '{{slug}}/index',
    //filter: { field: "hidden", value: false },
    summary: "{{title}} - {{day}}/{{month}}/{{year}}",
    //sortable_fields: [ 'news/categories' ],
    //media_folder: "" ,
    //public_folder: "",
    create: true,
    editor: {
        preview: false
    },
    fields: [
       // { label: "lfs", name: "lfs", widget: "hidden", default: false },
       // { label: "hasRelations", name: "hasRelations", widget: "hidden", default: true },
        //{ label: 'summary_button', name: 'summary_button', widget: 'hidden', default: "Read more" },
        {
            label: "Title",
            name: "title",
            widget: "string"
        },
        //...meta,
        //categories('news'),
        //tags('news'),
        //featureImage,
        {
            label: "Body",
            name: "body",
            widget: "markdown"
        },
        //...seo
    ],
}
```
When i remove  path: '{{slug}}/index' it works again. Something not quite working with path settings.

**Comment by martinjagodic** [comment]
Closing as stale
