### ISSUE TITLE
Custom Widgets not working with current version of Netlify CMS v2

### ISSUE THREAD

**Issue by mrkaluzny** [decaporg/decap-cms#6467]
Custom Widgets when build as separate packages for npm are resulting in React errors (while working great when they are decalread within the project). 

**Is your feature request related to a problem? Please describe.**
Current situation prevents developers from easily reusing the same custom widgets across different projects and sharing them with community. We need a better way to grow the CMS 

**Solution**
- Create new starter template for custom widgets,
- Update the documentation,

**Comment by martinjagodic** [comment]
Closing as stale
