### ISSUE TITLE
The template "Next.js Blog Template" failed to be deployed into Netlify

### ISSUE THREAD

**Issue by chengjianhua** [decaporg/decap-cms#6472]
**Describe the bug**
The template "Next.js Blog Template" failed to be deployed into Netlify after clicking the button "Deploy to Netlify".

https://www.netlifycms.org/docs/start-with-a-template/

**To Reproduce**
1. Visit https://www.netlifycms.org/docs/start-with-a-template/

2. Click the "Deploy to Netlify" button that is under Template "Next.js Blog Template"

3. The deployment on Netlify failes
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/10795207/168456656-6e043dc3-ddd3-4b52-b974-5b7c7a28f8cb.png">

**Expected behavior**
Deployment succeeds.

**Screenshots**
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/10795207/168456670-da90e182-4c21-4edd-98f0-eaf7340b8a65.png">
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/10795207/168456677-12d1bc4e-2c94-4134-9f9c-ae2a8a77db49.png">

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

**Additional context**

**Comment by skylerstyron** [comment]
I am running into the same issue.

**Comment by arctekdev** [comment]
set `NETLIFY_NEXT_PLUGIN_SKIP` to `true` in your site settings > Build & Deploy > Environment variables

**Comment by martinjagodic** [comment]
This repo is intended for Decap CMS-related issues.

For Netlify build-related issues I suggest reaching out in the forums: [https://answers.netlify.com/](https://answers.netlify.com/)

Closing the issue, and please comment if you have any other questions.
