### ISSUE TITLE
Document i18n "single_file" format & map widget format

### ISSUE THREAD

**Issue by ewjoachim** [decaporg/decap-cms#6477]
**Is your feature request related to a problem? Please describe.**
When writing one's config.yml, it can be frustrating not to be able to tell what format Netlify CMS will read/write. The only way to really know is to push a commit, wait for it to build and then make a change in draft, and look at the PR, whereas local development would allow getting the answers much faster.

This is especially true for non-obvious formats such as:
- In i18n, when choosing `single_file`, what format will the yaml have ? Are the untranslated fields in the default language or not in a language at all ?
- In the map widget, it's documented that the output is a geojson payload: is it the object directly in the yaml or a json dump that needs to be loaded ? Does it include the `type/property/geometry` keys or is it only the content of the `geometry` key ?

**Describe the solution you'd like**
2 solutions come to mind:

- When saving in `test_repo` mode, somehow show what would be saved (maybe just in console.log, but it's already enough)
- Or just simply document with a full example whenever what NetlifyCMS will write is not obvious (... or even when it's obvious)

**Additional context**
N/A

**Comment by airtonix** [comment]
Instead of writing it in YAMl, use typescript, where you'll get errors if you go off-pist

**Comment by airtonix** [comment]
The alternative is to actually ask for this: https://github.com/netlify/netlify-cms/issues/6635

**Comment by ewjoachim** [comment]
maybe my ticket wasn't clear, but your answers don't seem to match what I was requesting.

Netlify CMS is a tool that provides a UI for reading and writing content as markdown & yaml files for you. There's a configuration file that tells you how it should read and write files. What I'm unsure of is not how to fill the yaml configuration file, but how the configuration will impact the way Netlify CMS writes the content markdown & yaml files for me. For example, if I tell Netlify CMS to write a `geojson` payload, there may still be quite a lot of possible ways to encode some information, and I was requesting for a way to know in advance, whether this be through documentation of the output, or with a way to easily run netlify-cms locally where I can just do the change in the Web UI and check how Netlify CMS processed the corresponding file.
