### ISSUE TITLE
Feature: Trigger notification when items are moved to "Waiting for Review"

### ISSUE THREAD

**Issue by verythorough** [decaporg/decap-cms#648]
**- Do you want to request a *feature* or report a *bug*?**
Feature 

**- What is the current behavior?**
In the editorial workflow, moving an item into the "Waiting for Review" column adds some metadata to keep the item in that column of the UI, but it doesn't really do anything else.

**- What is the suggested behavior?**
It would be cool if this could trigger a notification of some kind. Possibly just a webhook to an address specified in the config, so users can have it send to slack, handle it with Zapier, etc.

**Comment by erquhart** [comment]
Webhook triggers in general would be a great thing.

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
