### ISSUE TITLE
New Editor: Undo must be pressed multiple times when changing block types.

### ISSUE THREAD

**Issue by tech4him1** [decaporg/decap-cms#655]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
If a block is removed with (Ctrl+Z), the editor loses focus. Then, if you click in the editor so that it regains focus, you will need to press undo (Ctrl+Z) *twice* to undo the next thing in the undo history.

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Make some changes (like in a regular paragraph).
2. press enter (make a new line), and enter some text there.
3. convert that new line of text to a H1 or a code block
4. do an undo (ctrl+Z). The text will be converted back to a paragraph (correct).
5. **press undo a second time. Nothing happens (incorrect).**
6. press undo a third time. the undo now works correctly and remove the text.

**- What is the expected behavior?**
you should only have to press undo once for each change

**- Please mention your CMS, node.js, and operating system version.**

0.5.0-beta

**Comment by erquhart** [comment]
I think I remember Slate's rich text example doing this before, but it doesn't anymore: http://slatejs.org/#/rich-text

We're reimplementing undo/redo for some reason, even though it's handled out of the box by Slate. There was a reason for this, but I also remember finding that Slate may have made that reasoning obsolete. I should really start writing things down more.

So we should:
* Try removing our undo/redo implementation and see if Slate can just handle things now
* If that doesn't work, follow the example linked above and adopt whatever they're doing

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
