### ISSUE TITLE
markdown editor is buggy on Google Chrome

### ISSUE THREAD

**Issue by marques-kevin** [decaporg/decap-cms#6553]
As you can see in the video, when I want to update the content, the cursor go to the end of the sentence. It makes the editor impossible to use when you intend to update the content.

https://user-images.githubusercontent.com/8655434/190159991-eb95fdd1-1e04-489a-91d2-c95e1c0cd161.mp4

The bug does not appear in Safari, but is present in Google Chrome (Mac)

Chrome Version: Version 105.0.5195.102 (Build officiel) (x86_64)

**Comment by tonyshearer** [comment]
@marques-kevin check out https://github.com/netlify/netlify-cms/issues/5092

**Comment by ValdoGhafoor** [comment]
Same here, with both Markdown & rich text editors

**Comment by sawilde** [comment]
I can confirm that the (temporary?) fix mentioned above works

**Comment by martinjagodic** [comment]
Solved in Decap 3
