### ISSUE TITLE
2 Issues: Cursor jumping to end of text line; strange character inserted after first character in new text line

### ISSUE THREAD

**Issue by TownCloudDev** [decaporg/decap-cms#6556]
This issue is similar to https://github.com/netlify/netlify-cms/issues/4539

**Issue 1:**
Using Chrome (106.0.5249.30) or Edge (105.0.1343.33) browsers, when editing an existing line of text, if the cursor is placed anywhere except for the end of the text line, after typing the first character, the cursor jumps to the end of the line making it very difficult to edit existing text. This does not appear to be an issue in Firefox (105.0 (64-bit))

**Issue 2**
Additionally, it appears that a special UTF character is being inserted into the text string which is not visible from the Netlify CMS editor but is flagged by the editor as a misspelled word and visible as a special character when inspecting the changes in VS Code. This was discovered because the first word typed in every line showed as as misspelled word even when it was not.

![image](https://user-images.githubusercontent.com/16582173/190508751-c1f31263-67db-448c-aa50-399899c13fb9.png)

![image](https://user-images.githubusercontent.com/16582173/190508852-1ec501e7-6426-481b-b284-e60b85a58f77.png)

**Comment by TownCloudDev** [comment]
We're unsure if these 2 bugs are related or not so we've logged them together.

**Comment by wing5wong** [comment]
issue 1 related #6557

Also noting some strange characters but havent looked into this yet, just discovered after looking at this issue
![image](https://user-images.githubusercontent.com/4406993/190928584-421083c0-0e09-4a53-bc33-abea08f913c1.png)

**Comment by chris-haywood** [comment]
[Cursor jumps to end of editorComponent text field in v2.10.97 #5092](https://github.com/netlify/netlify-cms/issues/5092)

**Comment by martinjagodic** [comment]
Solved in Decap 3
