### ISSUE TITLE
Nested collections root index.md issue

### ISSUE THREAD

**Issue by ryangittings** [decaporg/decap-cms#6567]
Hi all,

When using Nested Collections with 11ty, and a larger site, the root `index.md` file takes an age to save. 

Upon investigation, it seems as when triggering a publish, it sends a `POST` request to `/.netlify/git/github/git/trees`, which includes a payload of a tree of every file on the same level as that root `index.md` (which is the whole site).

This obviously is a standard setup for sites using 11ty, but wondered if this was a bug. Obviously, as a workaround I can move the root `index.md` file to a subfolder, and change the permalink, but then the client loses control of the `path` within Netlify.

Any advice is much appreciated - thanks!

**Comment by martinjagodic** [comment]
Closing as stale

**Comment by ryangittings** [comment]
I have come across this issue again today - just an FYI.

**Comment by martinjagodic** [comment]
@ryangittings ok, reopening.
