### ISSUE TITLE
Github API returns 502 when fetching resources

### ISSUE THREAD

**Issue by nick-mon1** [decaporg/decap-cms#6570]
**Describe the bug**

When logging into `netlify-cms` and loading github api request the response returns a 502 with error code `C084:58C5:1747A26:2F86499:6334A643`.
It takes several page requests to successfully load.

```
{
   "data": null,
   "errors":[
      {
         "message":"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `C084:58C5:1747A26:2F86499:6334A643` when reporting this issue."
      }
   ]
}
```

**To Reproduce**
1. Log in to netlify cms
2. Wait for resources to load

**Expected behavior**
Should not throw an error and load the resources

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: Mac OS X 12.3.1
 - Chrome Version 106.0.5249.91 (Official Build) (x86_64)

 - Node.JS version:

**CMS configuration**
Cannot provide

**Comment by martinjagodic** [comment]
Closing as stale
