### ISSUE TITLE
The editor removes emojis

### ISSUE THREAD

**Issue by 1alexvash** [decaporg/decap-cms#6572]
![Animation](https://user-images.githubusercontent.com/46556479/194720162-61ad517d-7b0a-496c-8b66-229c23c3dfba.gif)

**Comment by 1alexvash** [comment]
There was another issue created about it 4 years ago, and it's not resolved, not to say this feature is annoying as hell, and enough to consider moving from Netlify CMS to some other platform.

Is it even supported nowadays?

**Comment by whiver** [comment]
Looks like the bug still repro. Please keep this issue open.

**Comment by whiver** [comment]
I still repro the issue, using Firefox. I can add an emoji, but whatever I do after (type anything, switch to markdown view or simply save the page) removes the emoji:

![Animation](https://github.com/decaporg/decap-cms/assets/394565/e86fcd4c-286b-4e21-b885-b650c7394957)

I'm using latest version 2.10.192.

**Comment by martinjagodic** [comment]
@1alexvash @whiver it seems that the issue is solved in Decap 3.0, can you confirm?

**Comment by 1alexvash** [comment]
Sorry, I no longer use Netlify CMS, so I can't confirm
