### ISSUE TITLE
Unable to add global styles to Preview Template in NextJS

### ISSUE THREAD

**Issue by JWesorick** [decaporg/decap-cms#6575]
**Describe the bug**
Netlify CMS template previews have no styling when using NextJS and TailwindCSS.

**To Reproduce**

I have added Netlify CMS to my NextJS site, including preview templates (as described in [this post](https://www.manuelkruisz.com/blog/posts/custom-previews-nextjs-netlifycms).) My NextJS site is styled with TailwindCSS and is included as described [here.](https://tailwindcss.com/docs/guides/nextjs)

My issue is that the Tailwind styles are not included in the iframe Neltify CMS makes for previewing. Trying to include the css again in those preview components results in this error message: 

`
./styles/global.scss
Global CSS cannot be imported from files other than your Custom <App>. Due to the Global nature of stylesheets, and to avoid conflicts, Please move all first-party global CSS imports to pages/_app.js. Or convert the import to Component-Level CSS (CSS Modules).
Read more: https://nextjs.org/docs/messages/css-global
Location: pages/index.js
`

**Expected behavior**
Netlify CMS template previews are styled with the same styles as the live site.

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: 2.15.72
 - Next version: 12.3.1
 - Tailwind CSS: 3.1.8

 - Node.JS version: 17.0.1

**CMS configuration**

**Additional context**

As a workaround I am able to use this higher order component to wrap each preview template.

```js
const withGlobalStyles = (Component) => {
  return (props) => {
    useEffect(() => {
      const cssLinkElement = document.querySelector(
        process.env.NODE_ENV === "development"
          ? "head style"
          : "link[rel=stylesheet]",
      );

      props.document
        .querySelector("head")
        .appendChild(cssLinkElement.cloneNode(true));
    }, []);

    return <Component {...props} />;
  };
};
```

**Comment by martinjagodic** [comment]
Closing as stale
