### ISSUE TITLE
Jumping input cursor to end of text in markdown widget

### ISSUE THREAD

**Issue by NedelevPhilip** [decaporg/decap-cms#6580]
When I try to add some text in the middle of the text, enter one symbol, and after that input cursor jumps to the end of the text
![image](https://user-images.githubusercontent.com/17813909/196791966-28742185-8c3e-4659-b71e-8d5c6c5f8fee.png)

 - Netlify CMS version: 2.15.65
 - Git provider: GitHub
 - Browser version Chrome  106.0.5249.119

**CMS configuration**
- { label: "Answer", name: "answer", widget: "markdown" }

**Comment by matthewjumpsoffbuildings** [comment]
I am also seeing this issue, very irritating

**Comment by svvimming** [comment]
Same here

**Comment by izzudd** [comment]
I also experiencing this weird behavior. Found the workaround in [#5092](https://github.com/netlify/netlify-cms/issues/5092).

Simply just add this style to the head of `index.html`

```html
<style>
    [data-slate-editor] { 
        -webkit-user-modify: read-write !important; 
    }
</style>
```

Can confirm it works, at least for me.

**Comment by matthewjumpsoffbuildings** [comment]
that does indeed fix it for me too, though this hardly should be necessary right???

**Comment by NedelevPhilip** [comment]
> I also experiencing this weird behavior. Found the workaround in [#5092](https://github.com/netlify/netlify-cms/issues/5092).
> 
> Simply just add this style to the head of `index.html`
> 
> ```
> <style>
>     [data-slate-editor] { 
>         -webkit-user-modify: read-write !important; 
>     }
> </style>
> ```
> 
> Can confirm it works, at least for me.

[here](https://answers.netlify.com/t/change-admin-css-to-tweak-a-bit-the-cms-ui-defaults/17835/2) is solution how add styles with Gatsby + Netlify CMS

**Comment by matthewjumpsoffbuildings** [comment]
@NedelevPhilip why close this though? It's still a bug and needs to be fixed on netlify's end, instead of this workaround

**Comment by jaapaurelio** [comment]
I also have this behaviour in my Netlify CMS. I found this issue in other pages, as Reddit for example. Looks like some new weird browser behaviour.

**Comment by benseven** [comment]
Client facing this issue on current site build too.
netlify-cms-app 2.15.72
netlify-cms-core 2.55.2
netlify-cms 2.10.192

https://share.cleanshot.com/KLYz5zc0

**Comment by domino14** [comment]
this is still a bug as of right now. Please re-open?

**Comment by benseven** [comment]
> this is still a bug as of right now. Please re-open?

It is open?

**Comment by kaicianflone** [comment]
I was able to fix this in netlify-cms & gatsby by following the instructions in @NedelevPhilips post above

**Comment by casimiroarruda** [comment]
When I apply this fix, I get some buggy behavior when adding accented characters (such as `á`) accents on mac (not tested yet on windows)

**Comment by martinjagodic** [comment]
Fixed in Decap 3
