### ISSUE TITLE
Admin page appearing in Google search as default

### ISSUE THREAD

**Issue by simoncox** [decaporg/decap-cms#6616]
**Describe the bug**
Admin page appearing in Google search for many sites.

**To Reproduce**
1. Go to google.com 
2. Search for ["Login with Netlify Identity" ](https://www.google.com/search?q=%22Login+with+Netlify+Identity%22)
3. Scroll down the results and you start to see many instances of /admin for sites

**Expected behaviour**
For /admin not to appear in search results as the default

**Additional context**
Can I suggest that `<meta name="robots" content="noindex">` is added to the code example at [Add to Your Site | Netlify CMS | Open-Source Content Management System](https://www.netlifycms.org/docs/add-to-your-site/) and admin/index.html  as the default. If someone wants their /admin to be indexed (who/why?) they can take this line out.

**Comment by hound77** [comment]
@simoncox I am new to open source. can I work on this issue

**Comment by simoncox** [comment]
> 

I don't mind who works on it - I just flagged the issue with the docs!
