### ISSUE TITLE
I would like to have a map widget with address input

### ISSUE THREAD

**Issue by koraysels** [decaporg/decap-cms#6629]
**Is your feature request related to a problem? Please describe.**

Right now the map input widget is great but it requires the user to zoom into and pick the location based on topographical knowlege. Itwould be great if there was an inputfield with geocoding to translate that address to a point on the map. That way we could use the map still for finetuning the exact position but it would be much easier and faster to input address location. This is how for example ACF does it in wordpress

**Describe the solution you'd like**

Add an address field to the map widget that uses geocoding to determine the ppin position in the displayed map.

**Describe alternatives you've considered**

Alternatively you could say just use a text field for the address and parse it in your application, but that makes it vulnerable to errors. Also less precise. 

**Additional context**

I am building a map wth locations in a city and it is very cumbersome to have the client put in an address and a GeoPoint using the map widget.

**Comment by abdullaharik** [comment]
Maybe you can use this;

https://www.npmjs.com/package/netlify-cms-widget-gmaps

**Comment by koraysels** [comment]
> Maybe you can use this;
> 
> https://www.npmjs.com/package/netlify-cms-widget-gmaps

Cool! but it does no tseem to work out of the box. 

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms@2.10.192`
 - Git provider: `test-repo`
 - Browser version: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36`

```
ReferenceError: google is not defined at i.value (https://unpkg.com/netlify-cms-widget-gmaps@%5E1.0.0:2:267771) at Fa (https://unpkg.com/netlify-cms@%5E2.0.0/dist/netlify-cms.js:188:69876) at Na (https://unpkg.com/netlify-cms@%5E2.0.0/dist/netlify-cms.js:188:69671) at gs (https://unpkg.com/netlify-cms@%5E2.0.0/dist/netlify-cms.js:188:105470) at ul (https://unpkg.com/netlify-cms@%5E2.0.0/dist/netlify-cms.js:188:96717) at sl (https://unpkg.com/netlify-cms@%5E2.0.0/dist/netlify-cms.js:188:96642) at Js (https://unpkg.com/netlify-cms@%5E2.0.0/dist/netlify-cms.js:188:93672) at https://unpkg.com/netlify-cms@%5E2.0.0/dist/netlify-cms.js:188:45314 at t.unstable_runWithPriority (https://unpkg.com/netlify-cms@%5E2.0.0/dist/netlify-cms.js:196:3844) at qi (https://unpkg.com/netlify-cms@%5E2.0.0/dist/netlify-cms.js:188:45023)
```

**Comment by airtonix** [comment]
@koraysels so because this uses `react-google-maps`, the docs for that say at step-3: 

https://tomchentw.github.io/react-google-maps/

> If you don't use withScriptjs, you have to put a <script/> tag for [Google Maps JavaScript API v3](https://developers.google.com/maps/documentation/javascript/) in your HTML's <head/> element

**Comment by airtonix** [comment]
example https://codesandbox.io/s/2xyw6n4o9y (probably need to update with your own valid api key)

**Comment by martinjagodic** [comment]
Closing as stale
