### ISSUE TITLE
"Insert from URL" not working in Firefox

### ISSUE THREAD

**Issue by pgooch** [decaporg/decap-cms#6632]
**Describe the bug**
The "Insert from URL" button on the image and file uploads does now work in Firefox.

**To Reproduce**
- Create a collection with an image or URL
- Click the "Insert from URL" button in firefox

**Expected behavior**
It to allow some method of inserting a URL

**Applicable Versions:**
 - Netlify CMS version: 2.15.72
 - OS: Mac OS 12.3.1
 - Browser version: Firefox 108.0.1

**CMS configuration**
backend:
  name: git-gateway
  branch: master

local_backend: true

media_folder: "src/cms/images"

collections:
  - name: movie
    label: Movie
    folder: src/cms/data
    create: true
    fields:
      - { label: 'TEST', name: 'test', widget: 'image'}

**Additional context**
If you upload a file and press "Replace with URL" it will clear the image but the prompt never shows.

**Comment by Paguiar735** [comment]
> **Describe the bug** The "Insert from URL" button on the image and file uploads does now work in Firefox.
> 
> **To Reproduce**
> 
>     * Create a collection with an image or URL
> 
>     * Click the "Insert from URL" button in firefox
> 
> 
> **Expected behavior** It to allow some method of inserting a URL
> 
> **Applicable Versions:**
> 
>     * Netlify CMS version: 2.15.72
> 
>     * OS: Mac OS 12.3.1
> 
>     * Browser version: Firefox 108.0.1
> 
> 
> **CMS configuration** backend: name: git-gateway branch: master
> 
> local_backend: true
> 
> media_folder: "src/cms/images"
> 
> collections:
> 
>     * name: movie
>       label: Movie
>       folder: src/cms/data
>       create: true
>       fields:
>       
>       * { label: 'TEST', name: 'test', widget: 'image'}
> 
> 
> **Additional context** If you upload a file and press "Replace with URL" it will clear the image but the prompt never shows.

Can you check if this problem happens in other browsers?

**Comment by martinjagodic** [comment]
This works in Decap 3
