### ISSUE TITLE
Why netlify cms allows to publish/save entries with same identifier_field. but adds -1, -2, -3 at the end of file??

### ISSUE THREAD

**Issue by Git-I985** [decaporg/decap-cms#6633]
**Bug**
Why i can create two entries with SAME identifier_field and it will allow me to do this without giving any errors or warnings, i cant create two entries with same ID in my database, why i can do it here? NetlifyCMS just add -1, -2, ... postfix for my .json file. How to setup validation for this? 

**Reproduce**
Create two entries with SAME identifier_field and it will allow you to do this without giving any errors or warnings

**Expected behavior**
I would like to be able to prevent such behavior in the cms config, and show a warning to the user when he trying to create several entities with the same identifier, and not just silently save a file with a different filename

**Screenshots**
![image](https://user-images.githubusercontent.com/54438967/209558141-f6a6ebc3-50b4-4243-b383-68b78d7bce34.png)
![image](https://user-images.githubusercontent.com/54438967/209558241-5ecc33f8-86b9-4938-bcb7-8e994e0ce03d.png)

**Applicable Versions:**

 - Netlify CMS version: ^2.15.72
 - Git provider: proxy/netlify-cms-proxy-server
 - OS: MacOS 13.0.1
 - Browser version Chrome 108

 - Node.JS version: 16.13

**CMS configuration**
```
{
    backend: {
        name: 'proxy',
        proxy_url: "http://localhost:8081/api/v1",
        branch: "master"
    },
    local_backend: true,
    media_folder: 'static/img',
    public_folder: '/img',
    collections: [
        {
            name: 'page',
            label: 'Page',
            folder: '_netlify-cms-data/pages',
            identifier_field: 'id',
            create: true,
            extension: 'json',
            format: 'json',
            editor: {
                preview: false,
            },
            summary: 'ID: {{fields.id}}',
            slug: '{{fields.id}}',
            fields: [
                {
                  hint: 'id',
                  label: 'id',
                  name: 'id',
                  widget: 'string'
              }
            ],
        },
    ],
}
```

**Additional context**
Gatsby netlify cms plugin

**Comment by martinjagodic** [comment]
Closing as stale. identifier_field is not a Decap feature.
