### ISSUE TITLE
provide json schema definition for config.yml

### ISSUE THREAD

**Issue by airtonix** [decaporg/decap-cms#6635]
**Is your feature request related to a problem? Please describe.**

as a developer
when I edit the `config.yml`
and I make changes incompatible with netlifycms
I want my editor to make me aware of the invalid changes and why they're invalid.

**Describe the solution you'd like**

Provide a hosted jsonschema over at https://www.schemastore.org/json/

**Describe alternatives you've considered**

- Spend the rest of my life continually pressing `F5` on the netlifycms github page and analysing all possible code changes that might create changes to a valid config. 🤮 
- rely on runtime errors 🤮 

**Additional context**

**Comment by martinjagodic** [comment]
A schema exists: https://json.schemastore.org/netlify.json

It's possible that it's outdated or incomplete. I anyone willing to check it out?

**Comment by martinjagodic** [comment]
Closing as stale
