### ISSUE TITLE
Unable to deploy Netlify CMS in self hosted server (AWS ec2)

### ISSUE THREAD

**Issue by mvraja** [decaporg/decap-cms#6655]
I am new to this netlify CMS. I want to deploy cms in aws ec2 instance. I followed some of the tutorials which gave idea about deployment. But am not able to open cms in my own server. I have created oAuth in github too. I have provided it as env file in aws. But yet am not able to succeed. Could anyone give me suggestions?

**Comment by danurbanowicz** [comment]
Netlify CMS is a clientside React app i.e. it runs in the browser. How and why would you deploy it to an EC2 instance?

Maybe you could close this issue if you have already figured this out, or remove the bug label? Thanks!

**Comment by martinjagodic** [comment]
Not an issue
