### ISSUE TITLE
Starter template creates empty repository

### ISSUE THREAD

**Issue by gtirloni** [decaporg/decap-cms#6662]
**Describe the bug**

https://www.netlifycms.org/docs/start-with-a-template/ Hugo starter template
**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

**Additional context**

**Comment by ghughes13** [comment]
Seems to work, just ran the 'hugo' starter template and it generated this - https://github.com/ghughes13/one-click-hugo-cms

**Comment by martinjagodic** [comment]
Solved by @ghughes13. @gtirloni if you want help with this, please ask for help in `#support` channel on [Discord](https://decapcms.org/chat)
