### ISSUE TITLE
NetlfyCMS requires updating to React 18 to work in production with latest Nextjs

### ISSUE THREAD

**Issue by nolafs** [decaporg/decap-cms#6679]
**Is your feature request related to a problem? Please describe.**

NetlifyCMS does not work with latest Nextjs due to being above react 17

**Describe the solution you'd like**

I managed getting the cms to work locally with an error but it was working perfectly fine.  By adding the following to the package.json

```
 "override": {
    "react": "^18.2.0",
    "@types/react": "^18.0.25",
    "react-dom": "^18.2.0"
  },
```

However when deployed live as production build, cms is covered by an 'Application error: a client-side exception has occurred (see the browser console for more information)'.

I presume it is same error I am getting during development. Is just in production, it does let me get away with it.

Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'default')

Call Stack
default
../node_modules/next/dist/shared/lib/dynamic.js (69:21)

![error](https://user-images.githubusercontent.com/8676371/216380001-1d5e5258-766e-4cfd-b913-6db4e1679f7d.png)

Perhaps there is way around this but it seems is very likely that the CMS react version is behind my nextjs

**Comment by radenpioneer** [comment]
FYI, they are transferring ownership of NetlifyCMS to another company: https://www.netlify.com/blog/netlify-cms-to-become-decap-cms/

**Comment by martinjagodic** [comment]
Closing in favor of #6499
