### ISSUE TITLE
Empty entries inside collection

### ISSUE THREAD

**Issue by anastasiiaxfr** [decaporg/decap-cms#6684]
Hi,

I used in my static/admin/config.yml:
i18n:
  structure: multiple_folders

- label: "News"
    name: "news"
    folder: "content/" 
    path: 'news/{{slug}}'
    i18n: true

The Hugo file structure was:
content/ru/news
content/en/news
content/{{locale}}/{{section}}

All generated good if inside fields object not use default field:
http://joxi.ru/gmvdx3GH0BKJGA

But inside CMS i saw empty and duplicated entries and entries from other collection inside selected collection, like this:
http://joxi.ru/bmoGlk7slo1wlm
content > en > news > news-2023-02-05-11-50-1.md (empty)
http://joxi.ru/GrqERzNtby0OYr
http://joxi.ru/bmoGlk7slo15Jm
content > ru > news > news-2023-02-05-11-50-1.md (viewable content because, default locale RU)
http://joxi.ru/p27GJOdsZEbgn2

Why is it an empty file from the default locale when it has a translation? 

When I open file with not default locale I use empty fields inside
ex. default locale ru open file 
http://joxi.ru/Rmza7eltVG3llr
http://joxi.ru/Vm6MNvWCK06kMr

https://itg-news-hugo-netlifycms.netlify.app/admin 
(login: anastasiiaberest@gmail.com, password: tg6xctg6x)
https://github.com/anastasiiaxfr/itg-news-hugo-netlifycms
git@github.com:anastasiiaxfr/itg-news-hugo-netlifycms.git

By the way if you have multiple locales, when use default field properties it generate all locales files with the one what you select text content when saving one it's mistake, must be generate one file when you save it in selected locale, i mean, when i create new post i saw default lang ru, but after saving it generate also en, ua folders with data which default

**Comment by martinjagodic** [comment]
Closing as stale
