### ISSUE TITLE
Readme file contains incorrect links

### ISSUE THREAD

**Issue by naveen8801** [decaporg/decap-cms#6721]
**Describe the bug**
I can see readme file contains invalid links to Contribution.md, release, actions and license 

**To Reproduce**
Click on **License Badge** , **PRs Welcome**, **Build Status** Badges present inside Readme file.

**Expected behavior**
On Clicking these badges correct link should be opened

**Additional context**
I would like to fix it quickly 😃

**Comment by razonyang** [comment]
I think the #6718 fixes it. :)

**Comment by martinjagodic** [comment]
Fixed with #6718
