### ISSUE TITLE
The hugo starter points to a wrong url

### ISSUE THREAD

**Issue by Majd-eddine-BEN-TAHAR** [decaporg/decap-cms#6747]
**Describe the bug**
the hugo starter kit points to a wrong url which is https://github.com/AustinGreen/gatsby-starter-netlify-cms    and the actual url is https://github.com/decaporg/one-click-hugo-cms

**To Reproduce**
Steps to reproduce the behavior. For example:
1. Go to https://decapcms.org/docs/start-with-a-template
2. Click on Hugo Site Starter -> Deploy to Netlify
3. See error

**Expected behavior**
the deploy on gitub button will be disabled

**Comment by martinjagodic** [comment]
Fixed in #6748
