### ISSUE TITLE
Markdown editor: Hitting enter in the middle of a numbered line generates a new line, but doesn’t send the text to the right of the cursor to the next line

### ISSUE THREAD

**Issue by hetd54** [decaporg/decap-cms#6751]
**Describe the bug**
Hitting enter in the middle of a numbered line within the markdown editor generates a new line, but doesn’t send the text to the right of the cursor to the next line.

**To Reproduce**
(See screenshot below)
Within the Netlify CMS markdown editor, create a list.
Within number 1, write two sentences.
After you are finished typing, go to the start of the second sentence and enter a carriage return.

**Expected behavior**
Sentence 2 should be on list item 2

**Screenshots**
![image](https://user-images.githubusercontent.com/35639529/234034175-5a80b511-30e2-478e-a460-c018759ee288.png)

**Applicable Versions:**
 - Git provider: Github
 - OS: Mac Ventura
 - Browser version: Chrome 112
 - Node.JS version: 18

**CMS configuration**
https://github.com/thepolicylab-projectportals/project-portal-theme/tree/main/packages/project-portal-content-netlify

**Comment by hollandjg** [comment]
This also occurs:
- using https://github.com/decaporg/gatsby-starter-decap-cms without any modifications, 
- when deploying to Netlify.

**Comment by martinjagodic** [comment]
Solved in Decap 3
