### ISSUE TITLE
Nuxt content MDC new syntax

### ISSUE THREAD

**Issue by adinvadim** [decaporg/decap-cms#6758]
**Is your feature request related to a problem? Please describe.**
Simple integration with nuxt/content and related new feature MDC Syntax
https://content.nuxtjs.org/guide/writing/mdc/

**Describe the solution you'd like**
Highlight in markdown widget this samples:

```

::hero
Default slot text

#description
This will be rendered inside the `description` slot.
::

```
<img width="689" alt="image" src="https://user-images.githubusercontent.com/8646071/235659518-fb84bdb3-85ce-48e9-bdd7-17d71d8b992f.png">

**Comment by martinjagodic** [comment]
Hi @adinvadim, please fill out all the fields in the issue template. It's not clear from your description why you want this feature.
