### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by DomEscobar** [decaporg/decap-cms#6809]
**Describe the bug**
I tried to implement i18n into the gatsby blog template

**To Reproduce**
Add a template and change the i18n t

**Expected behavior**

**Screenshots**
![image](https://github.com/decaporg/decap-cms/assets/29872817/8121533a-64fe-4252-a7ff-4acc0c597ab4)

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms-app@2.15.72`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`

**CMS configuration**
[https://github.com/DomEscobar/gatsby-starter-decap-cms/blob/main/static/admin/config.yml](url)

**Comment by martinjagodic** [comment]
Hi @user, please fill out all the fields in the issue template. The information you provided is not enough to debug the problem.

I'm closing the issue for now. Once you add the missing information, I can open it again.
