### ISSUE TITLE
no authentication

### ISSUE THREAD

**Issue by njfamirm** [decaporg/decap-cms#6821]
I need to use decap CMS with minimum complexity, authentication complexities are too much for me!

I think the best method is to use the htpasswd file
Very simply, I put this file in /admin and authenticate without using a special service
for github access is possible to hard code token in client?

and can create feature for no authentication  backend?

**Comment by martinjagodic** [comment]
Hi @njfamirm, thanks for submitting.

First, the feature description is lacking explanation, please fill out all the fields in the issue template

Second, I think that hardcoding GitHub tokens is a security violation and that there is no place for it in Decap.

For these reasons, I'm closing the issue for now. Once you add the missing information, I can open it again.

**Comment by njfamirm** [comment]
Thank you for your response
I tried to provide additional explanations, this is all I could relate...

Of course, I came up with a better idea
If we can restrict user access to ‍`/admin`
Is it possible to get a secret token on the client-side and log in after returning?
