### ISSUE TITLE
Need the feature to publish multiple content at once 

### ISSUE THREAD

**Issue by AdityaKirad** [decaporg/decap-cms#6831]
when we use Decap CMS with static site generators like GatsbyJs every time we add a new content and publish it the whole app rebuilds but what if there are multiple content then we have to publish the content multiple times which means the whole app will rebuild then multiple times this process is not only inefficient but also time consuming and unnecessary computation power so if there will be feature to publish the multiple content all at once then the efficiency will increase time will be saved and unnecessary computation power will not be required this feature will be very helpful to those developers who have hosted their site in free tier since there we get limited amount of build time etc.

**Comment by martinjagodic** [comment]
Closing in favor of #6884
