### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'path')

### ISSUE THREAD

**Issue by edx-mostafa-eltahawy** [decaporg/decap-cms#6835]
**Describe the bug**
When i try to upload images from the media assets tab, firstly I cant see all my assets, secondly i get this error when i try uploading an asset. I am sure about the images folder path as it is the same path in all the collections and the media works perfectly under each collection

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms-app@2.15.72`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`

**CMS configuration**
```
backend:
  name: git-gateway
  branch: main
media_folder: ../../src/images
public_folder: ../../src/images
collections:
...

**Comment by martinjagodic** [comment]
Hi @edx-mostafa-eltahawy, please fill out all the fields in the issue template. The information you provided is not enough to debug the problem.

I'm closing the issue for now. Once you add the missing information, I can open it again.
