### ISSUE TITLE
.org file extension support for org-mode syntax

### ISSUE THREAD

**Issue by 4www** [decaporg/decap-cms#6844]
[org-mode](https://orgmode.org) documents, like markdown, have an accessible and powerful syntax, to write plain text and [export to other formats, such as HTML](https://orgmode.org/manual/Exporting.html).

decap-cms, supports editing formats such as JSON and markdown, and I wonder what could be a path to integrate support of an other content file type.

# about org-mode

Although, built in emacs lisp, and built-into emacs, org mode documents and [syntax](https://orgmode.org/worg/org-syntax.html) is supported in [many other editors and projects](https://orgmode.org/#editors), and gives access to [many new features](https://orgmode.org/features.html) on "just plain text" (and their HTML exported version).

It seems there are various active projects for parsing org files in the javascript npm ecosystem:
- https://github.com/orgapp/orgajs
- https://github.com/rasendubi/uniorg
- https://www.npmjs.com/search?q=org-mode%20emacs

Additionally:
- considered a "lightweight markup format" in [pandoc](https://pandoc.org)
- has a built-in [AST exporter](https://orgmode.org/worg/dev/org-element-api.html)
- [extensible manual](https://orgmode.org/manual), and [compact guide](https://orgmode.org/guide/)

# Is your feature request related to a problem? Please describe.

This is not a problem, and considered an enhancement, for supporting org document syntax in decap-cms.

User of org mode and its syntax, in IDEs and text editors, are already probably satisfied with their editing and publishing setup.

In order to onboard non IDE users, through the interface of decap-cms, it would be nice to offer access to edit org documents in the background (and have these changes saved to the git repository).

# Describe the solution you'd like

Like currently in decap-cms, for `.json`, `.md`, `.toml`, `.yml` etc. files, it would be nice to accept `.org` files and their syntax (maye `.txt` files too, with either markdown front matter and content, org plain text, org mode content).

Add the possibility to edit the content of org documents, and like markdown's front-matter, add specific keys to an org document.

Maybe add support for [org-insert-structure-template](https://orgmode.org/manual/Structure-Templates.html) in the text content, like the "text editor widgets" registration.

# Describe alternatives you've considered

I am not sure of any alternative, but continue "not using a git based CMS", if the objective is to use org document syntax.

As in the context of using .org documents to generate HTML sites, it could be possible to also use markdown files in the content folder (maybe with a separation of concern with .org and .md files, as well as .json files; and have org mode first export to markdown, or pandoc convert the markdown to org-mode or vice-versa)

[Uniorg](https://github.com/rasendubi/uniorg) can transform (uni)org syntax trees to [rehype](https://github.com/rehypejs/rehype) markdown.

# Additional context

Currently [working on a static site generator](https://gitlab.com/sctlib/emacs-ssg), that uses org-mode and emacs to convert content `.org` and `.txt` files into HTML websites. It mainly provides a default project structure and documentation to how to use these tools.

There are also [other static site projects](https://orgmode.org/worg/org-blog-wiki.html), such as [webloarg](https://emacs.love/weblorg/) using org syntax; [jekyll](https://orgmode.org/worg/org-tutorials/org-jekyll.html) also can support org syntax (and is used by default for github pages).

Additionally github, gitlab and other git providers support org text documents for the readme displayed on repositories.

Also a long time user of decap/netlify-cms, I imagine the combination of org documents, git and git based decap-cms, as very interesting. 

I am not sure if that is possible, and I'm looking forward to exploring how that could be achieved.

If there any pointers to which part of the code should be looked, I'll gladly look at them.

Cheers!

**Comment by mmkal** [comment]
Would be covered by https://github.com/decaporg/decap-cms/pull/6205

**Comment by martinjagodic** [comment]
@4www @mmkal this is now released in 3.0.3. Can you test and confirm that it works?

**Comment by mmkal** [comment]
@martinjagodic I haven't tested (or heard of) org-mode but I think this should be closed given the feature to support custom formats is now in. If there's a problem with a particular format it's a bug, I can likely help if someone raises one so feel free to tag me if it comes up.

**Comment by martinjagodic** [comment]
Great, thanks. Closing.

**Comment by 4www** [comment]
Sorry, haven't had the opportunity to test it. Will try to do that soon, and will post a feedback here if that's alright. Thanks!
