### ISSUE TITLE
TypeError: Expected "0" to be defined

### ISSUE THREAD

**Issue by sumlautollner** [decaporg/decap-cms#6858]
**Describe the bug**
Since Today I am no longer able to login to the Decap-CMS, hosted on Netlify
**To Reproduce**
Login to CMS 
**Expected behavior**
Login and see Admin Interface of Decap-CMS
**Screenshots**

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms@2.10.192`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0`

**CMS configuration**
```
backend:
  name: git-gateway
  branch: master
media_folder: static/images
public_folder: public/images
collections:
  - name: Blog Posts (en)
    label: en_posts
    folder: content/posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Draft
        name: draft
        widget: boolean
        default: true
      - label: Categories
        name: Categories
        widget: string
        required: false
      - label: Tags
        name: Tags
        widget: string
        required: false
      - label: Featured Image
        name: featuredImage
        widget: image
        required: false
      - label: Featured Image Preview
        name: featuredImagePreview
        widget: image
        required: false
      - label: Body
        name: body
        widget: markdown
    publish: true
    type: folder_based_collection
    sortable_fields:
      - commit_date
      - title
      - date
      - commit_author
    view_filters: []
    view_groups: []
publish_mode: simple
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
isFetching: false
error: null

```

**Additional context**
s/<@https://unpkg.com/netlify-cms@2.10.192/dist/netlify-cms.js:75:330119 E@https://unpkg.com/netlify-cms@2.10.192/dist/netlify-cms.js:34:66065 S/<@https://unpkg.com/netlify-cms@2.10.192/dist/netlify-cms.js:34:66325 gs@https://unpkg.com/netlify-cms@2.10.192/dist/netlify-cms.js:188:107583 ul@https://unpkg.com/netlify-cms@2.10.192/dist/netlify-cms.js:188:96719 sl@https://unpkg.com/netlify-cms@2.10.192/dist/netlify-cms.js:188:96642 Js@https://unpkg.com/netlify-cms@2.10.192/dist/netlify-cms.js:188:93672 Vi/<@https://unpkg.com/netlify-cms@2.10.192/dist/netlify-cms.js:188:45314 t.unstable_runWithPriority@https://unpkg.com/netlify-cms@2.10.192/dist/netlify-cms.js:196:3844 qi@https://unpkg.com/netlify-cms@2.10.192/dist/netlify-cms.js:188:45023 Vi@https://unpkg.com/netlify-cms@2.10.192/dist/netlify-cms.js:188:45261 $i@https://unpkg.com/netlify-cms@2.10.192/dist/netlify-cms.js:188:45194 el@https://unpkg.com/netlify-cms@2.10.192/dist/netlify-cms.js:188:93963 notify@https://unpkg.com/netlify-cms@2.10.192/dist/netlify-cms.js:28:10514 notifyNestedSubs@https://unpkg.com/netlify-cms@2.10.192/dist/netlify-cms.js:28:11110 i@https://unpkg.com/netlify-cms@2.10.192/dist/netlify-cms.js:28:10944 v@https://unpkg.com/netlify-cms@2.10.192/dist/netlify-cms.js:48:41561 t.waitUntilAction/</<@https://unpkg.com/netlify-cms@2.10.192/dist/netlify-cms.js:75:349430 r/</</<@https://unpkg.com/netlify-cms@2.10.192/dist/netlify-cms.js:220:38492 dispatch@https://unpkg.com/netlify-cms@2.10.192/dist/netlify-cms.js:48:43279 t.loginUser/</<@https://unpkg.com/netlify-cms@2.10.192/dist/netlify-cms.js:48:52458

**Comment by martinjagodic** [comment]
Hi @sumlautollner, please fill out all the fields in the issue template. The information you provided is not enough to debug the problem.

I'm closing the issue for now. Once you add the missing information, I can open it again.
