### ISSUE TITLE
Relative image in markdown body

### ISSUE THREAD

**Issue by eur2** [decaporg/decap-cms#6899]
Hi, is there any possibility to add relative path to images in markdown body?
I'm using the news Folder Collections Media and Public Folder like this:
```
  - name: posts
    label: Posts
    label_singular: 'Post'
    folder: content/posts
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
```
I need that the images are rendered with a relative path:
`![A starry night sky.](./stars.png) 
`and not like that:
`![A starry night sky.](stars.png)`

**Comment by martinjagodic** [comment]
You can create a custom editor component, I think you could achieve that there. Closing the issue as not an issue.
