### ISSUE TITLE
On Hover Effect for Join us on Discord Button on home page

### ISSUE THREAD

**Issue by Shreyashingale** [decaporg/decap-cms#6914]
**Description:**
I'd like to suggest adding an "on hover" effect to the "Join Us On Discord" button the on home page in the project. This feature would enhance the user experience by providing visual feedback when a user hovers their mouse pointer over a button. It can make the project look more interactive and engaging.

**Implementation Suggestions:**
If you have any ideas on how this feature can be implemented or if you're willing to contribute to the implementation, please share your thoughts.

**Screenshots:**
The image I have provided is a recent image where there is no hover event on the button

![image](https://github.com/decaporg/decap-cms/assets/85663556/6eeb29e7-50e4-4e87-aaeb-37fd8771a358)

**Additional Context:**
If you wish to add this feature I am willing to work on this feature so you can assign it to me.

**Comment by Shreyashingale** [comment]
hi @martinjagodic can you assign it to me

**Comment by Shreyashingale** [comment]
Thanks I'll work on it

**Comment by Shreyashingale** [comment]
@martinjagodic  when should I expect review on the pull request

**Comment by martinjagodic** [comment]
@Shreyashingale I can't promise anything. This is an open source project so PRs are reviewed depending on the availability of the team. Currently, we are a bit booked so please be patient. Also, PRs are merged based on the value they bring to the code.

**Comment by Shreyashingale** [comment]
@martinjagodic  Ok, Thanks for the reply in the meantime I'll look for other issues in the repo.
