### ISSUE TITLE
Netlify Large Media is deprecated; suggest adding this to Decap CMS docs

### ISSUE THREAD

**Issue by rstavchansky** [decaporg/decap-cms#6917]
**Describe the bug**
Netlify Large Media is deprecated, and it's not yet acknowledged in the docs for Decap CMS

**Expected behavior**

Decap CMS points out that Large Media is deprecated.

**Additional context**

https://docs.netlify.com/large-media/overview/ (see deprecation notice)
Deprecation announcement: https://answers.netlify.com/t/large-media-feature-deprecated-but-not-removed/100804

**Comment by martinjagodic** [comment]
@rstavchansky thanks for bringing this to our attention. Contributions to docs are welcome :)

**Comment by martinjagodic** [comment]
Done in #6951
