### ISSUE TITLE
Indentation removed on .toml files

### ISSUE THREAD

**Issue by schaefsteven** [decaporg/decap-cms#6921]
**Describe the bug**
.toml files that are edited by Decap CMS have their indentation (leading whitespace) removed. For example, I start with this: 

```
[params]
    firstName = "John"
    lastName = "Smith"
```

And after editing I get this: 

```
[params]
firstName = "Joe"
lastName = "Bloe"
```

This may be desired in some situations, but for me, when I need to go back in and edit the file manually, it makes it much harder to read.

**Applicable Versions:**
 - Decap CMS version: netlify-cms-core 2.55.2, netlify-cms-app 2.15.72
 - Git provider: Github
 - OS: Debian 12
 - Browser version: Chrome Version 116.0.5845.96

**CMS configuration**
```
local_backend: true
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
# logo_url:
# display_url:
media_folder: static/img
  # media_library:
  # name: 'disabled' # To disable the media library
public_folder: /img
collections:
  - name: 'config'
    label: 'Site Config'
    editor:
      preview: false
    files:
      - name: 'config'
        label: 'Contact Info'
        file: 'config.toml'
        format: 'toml'
        fields: 
        - { label: 'Contact Info',
            name: 'params',
            widget: 'object',
            fields: [
              { label: 'First Name', name: 'firstName', widget: 'string' },
              { label: 'Last Name', name: 'lastName', widget: 'string' },
              { label: 'Email', name: 'primEmail', widget: 'string' },
              { label: 'Phone Number', name: 'primPhone', widget: 'string' },
            ],
          }
```

**Additional context**

**Comment by martinjagodic** [comment]
@schaefsteven thanks for raising this topic. Indentation is optional in Toml, therefore having it vs. not having it is a matter of opinion. This is also potentially a breaking change for some users, who expect this type of formatting.

To conclude: let's keep the current formatting.

**Comment by mmkal** [comment]
This seems like something that could be overridden with a custom formatter: https://decapcms.org/docs/beta-features/#custom-formatters. There's an example of how you could change the yaml formatter in the docs, toml would be very similar.

**Comment by martinjagodic** [comment]
@mmkal thanks for pointing this out, I was not aware of this feature

**Comment by schaefsteven** [comment]
> This seems like something that could be overridden with a custom formatter: https://decapcms.org/docs/beta-features/#custom-formatters. There's an example of how you could change the yaml formatter in the docs, toml would be very similar.

Thanks for the advice! I will have to investigate this more when I have time, but yes, if I can swap out the formatter, that should be able to achieve the desired results.
