### ISSUE TITLE
Error: Cannot find a descendant at path [7,0,0,0,2] in node: {"children":[{"type":"paragraph","ch...

### ISSUE THREAD

**Issue by nanqic** [decaporg/decap-cms#6993]
**Describe the bug**
when edit，I press Shift+Enter , then
Error
There's been an error - please [open an issue on GitHub.](https://github.com/decaporg/decap-cms/issues/new?title=Error%3A+Cannot+find+a+descendant+at+path+%5B7%2C0%2C0%2C0%2C2%5D+in+node%3A+%7B%22children%22%3A%5B%7B%22type%22%3A%22paragraph%22%2C%22ch...&body=%0A**Describe+the+bug**%0A%0A**To+Reproduce**%0A%0A**Expected+behavior**%0A%0A**Screenshots**%0A%0A**Applicable+Versions%3A**%0A+-+Decap+CMS+version%3A+%60decap-cms%403.0.12%60%0A+-+Git+provider%3A+%60git-gateway%60%0A+-+Browser+version%3A+%60Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F119.0.0.0+Safari%2F537.36+Edg%2F119.0.0.0%60%0A%0A**CMS+configuration**%0A%60%60%60%0Abackend%3A%0A++name%3A+git-gateway%0A++branch%3A+master%0Amedia_folder%3A+static%2Ff%2Fup%0Apublic_folder%3A+%2Ff%2Fup%0Acollections%3A%0A++-+name%3A+posts%0A++++label%3A+Posts%0A++++label_singular%3A+Post%0A++++description%3A+%7C%0A++++++%E5%8F%91%E5%B8%83%E5%AD%A6%E4%B9%A0%E5%B0%8F%E7%BB%84%E5%85%B1%E4%BF%AE%E9%80%9A%E7%9F%A5.%0A++++folder%3A+content%2Fposts%0A++++extension%3A+md%0A++++format%3A+frontmatter%0A++++slug%3A+%22%7B%7Byear%7D%7D-%7B%7Bmonth%7D%7D-%7B%7Bday%7D%7D-%7B%7Bslug%7D%7D%22%0A++++summary%3A+%22%7B%7Btitle%7D%7D+--+%7B%7Byear%7D%7D%2F%7B%7Bmonth%7D%7D%2F%7B%7Bday%7D%7D%22%0A++++create%3A+true%0A++++sortable_fields%3A%0A++++++-+date%0A++++++-+commit_date%0A++++++-+title%0A++++++-+commit_author%0A++++view_groups%3A%0A++++++-+label%3A+Year%0A++++++++field%3A+date%0A++++++++pattern%3A+%5Cd%7B4%7D%0A++++++++id%3A+date__%5Cd%7B4%7D%0A++++++-+label%3A+Tags%0A++++++++field%3A+tags%0A++++++++id%3A+tags__undefined%0A++++fields%3A%0A++++++-+label%3A+Title%0A++++++++name%3A+title%0A++++++++widget%3A+string%0A++++++++tagname%3A+h1%0A++++++-+label%3A+Publish+Date%0A++++++++name%3A+date%0A++++++++widget%3A+datetime%0A++++++++dateFormat%3A+YYYY-MM-DD%0A++++++++timeFormat%3A+HH%3Amm%3Ass%0A++++++++format%3A+YYYY-MM-DD+HH%3Amm%3AssZ%0A++++++++date_format%3A+YYYY-MM-DD%0A++++++++time_format%3A+HH%3Amm%3Ass%0A++++++-+label%3A+Categories%0A++++++++name%3A+categories%0A++++++++widget%3A+list%0A++++++++default%3A%0A++++++++++-+%E6%85%A7%E7%81%AF%E7%A6%85%E4%BF%AE%E7%8F%AD%0A++++++-+label%3A+Tags%0A++++++++name%3A+tags%0A++++++++widget%3A+list%0A++++++++default%3A%0A++++++++++-+201x%E5%B1%8A%0A++++++-+label%3A+Attachments+%28Once+uploaded%2Fselected%2C+you+can+copy+the+link+from+preview%0A++++++++++panel+to+body+windown+below%29%0A++++++++name%3A+attachments%0A++++++++widget%3A+file%0A++++++++required%3A+false%0A++++++++media_library%3A%0A++++++++++config%3A%0A++++++++++++multiple%3A+true%0A++++++-+label%3A+Body%0A++++++++name%3A+body%0A++++++++widget%3A+markdown%0A++++++++hint%3A+Main+content+goes+here.%0A++++publish%3A+true%0A++++type%3A+folder_based_collection%0A++++view_filters%3A+%5B%5D%0Apublish_mode%3A+simple%0Aslug%3A%0A++encoding%3A+unicode%0A++clean_accents%3A+false%0A++sanitize_replacement%3A+%22-%22%0AisFetching%3A+false%0Aerror%3A+null%0A%0A%60%60%60%0A%0A**Additional+context**%0A&labels=type%3A+bug)
**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**
 - Decap CMS version: `decap-cms@3.0.12`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0`

**CMS configuration**
```
backend:
  name: git-gateway
  branch: master
media_folder: static/f/up
public_folder: /f/up
collections:
  - name: posts
    label: Posts
    label_singular: Post
    description: |
      发布学习小组共修通知.
    folder: content/posts
    extension: md
    format: frontmatter
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{title}} -- {{year}}/{{month}}/{{day}}"
    create: true
    sortable_fields:
      - date
      - commit_date
      - title
      - commit_author
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
        id: date__\d{4}
      - label: Tags
        field: tags
        id: tags__undefined
    fields:
      - label: Title
        name: title
        widget: string
        tagname: h1
      - label: Publish Date
        name: date
        widget: datetime
        dateFormat: YYYY-MM-DD
        timeFormat: HH:mm:ss
        format: YYYY-MM-DD HH:mm:ssZ
        date_format: YYYY-MM-DD
        time_format: HH:mm:ss
      - label: Categories
        name: categories
        widget: list
        default:
          - 慧灯禅修班
      - label: Tags
        name: tags
        widget: list
        default:
          - 201x届
      - label: Attachments (Once uploaded/selected, you can copy the link from preview
          panel to body windown below)
        name: attachments
        widget: file
        required: false
        media_library:
          config:
            multiple: true
      - label: Body
        name: body
        widget: markdown
        hint: Main content goes here.
    publish: true
    type: folder_based_collection
    view_filters: []
publish_mode: simple
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
isFetching: false
error: null

```

**Additional context**

**Comment by martinjagodic** [comment]
Hi @nanqic, please fill out all the fields in the issue template. The information you provided is not enough to debug the problem.

I'm closing the issue for now. Once you add the missing information, I can open it again.
