### ISSUE TITLE
Potential typo?

### ISSUE THREAD

**Issue by ryangittings** [decaporg/decap-cms#7003]
See typo on line that is shown in an error when a widget is missing:

https://github.com/decaporg/decap-cms/blob/9dc2fbd3acc96344b7d4a95862b338db04c3bd24/packages/decap-cms-widget-list/src/ListControl.js#L674

**Comment by martinjagodic** [comment]
haha 💩 happens 😅

**Comment by martinjagodic** [comment]
Closed in #7249
