### ISSUE TITLE
Error: Failed to load config.yml with hugo

### ISSUE THREAD

**Issue by RashiqAzhan** [decaporg/decap-cms#7023]
**Describe the bug**
Unable to load config.yml on the admin panel with minimal hugo example from the docs.
```
Error: Failed to load config.yml (404)
```

**To Reproduce**
I've followed up to [here](https://decapcms.org/docs/hugo/#getting-started-with-decap-cms) and then set up the `config.yml` as show [here](https://decapcms.org/docs/beta-features/#configure-the-decap-server-port-number)

I did `npx decap-server` and `hugo server` respectively in case the order matters.

**Expected behavior**
Admin panel loads.

**Applicable Versions:**

 - Decap CMS version: 3.0.12
 - Git provider: local
 - OS: Arch
 - Browser version: Firefox 120.0.1
 - hugo: 0.121.1
 - Node.JS: v21.5.0

**CMS configuration**
static/admin/config.yml
```yaml
local_backend: true

backend:
  name: git-gateway
```

**Comment by martinjagodic** [comment]
@RashiqAzhan please provide a screenshot of your error

**Comment by RashiqAzhan** [comment]
![image](https://github.com/decaporg/decap-cms/assets/7370540/6e8a1fcf-e6f5-4010-96a3-5dd63eb82ce7)

Here it is.

**Comment by tonyd256** [comment]
Not sure if it's helpful, but I use Eleventy and had to manually pass through the config file in the build settings. For eleventy it was adding `config.addPassthroughCopy({ "admin/config.yml": "admin/config.yml" });` to my `.eleventy.js` config file.

**Comment by hip3r** [comment]
@RashiqAzhan config.yml is missing required fields.
I get this response when trying with it 
![image](https://github.com/decaporg/decap-cms/assets/10455862/64f99faf-2934-4984-b8c3-2e206d155808)

Initial links are gone, see docs for configuration here https://decapcms.org/docs/configure-decap-cms/
