### ISSUE TITLE
Markdown editor: stop persisting empty blocks

### ISSUE THREAD

**Issue by erquhart** [decaporg/decap-cms#703]
**- Do you want to request a *feature* or report a *bug*?**
Improvement

**- What is the current behavior?**
If I create a block in the visual editor, the associated markdown is immediately created stored in state, so their present in the HTML preview, and in the markdown, which is observed if you save or switch to the raw editor. If you create an H2 and then don't use it, and save/exit, there will be two hashes persisted in that spot, which wouldn't be expected by users of the visual editor, since they shouldn't be concerned with the mechanics of markdown.

Another manifestation is that, if a user creates an empty list item, an asterisk is added in the markdown and displayed in the HTML, and only becomes a list item when content is added.

**- If the current behavior is a bug, please provide the steps to reproduce.**
* Create an empty list item
* Observe asterisk in HTML preview

**- What is the expected behavior?**
No asterisk should be shown

**- Please mention your CMS, node.js, and operating system version.**
CMS 0.5.1

**Comment by erquhart** [comment]
We should probably resolve this by stripping empty blocks in a new Remark plugin, which would run on every Markdown stringification here: https://github.com/netlify/netlify-cms/blob/master/src/components/Widgets/Markdown/serializers/index.js#L135

**Comment by theoephraim** [comment]
Just wanted to bump this up.

I'm getting empty headings saved in my markdown fields, which renders as "#".
Pretty unintuitive for end-users, especially when they have to wait for a build to see it.

**Comment by erquhart** [comment]
cc/ #2402

**Comment by erquhart** [comment]
This case should be tested after #2828 is merged.
