### ISSUE TITLE
Documentation: split up Add To Your Site into standalones

### ISSUE THREAD

**Issue by privatemaker** [decaporg/decap-cms#7051]
There are some pages in the documentation that are rather long in the current information architecture and file management, the most important one is:

- [Add To Your Site](https://decapcms.org/docs/add-to-your-site)

The current #anchor style long page has some negative user-experience aspects:

1. When loading the page via external link or manually loading these pages in browsers address bar the user lands on the page and the scrolling action starts. 

![decap-docs-page-title-linking](https://github.com/decaporg/decap-cms/assets/49612519/f24d5820-5aad-4c0a-b21f-f4727c31786a)

2. When clicking on the leftbar TOC the page scrolls and properly shows the title. However, the scrolling is rather time intensive and distracting compared to a normal page load, as well as losing the entire leftbar navigation above the top of screen which is disorienting.

![decap-docs-page-title-clicking](https://github.com/decaporg/decap-cms/assets/49612519/16697739-9322-4495-9237-fee2b754defd)

3. These sections are semantically different (and important enough) I think that warrants it's own pages.

I propose migrating each of the `Add To Your Site` sections to their own pages

- [x] [App File Structure](https://decapcms.org/docs/add-to-your-site/#app-file-structure)
- [x] [Configuration](https://decapcms.org/docs/add-to-your-site/#configuration)
- [x] [Authentication](https://decapcms.org/docs/add-to-your-site/#authentication)
- [x] [Accessing the CMS](https://decapcms.org/docs/add-to-your-site/#accessing-the-cms)

**Comment by martinjagodic** [comment]
@privatemaker this is a really good point. Also, the authentication section needs an update to include other options besides Netlify. I would do the rewrite as another PR. Would you take over the file reorg?

**Comment by privatemaker** [comment]
@martinjagodic yah i'm up for doing this. I will start a new PR once the Beta Features are done being merged.
