### ISSUE TITLE
Netlify Identity not using custom email templates 

### ISSUE THREAD

**Issue by jenlampton** [decaporg/decap-cms#7096]
First, sorry if this is the wrong place for this issue, but I was told I would be more likely to get help here than in the Netlify forum.

**Describe the bug**

Our custom email templates are not being used.

I am using Netlify CMS (now Decap) with Netlify Identity to log in. But nobody is able to log in because nobody is able to set a password. This is due to several separate problems, but the first one is that the password reset emails that are being sent do not contain the path `/admin#` at the end of the URL. 

Manually changing the path to include `/admin#` before navigating to that page does result in people being logged in immediately. Unfortunately since there is no way to set a password ([a separate issue](https://answers.netlify.com/t/missing-netlify-identity-modal-on-password-reset/33107)!), our only option is to use this password reset process to log in every time. It would be nice if we could get these emails working :)

We have created custom email templates that include the `/admin#` path, committed them to our repo, and have "hooked them up" via the various places in the Netlify Identity dashboard.  Sadly, they are not being used.

**To Reproduce**
1. Create a custom email template for password reset, and commit it into your repository
2. Within Netlify, navigate to `configuration/identity#emails` and specify the path to this new template
3. Within Netlify, navitate to `/integrations/identity/netlify` and send yourself the password reset email
4. Confirm that the template has not been used

**Expected behavior**
Specified templates should be used.

**Screenshots**

**Applicable Versions:**
 - Netlify CMS version: (I don't know where to find this) ??
 - Git provider: GitHub
 - OS: Mac OS Ventura 13.5.2
 - Browser version: Google Chrome Version 121.0.6167.85 (but also confirmed on Firefox and in various incognito windows)
 - Node.JS version: v19.6.1

**CMS configuration**

There is no `config.yml` file in our repository.

**Additional context**

**Comment by martinjagodic** [comment]
Hi @jenlampton, this repo is intended for Decap CMS related issues. For Netlify build related issues I suggest reaching out in the forums: https://answers.netlify.com/

Closing the issue, and please comment if you have any other questions.
