### ISSUE TITLE
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child o...

### ISSUE THREAD

**Issue by HAG87** [decaporg/decap-cms#7106]
**Applicable Versions:**
 - Decap CMS version: `decap-cms-app@3.1.1`
 - Git provider: `bitbucket`
 - Browser version: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0`

**CMS configuration**
```
backend:
  name: bitbucket
  repo: ...
  branch: main
  app_id: ...
  auth_type: implicit
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"
local_backend: true
media_folder: static/img
public_folder: /img

**Comment by gxanshu** [comment]
same issue

**Comment by martinjagodic** [comment]
Hi @HAG87, please fill out all the fields in the issue template. The information you provided is not enough to debug the problem.

**Comment by jackmahoney** [comment]
Also experiencing this. The auth is failing with 404 for bitbucket implicit.

**Comment by martinjagodic** [comment]
Closing as duplicate of #7183

**Comment by razzeee** [comment]
Also duplicates https://github.com/decaporg/decap-cms/issues/7105#issue-2137512462
