### ISSUE TITLE
Integrate netlify-identity-widget capabilities into Decap CMS.

### ISSUE THREAD

**Issue by punterpleural** [decaporg/decap-cms#7113]
**Is your feature request related to a problem? Please describe.**
Are there plans for updating the netlify-identity-widget?  When we updated Decap CMS 3.0.12 to 3.1.1, the netlify-identity-widget stopped working.  We received the following error: "the uri was missing". Upon reverting back to 3.0.12, it began working again

**Describe the solution you'd like**
It would be awesome if the netfligy-identiy-widget could be taken over by decaporg and either updated to work with the latest versions of Decap CMS or even better, brough into Decap CMS itself so the widget does not have to be used at all.

**Describe alternatives you've considered**
Unfortunately, the only alternative we have found is to revert back to 3.0.12.

**Comment by martinjagodic** [comment]
This is probably a problem with Decap, not the identity widget. We will not internalize authentication tools as this will bring more work. 

To solve this, please rephrase your issue as a bug and provide more detail that will help somebody reproduce it.
