### ISSUE TITLE
Chat / Discord link issues

### ISSUE THREAD

**Issue by paul-hammant** [decaporg/decap-cms#7156]
On the home page the're a  "Join us on Discord" .. https://decapcms.org/chat .. that 404's

Within Discord, there's no server for decap-cms

**Comment by martinjagodic** [comment]
https://decapcms.org/chat redirects to this invite link: https://discord.com/invite/KZRDXmTm9v

We use a redirect because invite links can change often

**Comment by vhbui02** [comment]
This invite link is invalid
