### ISSUE TITLE
Tag with list widget don't add escape

### ISSUE THREAD

**Issue by Juniors017** [decaporg/decap-cms#7167]
Hi, 
my tag list widget no longer accepts spaces since the last update.
` 
 '- label: "Tags"
      name: "tags"
      widget: list
      required: false'
`

i use this script for use decap : 
** <script src="https://unpkg.com/decap-cms@^3.0.0/dist/decap-cms.js"></script>**

**Comment by adriandpdev** [comment]
important to fix this

**Comment by martinjagodic** [comment]
Hi @Juniors017, please fill out all the fields in the issue template. The information you provided is not enough to debug the problem.

I'm closing the issue for now. Once you add the missing information, I can open it again.
