### ISSUE TITLE
local backend and auth

### ISSUE THREAD

**Issue by krodelabestiole** [decaporg/decap-cms#7217]
netlifyCMS used to have a _local_ backend such as :

```
backend:
  name: local
```
from the fact it doesn't work anymore and [the documentation](https://decapcms.org/docs/working-with-a-local-git-repository/) I understand it has more or less been replaced by the _git-gateway_ backend :
```
backend:
  name: git-gateway

local_backend: true
```

However the _git-gateway_ backend is prompting me for an email and password -while the _local_ backend was not.
Then it sends POST data to http://example.com/.netlify/identity/token which gives a 404 anyway.

I only use this for local testing purpose, no need for any auth. How could I get rid of this auth ?

**Comment by krodelabestiole** [comment]
(sorry, it seems I can't remove the _type: bug_ label)

**Comment by krodelabestiole** [comment]
I finally got it to work with :
```
backend:
  name: proxy
  proxy_url: 'http://localhost:8081/api/v1'
```
while running `npx decap-server`

I wonder why there is nothing about that in the doc though !

**Comment by martinjagodic** [comment]
if you're running `npx decap-server`, `local_backend: true` should be enough.

**Comment by jeffoxd** [comment]
> if you're running `npx decap-server`, `local_backend: true` should be enough.

Will cause this
```
Config Errors:

'backend' must have required property 'name'
```

**Comment by martinjagodic** [comment]
@jeffoxd my explanation was lacking.

You should combine your actual backend settings with `local_backend`. For example:

```
local_backend: true

backend:
  name: git-gateway
  ...
```

This will let decap-server know that it should work with your local directory. When using Decap without decap-server, it will use the backend settings. If you just need Decap for local development, you can just add some mock backend settings.
