### ISSUE TITLE
Formatting lost when copy-pasting from Google Docs to markdown widget

### ISSUE THREAD

**Issue by robbymilo** [decaporg/decap-cms#7233]
**Describe the bug**

Formatting such as bold text, headings, links etc. are lost when copy pasting from a word processor such as Google Docs.

Here is the behavior from Netlify CMS 2.15.72:

https://github.com/decaporg/decap-cms/assets/8106669/eec07104-8d31-418e-9277-13bdcc62c472

**To Reproduce**

Copy formatted text from a word processor and paste it into a markdown widget with "Rich text" selected:

https://github.com/decaporg/decap-cms/assets/8106669/a995e244-576b-4429-8a43-34052fa081fe

**Expected behavior**

The formatting remains and is converted to markdown.

**Screenshots**

See recordings above.

**Applicable Versions:**

 - Decap CMS version:
   - decap-cms-app 3.1.10
   - decap-cms-core 3.3.6
 - Git provider: GitHub
 - OS: Linux
 - Browser version Firefox 125.0b6

 - Node.JS version: n/a

**CMS configuration**

n/a

**Additional context**

Happy to make an attempt with a PR to fix this if you can point me to the code :)

**Comment by mirhamasala** [comment]
@martinjagodic Do you think this is something the team will be addressing, or is there a way we could assist with it (CC: @CharlyMartin @ barbaraperic)? It was quite useful for content teams to be able to copy and paste rich text into the widget without losing markup (such as links). 🙏🏼
