### ISSUE TITLE
chrome devtools high cpu while mapping sources

### ISSUE THREAD

**Issue by yuri-g-taboola** [decaporg/decap-cms#7268]
**Describe the bug**
The developer tools in Chrome utilizes high CPU while mapping the sources and it cause the whole page to be stuck for a few minutes

**To Reproduce**
1. start the project with npm start
2. open a post page
3.  open devtools and enable Javascript source maps if it's not enabled
4. switch between devtools tabs and try to open a source file

**Expected behavior**
The page is not being stuck

**Applicable Versions:**

 - Decap CMS version: 3.3.2
 - Git provider: test-repo
 - OS: Mac OS Sonoma 14.4
 - Browser version Chrome Version 127.0.6533.100 (Official Build) (arm64)
 - Node.JS version: v20.12.2

**Additional context**

Disabling the Javascript source maps solves the issue

**Comment by martinjagodic** [comment]
@yuri-g-taboola can you provide a screen recording of your issue? I have no issues with dev tools, nor have I heard about a similar issue from others.

**Comment by yuri-g-taboola** [comment]
@martinjagodic I can't reproduce it now either.
