### ISSUE TITLE
8 high severity vulnerabilities

### ISSUE THREAD

**Issue by d3vma** [decaporg/decap-cms#7295]
**Describe the bug**

**To Reproduce**

**Screenshots**

<img width="608" alt="image" src="https://github.com/user-attachments/assets/9feead46-3581-459e-9094-1b65f9058172">

**Applicable Versions:**

 - Decap CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [MacOS]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version: v22.5.1

**CMS configuration**

**Additional context**
It's just outdated! Too many plugins needs a bump to higher versions and a proper maintenance. I've had a great experience with NetlifyCMS few years ago integrating it with GatsbyJS. 
Now I am trying to get it work with `Astro` but apparently pretty much not secure and imho it's unusable.

**Comment by martinjagodic** [comment]
We are aware of this and we are tracking it under #6513. Unfortunately, it's not very easy to update so many dependencies with breaking changes, so we ask for your patience or your help with contributing. Closing as duplicate.
