### ISSUE TITLE
Should not alter abbr/acronym Markdown extra syntax

### ISSUE THREAD

**Issue by ArnaudLigny** [decaporg/decap-cms#777]
**- Do you want to request a *feature* or report a *bug*?**

A bug? 🐛 

**- What is the current behavior?**

`*[TIAA]: This Is An Acronym` is replaced by `_\[TIAA]: This Is An Acronym`

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. create a new collection item
2. switch to Markdown mode
3. add `*[TIAA]: This Is An Acronym` in the body of a collection item
4. save
5. see the content where `*[TIAA]: This Is An Acronym`is replaced by `_\[TIAA]: This Is An Acronym`

**- What is the expected behavior?**

Do not alter Markdown bloks with `*[FOO]`: Live it alone! :-)

**- Please mention your CMS, node.js, and operating system version.**

* Netlify CMS version 0.6.0
* MacOS Sierra 10.12.6
* Google Chrome 62.0.3202.75

**Comment by DirtyF** [comment]
There's [a remark plugin](https://www.npmjs.com/package/remark-abbr) for that, not currently used in NetlifyCMS.

**Comment by erquhart** [comment]
Awesome find on the plugin @DirtyF!

For escaping purposes (separate from actual parsing), the CMS is currently treating a leading asterisk as indicative of a list item, but we should be checking for a space after the asterisk as well.

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
