### ISSUE TITLE
Media library private mode switching can lead to inaccurate state

### ISSUE THREAD

**Issue by erquhart** [decaporg/decap-cms#835]
Related to #834.

If a user with an asset store integration switches in and out of private mode quickly while asset related requests are pending, the state of the library could become inaccurate. There should be no possibility of destructive consequences, and this is a fairly outside edge case.

We currently just check to see if the request originated from the current mode - instead we need to ensure that no mode changes have occurred since the request was made.

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
