### ISSUE TITLE
Validate entries before loading

### ISSUE THREAD

**Issue by erquhart** [decaporg/decap-cms#836]
**- Do you want to request a *feature* or report a *bug*?**

bug

**- What is the current behavior?**

An incorrectly formatted entry can crash the CMS.

**- If the current behavior is a bug, please provide the steps to reproduce.**

* Configure an entry type with a list widget containing one or more fields
* Manually create an entry of that type, but provide a list of strings as the value instead of the expected list of objects

**- What is the expected behavior?**

The CMS should gracefully error out using some sort of entry validation

**Comment by martinjagodic** [comment]
Closing as stale
