### ISSUE TITLE
Markdown widget loses focus on initial entry

### ISSUE THREAD

**Issue by erquhart** [decaporg/decap-cms#901]
**- Do you want to request a *feature* or report a *bug*?**

bug

**- What is the current behavior?**

The markdown editor uses a debounce for updating it's value in the redux store, about 150ms I believe. The first time this debounce runs, the editor loses focus. So usually just after the first character is typed. Only happens that one time in the session, and only if the editor was initially empty.

**- If the current behavior is a bug, please provide the steps to reproduce.**

* Open an entry with an empty markdown widget
* Start entering text

**- What is the expected behavior?**

Markdown widget should not lose focus.

**- Please mention your CMS, node.js, and operating system version.**

CMS 1.0.2

**Comment by erquhart** [comment]
It's almost certainly due to new logic included with 1.0:

https://github.com/netlify/netlify-cms/blob/master/src/components/EditorWidgets/Markdown/MarkdownControl/VisualEditor/index.js#L52-L58

**Comment by erquhart** [comment]
Had to revert fix, still an issue.

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
