### ISSUE TITLE
Broken Search when no content in content type

### ISSUE THREAD

**Issue by eliwilliamson** [decaporg/decap-cms#915]
**- Do you want to request a *feature* or report a *bug*?**
bug
**- What is the current behavior?**
search doesn't work if you have a content type without any content in it yet
**- If the current behavior is a bug, please provide the steps to reproduce.**
create a content type without any content then try to search
**- What is the expected behavior?**
it should return results - it doesn't
**- Please mention your CMS, node.js, and operating system version.**
1.0.0

@Benaiah i believe the api failed before it could complete a search. maybe add a line to skip over errors on missing content types?

ps. do i get added to the prestigious contributors list now? 😂

**Comment by tech4him1** [comment]
> ps. do i get added to the prestigious contributors list now? 😂

Sure do, you're already on our list: https://github.com/netlify/netlify-cms/issues/902#issuecomment-350396995 (or you can add yourself 😄 ).

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
