### ISSUE TITLE
[Discussion] Custom Widget Library

### ISSUE THREAD

**Issue by pungggi** [decaporg/decap-cms#919]
It would be nice to have a folder where the community can contribute to custom widgets...or does this exists already, i could not find anything in this repo..

**Comment by pungggi** [comment]
I suggest the first widget to add should be that from the blog https://www.netlify.com/blog/2017/06/20/extending-netlify-cms-part-one-custom-widgets/
What do you think?

**Comment by tech4him1** [comment]
@verythorough @erquhart What do you think of this?

**Comment by verythorough** [comment]
I think there are some cases where it would make sense to add a widget to the default widgets in the repo (like the [multiselect widget](https://github.com/netlify/netlify-cms/pull/922) in development now).

In other cases where the widget is less generic, we could add a "community-created widgets" section of the widgets doc, where people can link gists, repos, and/or tutorials for custom widgets they have created. I figure this makes for discoverability in a central location, while still allowing widget creators to store and maintain their code in a way that works for them.

**Comment by erquhart** [comment]
Agreed, I'd love to see major improvements in discoverability. Featuring community extensions is a big part of the current extensibility initiative.

**Comment by pungggi** [comment]
Yes, what really matters is  discoverability.. 
First, what for me would feel 'natural' is doing a search like this> https://yarnpkg.com/en/packages?q=netlify%20widget&p=1

So suggesting a default name convention to widget developers would help. like It should start by ...

Second, A linking section would also help for non-default named widgets..

sorry if my english is not that good I am not a native english speaker..

**Comment by erquhart** [comment]
Thanks @pungggi - your English is great, no problems there :)

I agree with establishing a naming convention, probably `netlify-cms-widget`. And building the kind of discovery that Gatsby is building right into the website would be awesome!

**Comment by cwahlfeldt** [comment]
Maybe the ecosystem would benefit from a third party app/site? Im thinking something similar to rusts package manager site https://crates.io/, or maybe even like a https://js.coach/, or https://vimawesome.com/.

**Comment by erquhart** [comment]
I'd like to see it built into netlifycms.org. I'm super inspired by this: http://nivo.rocks/#/components

Not only is it a visual playground, it allows you to configure components live, and it generates React component code (among other things) as output. Plus the public Storybook. Love love love.

**Comment by martinjagodic** [comment]
Closing in favor of #1286
