### ISSUE TITLE
Import external data? (Analytics, Shopify, Airtable)

### ISSUE THREAD

**Issue by LaneLourcey** [decaporg/decap-cms#935]
Is there a way to import external data files?

I have a few use cases in mind. 

- Importing Google Analytics data for page views by day/week/year for blog category page sorting

- Importing Shopify Products

- Downloading content from Airtable (or gSheets), preferably with the ability to turn linked fields into references in Netlify-CMS

**Comment by erquhart** [comment]
Nothing built in for now, it'd be an interesting feature to discuss. You could always export your data from those sources (likely to CSV), convert the CSV to JSON or YAML, and feed that to Netlify CMS. If you do get things set up, it'd be really cool to see a blog post walkthrough to help others on the same path.

Importing external data is a feature consideration, as I mentioned. Let's discuss that a bit further here.

**Comment by LaneLourcey** [comment]
@erquhart I'm a few months away from the project I'll be working on that I was interested in this for, but if I go that route and actually figure out a good way to fetch some external data I'll certainly make a repo and write a post about it!

I think one thing that makes this feature relatively complex is the huge variety of sources to import from, the types of data each source delivers, and structuring that data in a manner that netlifyCMS can consume it in a fairly automated manner. Since it's so customizable I'm not sure how one would go about making a solution that works for more than a very specific scenario.

**Comment by erquhart** [comment]
Agreed, a one-size-fits-all solution is unlikely, but examples definitely help, even if they're not the exact solution needed.

Going to leave this open for now in case others have thoughts from a feature standpoint.

**Comment by jeremyzilar** [comment]
I have been looking at building my own widget that just gets info from our Airtable API, and either
- inserts the data into Netlify CMS
- inserts just the ID of the record so we can pull the data in the build process

**Comment by mohab-sameh** [comment]
@jeremyzilar I've been looking into the same thing lately. Have you made any progress with this?
