### ISSUE TITLE
Proposal: convert example config to "learn x in y" style documentation

### ISSUE THREAD

**Issue by erquhart** [decaporg/decap-cms#947]
The config file under the example directory contains some lightweight examples and a few notes, but doesn't fully explain itself. Inspired by a recent conversation with @verythorough and suggestions by @benogle in #619, I propose that we improve the config file to essentially serve as standalone documentation. Learn X in Y Minutes' [guide to Go](https://learnxinyminutes.com/docs/go/) is a fantastic example of this approach in action.

Pros:
- helps folks with a "just show me" learning style grok cms configuration fast
- provides a complementary perspective to the docs site, as each approach may highlight things that the other doesn't
- can serve as an extension of the docs for fine details of configuration
- great place to show best practices for common use cases

Cons:
- maintaining overlapping docs in two different areas

**Comment by erquhart** [comment]
@verythorough I can't remember what issue you mentioned improving the example config in, but if this is a duplicate, please let me know.

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
